;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.asyncio
  "Raw bindings for SDL_asyncio.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def async-io-outcome
  "ffi/layout of SDL_AsyncIOOutcome."
  (ffi/layout [:struct [[:asyncio :pointer] [:type :int] [:result :int] [:buffer :pointer] [:offset :uint64] [:bytes-requested :uint64] [:bytes-transferred :uint64] [:userdata :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn async-io-from-file
  "SDL_AsyncIO * SDL_AsyncIOFromFile(const char * file, const char * mode)"
  {:arglists '([file mode]) :sdl/c "SDL_AsyncIOFromFile" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_AsyncIOFromFile" [:string :string] :pointer)

(ffi/defcfn get-async-io-size
  "Sint64 SDL_GetAsyncIOSize(SDL_AsyncIO * asyncio)"
  {:arglists '([asyncio]) :sdl/c "SDL_GetAsyncIOSize" :sdl/args [:pointer] :sdl/ret :int64}
  "SDL_GetAsyncIOSize" [:pointer] :int64)

(ffi/defcfn read-async-io
  "bool SDL_ReadAsyncIO(SDL_AsyncIO * asyncio, void * ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue * queue, void * userdata)"
  {:arglists '([asyncio ptr offset size queue userdata]) :sdl/c "SDL_ReadAsyncIO" :sdl/args [:pointer :pointer :uint64 :uint64 :pointer :pointer] :sdl/ret :bool}
  "SDL_ReadAsyncIO" [:pointer :pointer :uint64 :uint64 :pointer :pointer] :bool)

(ffi/defcfn write-async-io
  "bool SDL_WriteAsyncIO(SDL_AsyncIO * asyncio, void * ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue * queue, void * userdata)"
  {:arglists '([asyncio ptr offset size queue userdata]) :sdl/c "SDL_WriteAsyncIO" :sdl/args [:pointer :pointer :uint64 :uint64 :pointer :pointer] :sdl/ret :bool}
  "SDL_WriteAsyncIO" [:pointer :pointer :uint64 :uint64 :pointer :pointer] :bool)

(ffi/defcfn close-async-io
  "bool SDL_CloseAsyncIO(SDL_AsyncIO * asyncio, bool flush, SDL_AsyncIOQueue * queue, void * userdata)"
  {:arglists '([asyncio flush queue userdata]) :sdl/c "SDL_CloseAsyncIO" :sdl/args [:pointer :bool :pointer :pointer] :sdl/ret :bool}
  "SDL_CloseAsyncIO" [:pointer :bool :pointer :pointer] :bool)

(ffi/defcfn create-async-io-queue
  "SDL_AsyncIOQueue * SDL_CreateAsyncIOQueue(void)"
  {:arglists '([]) :sdl/c "SDL_CreateAsyncIOQueue" :sdl/args [] :sdl/ret :pointer}
  "SDL_CreateAsyncIOQueue" [] :pointer)

(ffi/defcfn destroy-async-io-queue
  "void SDL_DestroyAsyncIOQueue(SDL_AsyncIOQueue * queue)"
  {:arglists '([queue]) :sdl/c "SDL_DestroyAsyncIOQueue" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyAsyncIOQueue" [:pointer] :void)

(ffi/defcfn get-async-io-result
  "bool SDL_GetAsyncIOResult(SDL_AsyncIOQueue * queue, SDL_AsyncIOOutcome * outcome)"
  {:arglists '([queue outcome]) :sdl/c "SDL_GetAsyncIOResult" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetAsyncIOResult" [:pointer :pointer] :bool)

(ffi/defcfn wait-async-io-result
  "bool SDL_WaitAsyncIOResult(SDL_AsyncIOQueue * queue, SDL_AsyncIOOutcome * outcome, Sint32 timeoutMS)"
  {:arglists '([queue outcome timeout-ms]) :sdl/c "SDL_WaitAsyncIOResult" :sdl/args [:pointer :pointer :int32] :sdl/ret :bool}
  "SDL_WaitAsyncIOResult" [:pointer :pointer :int32] :bool :blocking)

(ffi/defcfn signal-async-io-queue
  "void SDL_SignalAsyncIOQueue(SDL_AsyncIOQueue * queue)"
  {:arglists '([queue]) :sdl/c "SDL_SignalAsyncIOQueue" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_SignalAsyncIOQueue" [:pointer] :void)

(ffi/defcfn load-file-async
  "bool SDL_LoadFileAsync(const char * file, SDL_AsyncIOQueue * queue, void * userdata)"
  {:arglists '([file queue userdata]) :sdl/c "SDL_LoadFileAsync" :sdl/args [:string :pointer :pointer] :sdl/ret :bool}
  "SDL_LoadFileAsync" [:string :pointer :pointer] :bool)
