;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.atomic
  "Raw bindings for SDL_atomic.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def atomic-int
  "ffi/layout of SDL_AtomicInt."
  (ffi/layout [:struct [[:value :int]]]))

(def atomic-u32
  "ffi/layout of SDL_AtomicU32."
  (ffi/layout [:struct [[:value :uint32]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn try-lock-spinlock
  "bool SDL_TryLockSpinlock(SDL_SpinLock * lock)"
  {:arglists '([lock]) :sdl/c "SDL_TryLockSpinlock" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TryLockSpinlock" [:pointer] :bool)

(ffi/defcfn lock-spinlock
  "void SDL_LockSpinlock(SDL_SpinLock * lock)"
  {:arglists '([lock]) :sdl/c "SDL_LockSpinlock" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_LockSpinlock" [:pointer] :void)

(ffi/defcfn unlock-spinlock
  "void SDL_UnlockSpinlock(SDL_SpinLock * lock)"
  {:arglists '([lock]) :sdl/c "SDL_UnlockSpinlock" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnlockSpinlock" [:pointer] :void)

(ffi/defcfn memory-barrier-release-function
  "void SDL_MemoryBarrierReleaseFunction(void)"
  {:arglists '([]) :sdl/c "SDL_MemoryBarrierReleaseFunction" :sdl/args [] :sdl/ret :void}
  "SDL_MemoryBarrierReleaseFunction" [] :void)

(ffi/defcfn memory-barrier-acquire-function
  "void SDL_MemoryBarrierAcquireFunction(void)"
  {:arglists '([]) :sdl/c "SDL_MemoryBarrierAcquireFunction" :sdl/args [] :sdl/ret :void}
  "SDL_MemoryBarrierAcquireFunction" [] :void)

(ffi/defcfn compare-and-swap-atomic-int
  "bool SDL_CompareAndSwapAtomicInt(SDL_AtomicInt * a, int oldval, int newval)"
  {:arglists '([a oldval newval]) :sdl/c "SDL_CompareAndSwapAtomicInt" :sdl/args [:pointer :int :int] :sdl/ret :bool}
  "SDL_CompareAndSwapAtomicInt" [:pointer :int :int] :bool)

(ffi/defcfn set-atomic-int
  "int SDL_SetAtomicInt(SDL_AtomicInt * a, int v)"
  {:arglists '([a v]) :sdl/c "SDL_SetAtomicInt" :sdl/args [:pointer :int] :sdl/ret :int}
  "SDL_SetAtomicInt" [:pointer :int] :int)

(ffi/defcfn get-atomic-int
  "int SDL_GetAtomicInt(SDL_AtomicInt * a)"
  {:arglists '([a]) :sdl/c "SDL_GetAtomicInt" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetAtomicInt" [:pointer] :int)

(ffi/defcfn add-atomic-int
  "int SDL_AddAtomicInt(SDL_AtomicInt * a, int v)"
  {:arglists '([a v]) :sdl/c "SDL_AddAtomicInt" :sdl/args [:pointer :int] :sdl/ret :int}
  "SDL_AddAtomicInt" [:pointer :int] :int)

(ffi/defcfn compare-and-swap-atomic-u32
  "bool SDL_CompareAndSwapAtomicU32(SDL_AtomicU32 * a, Uint32 oldval, Uint32 newval)"
  {:arglists '([a oldval newval]) :sdl/c "SDL_CompareAndSwapAtomicU32" :sdl/args [:pointer :uint32 :uint32] :sdl/ret :bool}
  "SDL_CompareAndSwapAtomicU32" [:pointer :uint32 :uint32] :bool)

(ffi/defcfn set-atomic-u32
  "Uint32 SDL_SetAtomicU32(SDL_AtomicU32 * a, Uint32 v)"
  {:arglists '([a v]) :sdl/c "SDL_SetAtomicU32" :sdl/args [:pointer :uint32] :sdl/ret :uint32}
  "SDL_SetAtomicU32" [:pointer :uint32] :uint32)

(ffi/defcfn get-atomic-u32
  "Uint32 SDL_GetAtomicU32(SDL_AtomicU32 * a)"
  {:arglists '([a]) :sdl/c "SDL_GetAtomicU32" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetAtomicU32" [:pointer] :uint32)

(ffi/defcfn add-atomic-u32
  "Uint32 SDL_AddAtomicU32(SDL_AtomicU32 * a, int v)"
  {:arglists '([a v]) :sdl/c "SDL_AddAtomicU32" :sdl/args [:pointer :int] :sdl/ret :uint32}
  "SDL_AddAtomicU32" [:pointer :int] :uint32)

(ffi/defcfn compare-and-swap-atomic-pointer
  "bool SDL_CompareAndSwapAtomicPointer(void ** a, void * oldval, void * newval)"
  {:arglists '([a oldval newval]) :sdl/c "SDL_CompareAndSwapAtomicPointer" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_CompareAndSwapAtomicPointer" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-atomic-pointer
  "void * SDL_SetAtomicPointer(void ** a, void * v)"
  {:arglists '([a v]) :sdl/c "SDL_SetAtomicPointer" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_SetAtomicPointer" [:pointer :pointer] :pointer)

(ffi/defcfn get-atomic-pointer
  "void * SDL_GetAtomicPointer(void ** a)"
  {:arglists '([a]) :sdl/c "SDL_GetAtomicPointer" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetAtomicPointer" [:pointer] :pointer)
