;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.audio
  "Raw bindings for SDL_audio.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def audio-spec
  "ffi/layout of SDL_AudioSpec."
  (ffi/layout [:struct [[:format :int] [:channels :int] [:freq :int]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-num-audio-drivers
  "int SDL_GetNumAudioDrivers(void)"
  {:arglists '([]) :sdl/c "SDL_GetNumAudioDrivers" :sdl/args [] :sdl/ret :int}
  "SDL_GetNumAudioDrivers" [] :int)

(ffi/defcfn get-audio-driver
  "const char * SDL_GetAudioDriver(int index)"
  {:arglists '([index]) :sdl/c "SDL_GetAudioDriver" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetAudioDriver" [:int] :string)

(ffi/defcfn get-current-audio-driver
  "const char * SDL_GetCurrentAudioDriver(void)"
  {:arglists '([]) :sdl/c "SDL_GetCurrentAudioDriver" :sdl/args [] :sdl/ret :string}
  "SDL_GetCurrentAudioDriver" [] :string)

(ffi/defcfn get-audio-playback-devices
  "SDL_AudioDeviceID * SDL_GetAudioPlaybackDevices(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetAudioPlaybackDevices" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetAudioPlaybackDevices" [:pointer] :pointer)

(ffi/defcfn get-audio-recording-devices
  "SDL_AudioDeviceID * SDL_GetAudioRecordingDevices(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetAudioRecordingDevices" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetAudioRecordingDevices" [:pointer] :pointer)

(ffi/defcfn get-audio-device-name
  "const char * SDL_GetAudioDeviceName(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_GetAudioDeviceName" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetAudioDeviceName" [:uint32] :string)

(ffi/defcfn get-audio-device-format
  "bool SDL_GetAudioDeviceFormat(SDL_AudioDeviceID devid, SDL_AudioSpec * spec, int * sample_frames)"
  {:arglists '([devid spec sample-frames]) :sdl/c "SDL_GetAudioDeviceFormat" :sdl/args [:uint32 :pointer :pointer] :sdl/ret :bool}
  "SDL_GetAudioDeviceFormat" [:uint32 :pointer :pointer] :bool)

(ffi/defcfn get-audio-device-channel-map
  "int * SDL_GetAudioDeviceChannelMap(SDL_AudioDeviceID devid, int * count)"
  {:arglists '([devid count]) :sdl/c "SDL_GetAudioDeviceChannelMap" :sdl/args [:uint32 :pointer] :sdl/ret :pointer}
  "SDL_GetAudioDeviceChannelMap" [:uint32 :pointer] :pointer)

(ffi/defcfn open-audio-device
  "SDL_AudioDeviceID SDL_OpenAudioDevice(SDL_AudioDeviceID devid, const SDL_AudioSpec * spec)"
  {:arglists '([devid spec]) :sdl/c "SDL_OpenAudioDevice" :sdl/args [:uint32 :pointer] :sdl/ret :uint32}
  "SDL_OpenAudioDevice" [:uint32 :pointer] :uint32)

(ffi/defcfn is-audio-device-physical
  "bool SDL_IsAudioDevicePhysical(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_IsAudioDevicePhysical" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_IsAudioDevicePhysical" [:uint32] :bool)

(ffi/defcfn is-audio-device-playback
  "bool SDL_IsAudioDevicePlayback(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_IsAudioDevicePlayback" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_IsAudioDevicePlayback" [:uint32] :bool)

(ffi/defcfn pause-audio-device
  "bool SDL_PauseAudioDevice(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_PauseAudioDevice" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_PauseAudioDevice" [:uint32] :bool)

(ffi/defcfn resume-audio-device
  "bool SDL_ResumeAudioDevice(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_ResumeAudioDevice" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_ResumeAudioDevice" [:uint32] :bool)

(ffi/defcfn audio-device-paused
  "bool SDL_AudioDevicePaused(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_AudioDevicePaused" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_AudioDevicePaused" [:uint32] :bool)

(ffi/defcfn get-audio-device-gain
  "float SDL_GetAudioDeviceGain(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_GetAudioDeviceGain" :sdl/args [:uint32] :sdl/ret :float}
  "SDL_GetAudioDeviceGain" [:uint32] :float)

(ffi/defcfn set-audio-device-gain
  "bool SDL_SetAudioDeviceGain(SDL_AudioDeviceID devid, float gain)"
  {:arglists '([devid gain]) :sdl/c "SDL_SetAudioDeviceGain" :sdl/args [:uint32 :float] :sdl/ret :bool}
  "SDL_SetAudioDeviceGain" [:uint32 :float] :bool)

(ffi/defcfn close-audio-device
  "void SDL_CloseAudioDevice(SDL_AudioDeviceID devid)"
  {:arglists '([devid]) :sdl/c "SDL_CloseAudioDevice" :sdl/args [:uint32] :sdl/ret :void}
  "SDL_CloseAudioDevice" [:uint32] :void)

(ffi/defcfn bind-audio-streams
  "bool SDL_BindAudioStreams(SDL_AudioDeviceID devid, SDL_AudioStream * const * streams, int num_streams)"
  {:arglists '([devid streams num-streams]) :sdl/c "SDL_BindAudioStreams" :sdl/args [:uint32 :pointer :int] :sdl/ret :bool}
  "SDL_BindAudioStreams" [:uint32 :pointer :int] :bool)

(ffi/defcfn bind-audio-stream
  "bool SDL_BindAudioStream(SDL_AudioDeviceID devid, SDL_AudioStream * stream)"
  {:arglists '([devid stream]) :sdl/c "SDL_BindAudioStream" :sdl/args [:uint32 :pointer] :sdl/ret :bool}
  "SDL_BindAudioStream" [:uint32 :pointer] :bool)

(ffi/defcfn unbind-audio-streams
  "void SDL_UnbindAudioStreams(SDL_AudioStream * const * streams, int num_streams)"
  {:arglists '([streams num-streams]) :sdl/c "SDL_UnbindAudioStreams" :sdl/args [:pointer :int] :sdl/ret :void}
  "SDL_UnbindAudioStreams" [:pointer :int] :void)

(ffi/defcfn unbind-audio-stream
  "void SDL_UnbindAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_UnbindAudioStream" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnbindAudioStream" [:pointer] :void)

(ffi/defcfn get-audio-stream-device
  "SDL_AudioDeviceID SDL_GetAudioStreamDevice(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamDevice" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetAudioStreamDevice" [:pointer] :uint32)

(ffi/defcfn create-audio-stream
  "SDL_AudioStream * SDL_CreateAudioStream(const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec)"
  {:arglists '([src-spec dst-spec]) :sdl/c "SDL_CreateAudioStream" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateAudioStream" [:pointer :pointer] :pointer)

(ffi/defcfn get-audio-stream-properties
  "SDL_PropertiesID SDL_GetAudioStreamProperties(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetAudioStreamProperties" [:pointer] :uint32)

(ffi/defcfn get-audio-stream-format
  "bool SDL_GetAudioStreamFormat(SDL_AudioStream * stream, SDL_AudioSpec * src_spec, SDL_AudioSpec * dst_spec)"
  {:arglists '([stream src-spec dst-spec]) :sdl/c "SDL_GetAudioStreamFormat" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetAudioStreamFormat" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-audio-stream-format
  "bool SDL_SetAudioStreamFormat(SDL_AudioStream * stream, const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec)"
  {:arglists '([stream src-spec dst-spec]) :sdl/c "SDL_SetAudioStreamFormat" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_SetAudioStreamFormat" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-audio-stream-frequency-ratio
  "float SDL_GetAudioStreamFrequencyRatio(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamFrequencyRatio" :sdl/args [:pointer] :sdl/ret :float}
  "SDL_GetAudioStreamFrequencyRatio" [:pointer] :float)

(ffi/defcfn set-audio-stream-frequency-ratio
  "bool SDL_SetAudioStreamFrequencyRatio(SDL_AudioStream * stream, float ratio)"
  {:arglists '([stream ratio]) :sdl/c "SDL_SetAudioStreamFrequencyRatio" :sdl/args [:pointer :float] :sdl/ret :bool}
  "SDL_SetAudioStreamFrequencyRatio" [:pointer :float] :bool)

(ffi/defcfn get-audio-stream-gain
  "float SDL_GetAudioStreamGain(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamGain" :sdl/args [:pointer] :sdl/ret :float}
  "SDL_GetAudioStreamGain" [:pointer] :float)

(ffi/defcfn set-audio-stream-gain
  "bool SDL_SetAudioStreamGain(SDL_AudioStream * stream, float gain)"
  {:arglists '([stream gain]) :sdl/c "SDL_SetAudioStreamGain" :sdl/args [:pointer :float] :sdl/ret :bool}
  "SDL_SetAudioStreamGain" [:pointer :float] :bool)

(ffi/defcfn get-audio-stream-input-channel-map
  "int * SDL_GetAudioStreamInputChannelMap(SDL_AudioStream * stream, int * count)"
  {:arglists '([stream count]) :sdl/c "SDL_GetAudioStreamInputChannelMap" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_GetAudioStreamInputChannelMap" [:pointer :pointer] :pointer)

(ffi/defcfn get-audio-stream-output-channel-map
  "int * SDL_GetAudioStreamOutputChannelMap(SDL_AudioStream * stream, int * count)"
  {:arglists '([stream count]) :sdl/c "SDL_GetAudioStreamOutputChannelMap" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_GetAudioStreamOutputChannelMap" [:pointer :pointer] :pointer)

(ffi/defcfn set-audio-stream-input-channel-map
  "bool SDL_SetAudioStreamInputChannelMap(SDL_AudioStream * stream, const int * chmap, int count)"
  {:arglists '([stream chmap count]) :sdl/c "SDL_SetAudioStreamInputChannelMap" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_SetAudioStreamInputChannelMap" [:pointer :pointer :int] :bool)

(ffi/defcfn set-audio-stream-output-channel-map
  "bool SDL_SetAudioStreamOutputChannelMap(SDL_AudioStream * stream, const int * chmap, int count)"
  {:arglists '([stream chmap count]) :sdl/c "SDL_SetAudioStreamOutputChannelMap" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_SetAudioStreamOutputChannelMap" [:pointer :pointer :int] :bool)

(ffi/defcfn put-audio-stream-data
  "bool SDL_PutAudioStreamData(SDL_AudioStream * stream, const void * buf, int len)"
  {:arglists '([stream buf len]) :sdl/c "SDL_PutAudioStreamData" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_PutAudioStreamData" [:pointer :pointer :int] :bool)

(ffi/defcfn put-audio-stream-data-no-copy
  "bool SDL_PutAudioStreamDataNoCopy(SDL_AudioStream * stream, const void * buf, int len, SDL_AudioStreamDataCompleteCallback callback, void * userdata)"
  {:arglists '([stream buf len callback userdata]) :sdl/c "SDL_PutAudioStreamDataNoCopy" :sdl/args [:pointer :pointer :int :pointer :pointer] :sdl/ret :bool}
  "SDL_PutAudioStreamDataNoCopy" [:pointer :pointer :int :pointer :pointer] :bool)

(ffi/defcfn put-audio-stream-planar-data
  "bool SDL_PutAudioStreamPlanarData(SDL_AudioStream * stream, const void * const * channel_buffers, int num_channels, int num_samples)"
  {:arglists '([stream channel-buffers num-channels num-samples]) :sdl/c "SDL_PutAudioStreamPlanarData" :sdl/args [:pointer :pointer :int :int] :sdl/ret :bool}
  "SDL_PutAudioStreamPlanarData" [:pointer :pointer :int :int] :bool)

(ffi/defcfn get-audio-stream-data
  "int SDL_GetAudioStreamData(SDL_AudioStream * stream, void * buf, int len)"
  {:arglists '([stream buf len]) :sdl/c "SDL_GetAudioStreamData" :sdl/args [:pointer :pointer :int] :sdl/ret :int}
  "SDL_GetAudioStreamData" [:pointer :pointer :int] :int)

(ffi/defcfn get-audio-stream-available
  "int SDL_GetAudioStreamAvailable(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamAvailable" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetAudioStreamAvailable" [:pointer] :int)

(ffi/defcfn get-audio-stream-queued
  "int SDL_GetAudioStreamQueued(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_GetAudioStreamQueued" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetAudioStreamQueued" [:pointer] :int)

(ffi/defcfn flush-audio-stream
  "bool SDL_FlushAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_FlushAudioStream" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_FlushAudioStream" [:pointer] :bool)

(ffi/defcfn clear-audio-stream
  "bool SDL_ClearAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_ClearAudioStream" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ClearAudioStream" [:pointer] :bool)

(ffi/defcfn pause-audio-stream-device
  "bool SDL_PauseAudioStreamDevice(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_PauseAudioStreamDevice" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_PauseAudioStreamDevice" [:pointer] :bool)

(ffi/defcfn resume-audio-stream-device
  "bool SDL_ResumeAudioStreamDevice(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_ResumeAudioStreamDevice" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ResumeAudioStreamDevice" [:pointer] :bool)

(ffi/defcfn audio-stream-device-paused
  "bool SDL_AudioStreamDevicePaused(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_AudioStreamDevicePaused" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_AudioStreamDevicePaused" [:pointer] :bool)

(ffi/defcfn lock-audio-stream
  "bool SDL_LockAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_LockAudioStream" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_LockAudioStream" [:pointer] :bool)

(ffi/defcfn unlock-audio-stream
  "bool SDL_UnlockAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_UnlockAudioStream" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_UnlockAudioStream" [:pointer] :bool)

(ffi/defcfn set-audio-stream-get-callback
  "bool SDL_SetAudioStreamGetCallback(SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata)"
  {:arglists '([stream callback userdata]) :sdl/c "SDL_SetAudioStreamGetCallback" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_SetAudioStreamGetCallback" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-audio-stream-put-callback
  "bool SDL_SetAudioStreamPutCallback(SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata)"
  {:arglists '([stream callback userdata]) :sdl/c "SDL_SetAudioStreamPutCallback" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_SetAudioStreamPutCallback" [:pointer :pointer :pointer] :bool)

(ffi/defcfn destroy-audio-stream
  "void SDL_DestroyAudioStream(SDL_AudioStream * stream)"
  {:arglists '([stream]) :sdl/c "SDL_DestroyAudioStream" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyAudioStream" [:pointer] :void)

(ffi/defcfn open-audio-device-stream
  "SDL_AudioStream * SDL_OpenAudioDeviceStream(SDL_AudioDeviceID devid, const SDL_AudioSpec * spec, SDL_AudioStreamCallback callback, void * userdata)"
  {:arglists '([devid spec callback userdata]) :sdl/c "SDL_OpenAudioDeviceStream" :sdl/args [:uint32 :pointer :pointer :pointer] :sdl/ret :pointer}
  "SDL_OpenAudioDeviceStream" [:uint32 :pointer :pointer :pointer] :pointer)

(ffi/defcfn set-audio-postmix-callback
  "bool SDL_SetAudioPostmixCallback(SDL_AudioDeviceID devid, SDL_AudioPostmixCallback callback, void * userdata)"
  {:arglists '([devid callback userdata]) :sdl/c "SDL_SetAudioPostmixCallback" :sdl/args [:uint32 :pointer :pointer] :sdl/ret :bool}
  "SDL_SetAudioPostmixCallback" [:uint32 :pointer :pointer] :bool)

(ffi/defcfn load-wav-io
  "bool SDL_LoadWAV_IO(SDL_IOStream * src, bool closeio, SDL_AudioSpec * spec, Uint8 ** audio_buf, Uint32 * audio_len)"
  {:arglists '([src closeio spec audio-buf audio-len]) :sdl/c "SDL_LoadWAV_IO" :sdl/args [:pointer :bool :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_LoadWAV_IO" [:pointer :bool :pointer :pointer :pointer] :bool)

(ffi/defcfn load-wav
  "bool SDL_LoadWAV(const char * path, SDL_AudioSpec * spec, Uint8 ** audio_buf, Uint32 * audio_len)"
  {:arglists '([path spec audio-buf audio-len]) :sdl/c "SDL_LoadWAV" :sdl/args [:string :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_LoadWAV" [:string :pointer :pointer :pointer] :bool)

(ffi/defcfn mix-audio
  "bool SDL_MixAudio(Uint8 * dst, const Uint8 * src, SDL_AudioFormat format, Uint32 len, float volume)"
  {:arglists '([dst src format len volume]) :sdl/c "SDL_MixAudio" :sdl/args [:pointer :pointer :int :uint32 :float] :sdl/ret :bool}
  "SDL_MixAudio" [:pointer :pointer :int :uint32 :float] :bool)

(ffi/defcfn convert-audio-samples
  "bool SDL_ConvertAudioSamples(const SDL_AudioSpec * src_spec, const Uint8 * src_data, int src_len, const SDL_AudioSpec * dst_spec, Uint8 ** dst_data, int * dst_len)"
  {:arglists '([src-spec src-data src-len dst-spec dst-data dst-len]) :sdl/c "SDL_ConvertAudioSamples" :sdl/args [:pointer :pointer :int :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_ConvertAudioSamples" [:pointer :pointer :int :pointer :pointer :pointer] :bool)

(ffi/defcfn get-audio-format-name
  "const char * SDL_GetAudioFormatName(SDL_AudioFormat format)"
  {:arglists '([format]) :sdl/c "SDL_GetAudioFormatName" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetAudioFormatName" [:int] :string)

(ffi/defcfn get-silence-value-for-format
  "int SDL_GetSilenceValueForFormat(SDL_AudioFormat format)"
  {:arglists '([format]) :sdl/c "SDL_GetSilenceValueForFormat" :sdl/args [:int] :sdl/ret :int}
  "SDL_GetSilenceValueForFormat" [:int] :int)
