;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.clipboard
  "Raw bindings for SDL_clipboard.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn set-clipboard-text
  "bool SDL_SetClipboardText(const char * text)"
  {:arglists '([text]) :sdl/c "SDL_SetClipboardText" :sdl/args [:string] :sdl/ret :bool}
  "SDL_SetClipboardText" [:string] :bool)

(ffi/defcfn get-clipboard-text
  "char * SDL_GetClipboardText(void)"
  {:arglists '([]) :sdl/c "SDL_GetClipboardText" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetClipboardText" [] :pointer)

(ffi/defcfn has-clipboard-text
  "bool SDL_HasClipboardText(void)"
  {:arglists '([]) :sdl/c "SDL_HasClipboardText" :sdl/args [] :sdl/ret :bool}
  "SDL_HasClipboardText" [] :bool)

(ffi/defcfn set-primary-selection-text
  "bool SDL_SetPrimarySelectionText(const char * text)"
  {:arglists '([text]) :sdl/c "SDL_SetPrimarySelectionText" :sdl/args [:string] :sdl/ret :bool}
  "SDL_SetPrimarySelectionText" [:string] :bool)

(ffi/defcfn get-primary-selection-text
  "char * SDL_GetPrimarySelectionText(void)"
  {:arglists '([]) :sdl/c "SDL_GetPrimarySelectionText" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetPrimarySelectionText" [] :pointer)

(ffi/defcfn has-primary-selection-text
  "bool SDL_HasPrimarySelectionText(void)"
  {:arglists '([]) :sdl/c "SDL_HasPrimarySelectionText" :sdl/args [] :sdl/ret :bool}
  "SDL_HasPrimarySelectionText" [] :bool)

(ffi/defcfn set-clipboard-data
  "bool SDL_SetClipboardData(SDL_ClipboardDataCallback callback, SDL_ClipboardCleanupCallback cleanup, void * userdata, const char *const * mime_types, size_t num_mime_types)"
  {:arglists '([callback cleanup userdata mime-types num-mime-types]) :sdl/c "SDL_SetClipboardData" :sdl/args [:pointer :pointer :pointer :pointer :size_t] :sdl/ret :bool}
  "SDL_SetClipboardData" [:pointer :pointer :pointer :pointer :size_t] :bool)

(ffi/defcfn clear-clipboard-data
  "bool SDL_ClearClipboardData(void)"
  {:arglists '([]) :sdl/c "SDL_ClearClipboardData" :sdl/args [] :sdl/ret :bool}
  "SDL_ClearClipboardData" [] :bool)

(ffi/defcfn get-clipboard-data
  "void * SDL_GetClipboardData(const char * mime_type, size_t * size)"
  {:arglists '([mime-type size]) :sdl/c "SDL_GetClipboardData" :sdl/args [:string :pointer] :sdl/ret :pointer}
  "SDL_GetClipboardData" [:string :pointer] :pointer)

(ffi/defcfn has-clipboard-data
  "bool SDL_HasClipboardData(const char * mime_type)"
  {:arglists '([mime-type]) :sdl/c "SDL_HasClipboardData" :sdl/args [:string] :sdl/ret :bool}
  "SDL_HasClipboardData" [:string] :bool)

(ffi/defcfn get-clipboard-mime-types
  "char ** SDL_GetClipboardMimeTypes(size_t * num_mime_types)"
  {:arglists '([num-mime-types]) :sdl/c "SDL_GetClipboardMimeTypes" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetClipboardMimeTypes" [:pointer] :pointer)
