;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.cpuinfo
  "Raw bindings for SDL_cpuinfo.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-num-logical-cpu-cores
  "int SDL_GetNumLogicalCPUCores(void)"
  {:arglists '([]) :sdl/c "SDL_GetNumLogicalCPUCores" :sdl/args [] :sdl/ret :int}
  "SDL_GetNumLogicalCPUCores" [] :int)

(ffi/defcfn get-cpu-cache-line-size
  "int SDL_GetCPUCacheLineSize(void)"
  {:arglists '([]) :sdl/c "SDL_GetCPUCacheLineSize" :sdl/args [] :sdl/ret :int}
  "SDL_GetCPUCacheLineSize" [] :int)

(ffi/defcfn has-alti-vec
  "bool SDL_HasAltiVec(void)"
  {:arglists '([]) :sdl/c "SDL_HasAltiVec" :sdl/args [] :sdl/ret :bool}
  "SDL_HasAltiVec" [] :bool)

(ffi/defcfn has-mmx
  "bool SDL_HasMMX(void)"
  {:arglists '([]) :sdl/c "SDL_HasMMX" :sdl/args [] :sdl/ret :bool}
  "SDL_HasMMX" [] :bool)

(ffi/defcfn has-sse
  "bool SDL_HasSSE(void)"
  {:arglists '([]) :sdl/c "SDL_HasSSE" :sdl/args [] :sdl/ret :bool}
  "SDL_HasSSE" [] :bool)

(ffi/defcfn has-sse2
  "bool SDL_HasSSE2(void)"
  {:arglists '([]) :sdl/c "SDL_HasSSE2" :sdl/args [] :sdl/ret :bool}
  "SDL_HasSSE2" [] :bool)

(ffi/defcfn has-sse3
  "bool SDL_HasSSE3(void)"
  {:arglists '([]) :sdl/c "SDL_HasSSE3" :sdl/args [] :sdl/ret :bool}
  "SDL_HasSSE3" [] :bool)

(ffi/defcfn has-sse41
  "bool SDL_HasSSE41(void)"
  {:arglists '([]) :sdl/c "SDL_HasSSE41" :sdl/args [] :sdl/ret :bool}
  "SDL_HasSSE41" [] :bool)

(ffi/defcfn has-sse42
  "bool SDL_HasSSE42(void)"
  {:arglists '([]) :sdl/c "SDL_HasSSE42" :sdl/args [] :sdl/ret :bool}
  "SDL_HasSSE42" [] :bool)

(ffi/defcfn has-avx
  "bool SDL_HasAVX(void)"
  {:arglists '([]) :sdl/c "SDL_HasAVX" :sdl/args [] :sdl/ret :bool}
  "SDL_HasAVX" [] :bool)

(ffi/defcfn has-avx2
  "bool SDL_HasAVX2(void)"
  {:arglists '([]) :sdl/c "SDL_HasAVX2" :sdl/args [] :sdl/ret :bool}
  "SDL_HasAVX2" [] :bool)

(ffi/defcfn has-avx512f
  "bool SDL_HasAVX512F(void)"
  {:arglists '([]) :sdl/c "SDL_HasAVX512F" :sdl/args [] :sdl/ret :bool}
  "SDL_HasAVX512F" [] :bool)

(ffi/defcfn has-armsimd
  "bool SDL_HasARMSIMD(void)"
  {:arglists '([]) :sdl/c "SDL_HasARMSIMD" :sdl/args [] :sdl/ret :bool}
  "SDL_HasARMSIMD" [] :bool)

(ffi/defcfn has-neon
  "bool SDL_HasNEON(void)"
  {:arglists '([]) :sdl/c "SDL_HasNEON" :sdl/args [] :sdl/ret :bool}
  "SDL_HasNEON" [] :bool)

(ffi/defcfn has-lsx
  "bool SDL_HasLSX(void)"
  {:arglists '([]) :sdl/c "SDL_HasLSX" :sdl/args [] :sdl/ret :bool}
  "SDL_HasLSX" [] :bool)

(ffi/defcfn has-lasx
  "bool SDL_HasLASX(void)"
  {:arglists '([]) :sdl/c "SDL_HasLASX" :sdl/args [] :sdl/ret :bool}
  "SDL_HasLASX" [] :bool)

(ffi/defcfn get-system-ram
  "int SDL_GetSystemRAM(void)"
  {:arglists '([]) :sdl/c "SDL_GetSystemRAM" :sdl/args [] :sdl/ret :int}
  "SDL_GetSystemRAM" [] :int)

(ffi/defcfn get-simd-alignment
  "size_t SDL_GetSIMDAlignment(void)"
  {:arglists '([]) :sdl/c "SDL_GetSIMDAlignment" :sdl/args [] :sdl/ret :size_t}
  "SDL_GetSIMDAlignment" [] :size_t)

(ffi/defcfn get-system-page-size
  "int SDL_GetSystemPageSize(void)"
  {:arglists '([]) :sdl/c "SDL_GetSystemPageSize" :sdl/args [] :sdl/ret :int}
  "SDL_GetSystemPageSize" [] :int)
