;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.error
  "Raw bindings for SDL_error.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn set-error
  "bool SDL_SetError(const char * fmt, ...)"
  {:arglists '([fmt & varargs]) :sdl/c "SDL_SetError" :sdl/args [:string :&] :sdl/ret :bool}
  "SDL_SetError" [:string :&] :bool)

(ffi/defcfn out-of-memory
  "bool SDL_OutOfMemory(void)"
  {:arglists '([]) :sdl/c "SDL_OutOfMemory" :sdl/args [] :sdl/ret :bool}
  "SDL_OutOfMemory" [] :bool)

(ffi/defcfn get-error
  "const char * SDL_GetError(void)"
  {:arglists '([]) :sdl/c "SDL_GetError" :sdl/args [] :sdl/ret :string}
  "SDL_GetError" [] :string)

(ffi/defcfn clear-error
  "bool SDL_ClearError(void)"
  {:arglists '([]) :sdl/c "SDL_ClearError" :sdl/args [] :sdl/ret :bool}
  "SDL_ClearError" [] :bool)
