;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.filesystem
  "Raw bindings for SDL_filesystem.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def path-info
  "ffi/layout of SDL_PathInfo."
  (ffi/layout [:struct [[:type :int] [:size :uint64] [:create-time :int64] [:modify-time :int64] [:access-time :int64]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-base-path
  "const char * SDL_GetBasePath(void)"
  {:arglists '([]) :sdl/c "SDL_GetBasePath" :sdl/args [] :sdl/ret :string}
  "SDL_GetBasePath" [] :string)

(ffi/defcfn get-pref-path
  "char * SDL_GetPrefPath(const char * org, const char * app)"
  {:arglists '([org app]) :sdl/c "SDL_GetPrefPath" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_GetPrefPath" [:string :string] :pointer)

(ffi/defcfn get-user-folder
  "const char * SDL_GetUserFolder(SDL_Folder folder)"
  {:arglists '([folder]) :sdl/c "SDL_GetUserFolder" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetUserFolder" [:int] :string)

(ffi/defcfn create-directory
  "bool SDL_CreateDirectory(const char * path)"
  {:arglists '([path]) :sdl/c "SDL_CreateDirectory" :sdl/args [:string] :sdl/ret :bool}
  "SDL_CreateDirectory" [:string] :bool)

(ffi/defcfn enumerate-directory
  "bool SDL_EnumerateDirectory(const char * path, SDL_EnumerateDirectoryCallback callback, void * userdata)"
  {:arglists '([path callback userdata]) :sdl/c "SDL_EnumerateDirectory" :sdl/args [:string :pointer :pointer] :sdl/ret :bool}
  "SDL_EnumerateDirectory" [:string :pointer :pointer] :bool)

(ffi/defcfn remove-path
  "bool SDL_RemovePath(const char * path)"
  {:arglists '([path]) :sdl/c "SDL_RemovePath" :sdl/args [:string] :sdl/ret :bool}
  "SDL_RemovePath" [:string] :bool)

(ffi/defcfn rename-path
  "bool SDL_RenamePath(const char * oldpath, const char * newpath)"
  {:arglists '([oldpath newpath]) :sdl/c "SDL_RenamePath" :sdl/args [:string :string] :sdl/ret :bool}
  "SDL_RenamePath" [:string :string] :bool)

(ffi/defcfn copy-file
  "bool SDL_CopyFile(const char * oldpath, const char * newpath)"
  {:arglists '([oldpath newpath]) :sdl/c "SDL_CopyFile" :sdl/args [:string :string] :sdl/ret :bool}
  "SDL_CopyFile" [:string :string] :bool)

(ffi/defcfn get-path-info
  "bool SDL_GetPathInfo(const char * path, SDL_PathInfo * info)"
  {:arglists '([path info]) :sdl/c "SDL_GetPathInfo" :sdl/args [:string :pointer] :sdl/ret :bool}
  "SDL_GetPathInfo" [:string :pointer] :bool)

(ffi/defcfn glob-directory
  "char ** SDL_GlobDirectory(const char * path, const char * pattern, SDL_GlobFlags flags, int * count)"
  {:arglists '([path pattern flags count]) :sdl/c "SDL_GlobDirectory" :sdl/args [:string :string :uint32 :pointer] :sdl/ret :pointer}
  "SDL_GlobDirectory" [:string :string :uint32 :pointer] :pointer)

(ffi/defcfn get-current-directory
  "char * SDL_GetCurrentDirectory(void)"
  {:arglists '([]) :sdl/c "SDL_GetCurrentDirectory" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetCurrentDirectory" [] :pointer)
