;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.gamepad
  "Raw bindings for SDL_gamepad.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn add-gamepad-mapping
  "int SDL_AddGamepadMapping(const char * mapping)"
  {:arglists '([mapping]) :sdl/c "SDL_AddGamepadMapping" :sdl/args [:string] :sdl/ret :int}
  "SDL_AddGamepadMapping" [:string] :int)

(ffi/defcfn add-gamepad-mappings-from-io
  "int SDL_AddGamepadMappingsFromIO(SDL_IOStream * src, bool closeio)"
  {:arglists '([src closeio]) :sdl/c "SDL_AddGamepadMappingsFromIO" :sdl/args [:pointer :bool] :sdl/ret :int}
  "SDL_AddGamepadMappingsFromIO" [:pointer :bool] :int)

(ffi/defcfn add-gamepad-mappings-from-file
  "int SDL_AddGamepadMappingsFromFile(const char * file)"
  {:arglists '([file]) :sdl/c "SDL_AddGamepadMappingsFromFile" :sdl/args [:string] :sdl/ret :int}
  "SDL_AddGamepadMappingsFromFile" [:string] :int)

(ffi/defcfn reload-gamepad-mappings
  "bool SDL_ReloadGamepadMappings(void)"
  {:arglists '([]) :sdl/c "SDL_ReloadGamepadMappings" :sdl/args [] :sdl/ret :bool}
  "SDL_ReloadGamepadMappings" [] :bool)

(ffi/defcfn get-gamepad-mappings
  "char ** SDL_GetGamepadMappings(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetGamepadMappings" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetGamepadMappings" [:pointer] :pointer)

(ffi/defcfn get-gamepad-mapping-for-guid
  "char * SDL_GetGamepadMappingForGUID(SDL_GUID guid)"
  {:arglists '([guid]) :sdl/c "SDL_GetGamepadMappingForGUID" :sdl/args [[:by-value [:struct [[:data [:array :uint8 16]]]]]] :sdl/ret :pointer}
  "SDL_GetGamepadMappingForGUID" [[:by-value [:struct [[:data [:array :uint8 16]]]]]] :pointer)

(ffi/defcfn get-gamepad-mapping
  "char * SDL_GetGamepadMapping(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadMapping" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetGamepadMapping" [:pointer] :pointer)

(ffi/defcfn set-gamepad-mapping
  "bool SDL_SetGamepadMapping(SDL_JoystickID instance_id, const char * mapping)"
  {:arglists '([instance-id mapping]) :sdl/c "SDL_SetGamepadMapping" :sdl/args [:uint32 :string] :sdl/ret :bool}
  "SDL_SetGamepadMapping" [:uint32 :string] :bool)

(ffi/defcfn has-gamepad
  "bool SDL_HasGamepad(void)"
  {:arglists '([]) :sdl/c "SDL_HasGamepad" :sdl/args [] :sdl/ret :bool}
  "SDL_HasGamepad" [] :bool)

(ffi/defcfn get-gamepads
  "SDL_JoystickID * SDL_GetGamepads(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetGamepads" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetGamepads" [:pointer] :pointer)

(ffi/defcfn is-gamepad
  "bool SDL_IsGamepad(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_IsGamepad" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_IsGamepad" [:uint32] :bool)

(ffi/defcfn get-gamepad-name-for-id
  "const char * SDL_GetGamepadNameForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadNameForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetGamepadNameForID" [:uint32] :string)

(ffi/defcfn get-gamepad-path-for-id
  "const char * SDL_GetGamepadPathForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadPathForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetGamepadPathForID" [:uint32] :string)

(ffi/defcfn get-gamepad-player-index-for-id
  "int SDL_GetGamepadPlayerIndexForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadPlayerIndexForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetGamepadPlayerIndexForID" [:uint32] :int)

(ffi/defcfn get-gamepad-guid-for-id
  "SDL_GUID SDL_GetGamepadGUIDForID(SDL_JoystickID instance_id)"
  {:arglists '([out instance-id]) :sdl/c "SDL_GetGamepadGUIDForID" :sdl/args [:uint32] :sdl/ret [:by-value [:struct [[:data [:array :uint8 16]]]]]}
  "SDL_GetGamepadGUIDForID" [:uint32] [:by-value [:struct [[:data [:array :uint8 16]]]]])

(ffi/defcfn get-gamepad-vendor-for-id
  "Uint16 SDL_GetGamepadVendorForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadVendorForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetGamepadVendorForID" [:uint32] :uint16)

(ffi/defcfn get-gamepad-product-for-id
  "Uint16 SDL_GetGamepadProductForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadProductForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetGamepadProductForID" [:uint32] :uint16)

(ffi/defcfn get-gamepad-product-version-for-id
  "Uint16 SDL_GetGamepadProductVersionForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadProductVersionForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetGamepadProductVersionForID" [:uint32] :uint16)

(ffi/defcfn get-gamepad-type-for-id
  "SDL_GamepadType SDL_GetGamepadTypeForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadTypeForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetGamepadTypeForID" [:uint32] :int)

(ffi/defcfn get-real-gamepad-type-for-id
  "SDL_GamepadType SDL_GetRealGamepadTypeForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetRealGamepadTypeForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetRealGamepadTypeForID" [:uint32] :int)

(ffi/defcfn get-gamepad-mapping-for-id
  "char * SDL_GetGamepadMappingForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadMappingForID" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_GetGamepadMappingForID" [:uint32] :pointer)

(ffi/defcfn open-gamepad
  "SDL_Gamepad * SDL_OpenGamepad(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_OpenGamepad" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_OpenGamepad" [:uint32] :pointer)

(ffi/defcfn get-gamepad-from-id
  "SDL_Gamepad * SDL_GetGamepadFromID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetGamepadFromID" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_GetGamepadFromID" [:uint32] :pointer)

(ffi/defcfn get-gamepad-from-player-index
  "SDL_Gamepad * SDL_GetGamepadFromPlayerIndex(int player_index)"
  {:arglists '([player-index]) :sdl/c "SDL_GetGamepadFromPlayerIndex" :sdl/args [:int] :sdl/ret :pointer}
  "SDL_GetGamepadFromPlayerIndex" [:int] :pointer)

(ffi/defcfn get-gamepad-properties
  "SDL_PropertiesID SDL_GetGamepadProperties(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetGamepadProperties" [:pointer] :uint32)

(ffi/defcfn get-gamepad-id
  "SDL_JoystickID SDL_GetGamepadID(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadID" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetGamepadID" [:pointer] :uint32)

(ffi/defcfn get-gamepad-name
  "const char * SDL_GetGamepadName(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetGamepadName" [:pointer] :string)

(ffi/defcfn get-gamepad-path
  "const char * SDL_GetGamepadPath(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadPath" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetGamepadPath" [:pointer] :string)

(ffi/defcfn get-gamepad-type
  "SDL_GamepadType SDL_GetGamepadType(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadType" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetGamepadType" [:pointer] :int)

(ffi/defcfn get-real-gamepad-type
  "SDL_GamepadType SDL_GetRealGamepadType(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetRealGamepadType" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetRealGamepadType" [:pointer] :int)

(ffi/defcfn get-gamepad-player-index
  "int SDL_GetGamepadPlayerIndex(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadPlayerIndex" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetGamepadPlayerIndex" [:pointer] :int)

(ffi/defcfn set-gamepad-player-index
  "bool SDL_SetGamepadPlayerIndex(SDL_Gamepad * gamepad, int player_index)"
  {:arglists '([gamepad player-index]) :sdl/c "SDL_SetGamepadPlayerIndex" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetGamepadPlayerIndex" [:pointer :int] :bool)

(ffi/defcfn get-gamepad-vendor
  "Uint16 SDL_GetGamepadVendor(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadVendor" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetGamepadVendor" [:pointer] :uint16)

(ffi/defcfn get-gamepad-product
  "Uint16 SDL_GetGamepadProduct(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadProduct" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetGamepadProduct" [:pointer] :uint16)

(ffi/defcfn get-gamepad-product-version
  "Uint16 SDL_GetGamepadProductVersion(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadProductVersion" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetGamepadProductVersion" [:pointer] :uint16)

(ffi/defcfn get-gamepad-firmware-version
  "Uint16 SDL_GetGamepadFirmwareVersion(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadFirmwareVersion" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetGamepadFirmwareVersion" [:pointer] :uint16)

(ffi/defcfn get-gamepad-serial
  "const char * SDL_GetGamepadSerial(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadSerial" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetGamepadSerial" [:pointer] :string)

(ffi/defcfn get-gamepad-steam-handle
  "Uint64 SDL_GetGamepadSteamHandle(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadSteamHandle" :sdl/args [:pointer] :sdl/ret :uint64}
  "SDL_GetGamepadSteamHandle" [:pointer] :uint64)

(ffi/defcfn get-gamepad-connection-state
  "SDL_JoystickConnectionState SDL_GetGamepadConnectionState(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadConnectionState" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetGamepadConnectionState" [:pointer] :int)

(ffi/defcfn get-gamepad-power-info
  "SDL_PowerState SDL_GetGamepadPowerInfo(SDL_Gamepad * gamepad, int * percent)"
  {:arglists '([gamepad percent]) :sdl/c "SDL_GetGamepadPowerInfo" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "SDL_GetGamepadPowerInfo" [:pointer :pointer] :int)

(ffi/defcfn gamepad-connected
  "bool SDL_GamepadConnected(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GamepadConnected" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GamepadConnected" [:pointer] :bool)

(ffi/defcfn get-gamepad-joystick
  "SDL_Joystick * SDL_GetGamepadJoystick(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetGamepadJoystick" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetGamepadJoystick" [:pointer] :pointer)

(ffi/defcfn set-gamepad-events-enabled
  "void SDL_SetGamepadEventsEnabled(bool enabled)"
  {:arglists '([enabled]) :sdl/c "SDL_SetGamepadEventsEnabled" :sdl/args [:bool] :sdl/ret :void}
  "SDL_SetGamepadEventsEnabled" [:bool] :void)

(ffi/defcfn gamepad-events-enabled
  "bool SDL_GamepadEventsEnabled(void)"
  {:arglists '([]) :sdl/c "SDL_GamepadEventsEnabled" :sdl/args [] :sdl/ret :bool}
  "SDL_GamepadEventsEnabled" [] :bool)

(ffi/defcfn get-gamepad-bindings
  "SDL_GamepadBinding ** SDL_GetGamepadBindings(SDL_Gamepad * gamepad, int * count)"
  {:arglists '([gamepad count]) :sdl/c "SDL_GetGamepadBindings" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_GetGamepadBindings" [:pointer :pointer] :pointer)

(ffi/defcfn update-gamepads
  "void SDL_UpdateGamepads(void)"
  {:arglists '([]) :sdl/c "SDL_UpdateGamepads" :sdl/args [] :sdl/ret :void}
  "SDL_UpdateGamepads" [] :void)

(ffi/defcfn get-gamepad-type-from-string
  "SDL_GamepadType SDL_GetGamepadTypeFromString(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_GetGamepadTypeFromString" :sdl/args [:string] :sdl/ret :int}
  "SDL_GetGamepadTypeFromString" [:string] :int)

(ffi/defcfn get-gamepad-string-for-type
  "const char * SDL_GetGamepadStringForType(SDL_GamepadType type)"
  {:arglists '([type]) :sdl/c "SDL_GetGamepadStringForType" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetGamepadStringForType" [:int] :string)

(ffi/defcfn get-gamepad-axis-from-string
  "SDL_GamepadAxis SDL_GetGamepadAxisFromString(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_GetGamepadAxisFromString" :sdl/args [:string] :sdl/ret :int}
  "SDL_GetGamepadAxisFromString" [:string] :int)

(ffi/defcfn get-gamepad-string-for-axis
  "const char * SDL_GetGamepadStringForAxis(SDL_GamepadAxis axis)"
  {:arglists '([axis]) :sdl/c "SDL_GetGamepadStringForAxis" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetGamepadStringForAxis" [:int] :string)

(ffi/defcfn gamepad-has-axis
  "bool SDL_GamepadHasAxis(SDL_Gamepad * gamepad, SDL_GamepadAxis axis)"
  {:arglists '([gamepad axis]) :sdl/c "SDL_GamepadHasAxis" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GamepadHasAxis" [:pointer :int] :bool)

(ffi/defcfn get-gamepad-axis
  "Sint16 SDL_GetGamepadAxis(SDL_Gamepad * gamepad, SDL_GamepadAxis axis)"
  {:arglists '([gamepad axis]) :sdl/c "SDL_GetGamepadAxis" :sdl/args [:pointer :int] :sdl/ret :int16}
  "SDL_GetGamepadAxis" [:pointer :int] :int16)

(ffi/defcfn get-gamepad-button-from-string
  "SDL_GamepadButton SDL_GetGamepadButtonFromString(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_GetGamepadButtonFromString" :sdl/args [:string] :sdl/ret :int}
  "SDL_GetGamepadButtonFromString" [:string] :int)

(ffi/defcfn get-gamepad-string-for-button
  "const char * SDL_GetGamepadStringForButton(SDL_GamepadButton button)"
  {:arglists '([button]) :sdl/c "SDL_GetGamepadStringForButton" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetGamepadStringForButton" [:int] :string)

(ffi/defcfn gamepad-has-button
  "bool SDL_GamepadHasButton(SDL_Gamepad * gamepad, SDL_GamepadButton button)"
  {:arglists '([gamepad button]) :sdl/c "SDL_GamepadHasButton" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GamepadHasButton" [:pointer :int] :bool)

(ffi/defcfn get-gamepad-button
  "bool SDL_GetGamepadButton(SDL_Gamepad * gamepad, SDL_GamepadButton button)"
  {:arglists '([gamepad button]) :sdl/c "SDL_GetGamepadButton" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GetGamepadButton" [:pointer :int] :bool)

(ffi/defcfn get-gamepad-button-label-for-type
  "SDL_GamepadButtonLabel SDL_GetGamepadButtonLabelForType(SDL_GamepadType type, SDL_GamepadButton button)"
  {:arglists '([type button]) :sdl/c "SDL_GetGamepadButtonLabelForType" :sdl/args [:int :int] :sdl/ret :int}
  "SDL_GetGamepadButtonLabelForType" [:int :int] :int)

(ffi/defcfn get-gamepad-button-label
  "SDL_GamepadButtonLabel SDL_GetGamepadButtonLabel(SDL_Gamepad * gamepad, SDL_GamepadButton button)"
  {:arglists '([gamepad button]) :sdl/c "SDL_GetGamepadButtonLabel" :sdl/args [:pointer :int] :sdl/ret :int}
  "SDL_GetGamepadButtonLabel" [:pointer :int] :int)

(ffi/defcfn get-num-gamepad-touchpads
  "int SDL_GetNumGamepadTouchpads(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_GetNumGamepadTouchpads" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumGamepadTouchpads" [:pointer] :int)

(ffi/defcfn get-num-gamepad-touchpad-fingers
  "int SDL_GetNumGamepadTouchpadFingers(SDL_Gamepad * gamepad, int touchpad)"
  {:arglists '([gamepad touchpad]) :sdl/c "SDL_GetNumGamepadTouchpadFingers" :sdl/args [:pointer :int] :sdl/ret :int}
  "SDL_GetNumGamepadTouchpadFingers" [:pointer :int] :int)

(ffi/defcfn get-gamepad-touchpad-finger
  "bool SDL_GetGamepadTouchpadFinger(SDL_Gamepad * gamepad, int touchpad, int finger, bool * down, float * x, float * y, float * pressure)"
  {:arglists '([gamepad touchpad finger down x y pressure]) :sdl/c "SDL_GetGamepadTouchpadFinger" :sdl/args [:pointer :int :int :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetGamepadTouchpadFinger" [:pointer :int :int :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn gamepad-has-sensor
  "bool SDL_GamepadHasSensor(SDL_Gamepad * gamepad, SDL_SensorType type)"
  {:arglists '([gamepad type]) :sdl/c "SDL_GamepadHasSensor" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GamepadHasSensor" [:pointer :int] :bool)

(ffi/defcfn set-gamepad-sensor-enabled
  "bool SDL_SetGamepadSensorEnabled(SDL_Gamepad * gamepad, SDL_SensorType type, bool enabled)"
  {:arglists '([gamepad type enabled]) :sdl/c "SDL_SetGamepadSensorEnabled" :sdl/args [:pointer :int :bool] :sdl/ret :bool}
  "SDL_SetGamepadSensorEnabled" [:pointer :int :bool] :bool)

(ffi/defcfn gamepad-sensor-enabled
  "bool SDL_GamepadSensorEnabled(SDL_Gamepad * gamepad, SDL_SensorType type)"
  {:arglists '([gamepad type]) :sdl/c "SDL_GamepadSensorEnabled" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GamepadSensorEnabled" [:pointer :int] :bool)

(ffi/defcfn get-gamepad-sensor-data-rate
  "float SDL_GetGamepadSensorDataRate(SDL_Gamepad * gamepad, SDL_SensorType type)"
  {:arglists '([gamepad type]) :sdl/c "SDL_GetGamepadSensorDataRate" :sdl/args [:pointer :int] :sdl/ret :float}
  "SDL_GetGamepadSensorDataRate" [:pointer :int] :float)

(ffi/defcfn get-gamepad-sensor-data
  "bool SDL_GetGamepadSensorData(SDL_Gamepad * gamepad, SDL_SensorType type, float * data, int num_values)"
  {:arglists '([gamepad type data num-values]) :sdl/c "SDL_GetGamepadSensorData" :sdl/args [:pointer :int :pointer :int] :sdl/ret :bool}
  "SDL_GetGamepadSensorData" [:pointer :int :pointer :int] :bool)

(ffi/defcfn rumble-gamepad
  "bool SDL_RumbleGamepad(SDL_Gamepad * gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)"
  {:arglists '([gamepad low-frequency-rumble high-frequency-rumble duration-ms]) :sdl/c "SDL_RumbleGamepad" :sdl/args [:pointer :uint16 :uint16 :uint32] :sdl/ret :bool}
  "SDL_RumbleGamepad" [:pointer :uint16 :uint16 :uint32] :bool)

(ffi/defcfn rumble-gamepad-triggers
  "bool SDL_RumbleGamepadTriggers(SDL_Gamepad * gamepad, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)"
  {:arglists '([gamepad left-rumble right-rumble duration-ms]) :sdl/c "SDL_RumbleGamepadTriggers" :sdl/args [:pointer :uint16 :uint16 :uint32] :sdl/ret :bool}
  "SDL_RumbleGamepadTriggers" [:pointer :uint16 :uint16 :uint32] :bool)

(ffi/defcfn set-gamepad-led
  "bool SDL_SetGamepadLED(SDL_Gamepad * gamepad, Uint8 red, Uint8 green, Uint8 blue)"
  {:arglists '([gamepad red green blue]) :sdl/c "SDL_SetGamepadLED" :sdl/args [:pointer :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_SetGamepadLED" [:pointer :uint8 :uint8 :uint8] :bool)

(ffi/defcfn send-gamepad-effect
  "bool SDL_SendGamepadEffect(SDL_Gamepad * gamepad, const void * data, int size)"
  {:arglists '([gamepad data size]) :sdl/c "SDL_SendGamepadEffect" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_SendGamepadEffect" [:pointer :pointer :int] :bool)

(ffi/defcfn close-gamepad
  "void SDL_CloseGamepad(SDL_Gamepad * gamepad)"
  {:arglists '([gamepad]) :sdl/c "SDL_CloseGamepad" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_CloseGamepad" [:pointer] :void)

(ffi/defcfn get-gamepad-apple-sf-symbols-name-for-button
  "const char * SDL_GetGamepadAppleSFSymbolsNameForButton(SDL_Gamepad * gamepad, SDL_GamepadButton button)"
  {:arglists '([gamepad button]) :sdl/c "SDL_GetGamepadAppleSFSymbolsNameForButton" :sdl/args [:pointer :int] :sdl/ret :string}
  "SDL_GetGamepadAppleSFSymbolsNameForButton" [:pointer :int] :string)

(ffi/defcfn get-gamepad-apple-sf-symbols-name-for-axis
  "const char * SDL_GetGamepadAppleSFSymbolsNameForAxis(SDL_Gamepad * gamepad, SDL_GamepadAxis axis)"
  {:arglists '([gamepad axis]) :sdl/c "SDL_GetGamepadAppleSFSymbolsNameForAxis" :sdl/args [:pointer :int] :sdl/ret :string}
  "SDL_GetGamepadAppleSFSymbolsNameForAxis" [:pointer :int] :string)
