;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.haptic
  "Raw bindings for SDL_haptic.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def haptic-direction
  "ffi/layout of SDL_HapticDirection."
  (ffi/layout [:struct [[:type :uint8] [:dir [:array :int32 3]]]]))

(def haptic-constant
  "ffi/layout of SDL_HapticConstant."
  (ffi/layout [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:level :int16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]))

(def haptic-periodic
  "ffi/layout of SDL_HapticPeriodic."
  (ffi/layout [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:period :uint16] [:magnitude :int16] [:offset :int16] [:phase :uint16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]))

(def haptic-condition
  "ffi/layout of SDL_HapticCondition."
  (ffi/layout [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:right-sat [:array :uint16 3]] [:left-sat [:array :uint16 3]] [:right-coeff [:array :int16 3]] [:left-coeff [:array :int16 3]] [:deadband [:array :uint16 3]] [:center [:array :int16 3]]]]))

(def haptic-ramp
  "ffi/layout of SDL_HapticRamp."
  (ffi/layout [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:start :int16] [:end :int16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]))

(def haptic-left-right
  "ffi/layout of SDL_HapticLeftRight."
  (ffi/layout [:struct [[:type :uint16] [:length :uint32] [:large-magnitude :uint16] [:small-magnitude :uint16]]]))

(def haptic-custom
  "ffi/layout of SDL_HapticCustom."
  (ffi/layout [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:channels :uint8] [:period :uint16] [:samples :uint16] [:data :pointer] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]))

(def haptic-effect
  "ffi/layout of SDL_HapticEffect."
  (ffi/layout [:union [[:type :uint16] [:constant [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:level :int16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]] [:periodic [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:period :uint16] [:magnitude :int16] [:offset :int16] [:phase :uint16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]] [:condition [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:right-sat [:array :uint16 3]] [:left-sat [:array :uint16 3]] [:right-coeff [:array :int16 3]] [:left-coeff [:array :int16 3]] [:deadband [:array :uint16 3]] [:center [:array :int16 3]]]]] [:ramp [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:start :int16] [:end :int16] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]] [:leftright [:struct [[:type :uint16] [:length :uint32] [:large-magnitude :uint16] [:small-magnitude :uint16]]]] [:custom [:struct [[:type :uint16] [:direction [:struct [[:type :uint8] [:dir [:array :int32 3]]]]] [:length :uint32] [:delay :uint16] [:button :uint16] [:interval :uint16] [:channels :uint8] [:period :uint16] [:samples :uint16] [:data :pointer] [:attack-length :uint16] [:attack-level :uint16] [:fade-length :uint16] [:fade-level :uint16]]]]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-haptics
  "SDL_HapticID * SDL_GetHaptics(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetHaptics" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetHaptics" [:pointer] :pointer)

(ffi/defcfn get-haptic-name-for-id
  "const char * SDL_GetHapticNameForID(SDL_HapticID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetHapticNameForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetHapticNameForID" [:uint32] :string)

(ffi/defcfn open-haptic
  "SDL_Haptic * SDL_OpenHaptic(SDL_HapticID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_OpenHaptic" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_OpenHaptic" [:uint32] :pointer)

(ffi/defcfn get-haptic-from-id
  "SDL_Haptic * SDL_GetHapticFromID(SDL_HapticID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetHapticFromID" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_GetHapticFromID" [:uint32] :pointer)

(ffi/defcfn get-haptic-id
  "SDL_HapticID SDL_GetHapticID(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetHapticID" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetHapticID" [:pointer] :uint32)

(ffi/defcfn get-haptic-name
  "const char * SDL_GetHapticName(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetHapticName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetHapticName" [:pointer] :string)

(ffi/defcfn is-mouse-haptic
  "bool SDL_IsMouseHaptic(void)"
  {:arglists '([]) :sdl/c "SDL_IsMouseHaptic" :sdl/args [] :sdl/ret :bool}
  "SDL_IsMouseHaptic" [] :bool)

(ffi/defcfn open-haptic-from-mouse
  "SDL_Haptic * SDL_OpenHapticFromMouse(void)"
  {:arglists '([]) :sdl/c "SDL_OpenHapticFromMouse" :sdl/args [] :sdl/ret :pointer}
  "SDL_OpenHapticFromMouse" [] :pointer)

(ffi/defcfn is-joystick-haptic
  "bool SDL_IsJoystickHaptic(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_IsJoystickHaptic" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_IsJoystickHaptic" [:pointer] :bool)

(ffi/defcfn open-haptic-from-joystick
  "SDL_Haptic * SDL_OpenHapticFromJoystick(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_OpenHapticFromJoystick" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_OpenHapticFromJoystick" [:pointer] :pointer)

(ffi/defcfn close-haptic
  "void SDL_CloseHaptic(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_CloseHaptic" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_CloseHaptic" [:pointer] :void)

(ffi/defcfn get-max-haptic-effects
  "int SDL_GetMaxHapticEffects(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetMaxHapticEffects" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetMaxHapticEffects" [:pointer] :int)

(ffi/defcfn get-max-haptic-effects-playing
  "int SDL_GetMaxHapticEffectsPlaying(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetMaxHapticEffectsPlaying" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetMaxHapticEffectsPlaying" [:pointer] :int)

(ffi/defcfn get-haptic-features
  "Uint32 SDL_GetHapticFeatures(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetHapticFeatures" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetHapticFeatures" [:pointer] :uint32)

(ffi/defcfn get-num-haptic-axes
  "int SDL_GetNumHapticAxes(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_GetNumHapticAxes" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumHapticAxes" [:pointer] :int)

(ffi/defcfn haptic-effect-supported
  "bool SDL_HapticEffectSupported(SDL_Haptic * haptic, const SDL_HapticEffect * effect)"
  {:arglists '([haptic effect]) :sdl/c "SDL_HapticEffectSupported" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_HapticEffectSupported" [:pointer :pointer] :bool)

(ffi/defcfn create-haptic-effect
  "SDL_HapticEffectID SDL_CreateHapticEffect(SDL_Haptic * haptic, const SDL_HapticEffect * effect)"
  {:arglists '([haptic effect]) :sdl/c "SDL_CreateHapticEffect" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "SDL_CreateHapticEffect" [:pointer :pointer] :int)

(ffi/defcfn update-haptic-effect
  "bool SDL_UpdateHapticEffect(SDL_Haptic * haptic, SDL_HapticEffectID effect, const SDL_HapticEffect * data)"
  {:arglists '([haptic effect data]) :sdl/c "SDL_UpdateHapticEffect" :sdl/args [:pointer :int :pointer] :sdl/ret :bool}
  "SDL_UpdateHapticEffect" [:pointer :int :pointer] :bool)

(ffi/defcfn run-haptic-effect
  "bool SDL_RunHapticEffect(SDL_Haptic * haptic, SDL_HapticEffectID effect, Uint32 iterations)"
  {:arglists '([haptic effect iterations]) :sdl/c "SDL_RunHapticEffect" :sdl/args [:pointer :int :uint32] :sdl/ret :bool}
  "SDL_RunHapticEffect" [:pointer :int :uint32] :bool)

(ffi/defcfn stop-haptic-effect
  "bool SDL_StopHapticEffect(SDL_Haptic * haptic, SDL_HapticEffectID effect)"
  {:arglists '([haptic effect]) :sdl/c "SDL_StopHapticEffect" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_StopHapticEffect" [:pointer :int] :bool)

(ffi/defcfn destroy-haptic-effect
  "void SDL_DestroyHapticEffect(SDL_Haptic * haptic, SDL_HapticEffectID effect)"
  {:arglists '([haptic effect]) :sdl/c "SDL_DestroyHapticEffect" :sdl/args [:pointer :int] :sdl/ret :void}
  "SDL_DestroyHapticEffect" [:pointer :int] :void)

(ffi/defcfn get-haptic-effect-status
  "bool SDL_GetHapticEffectStatus(SDL_Haptic * haptic, SDL_HapticEffectID effect)"
  {:arglists '([haptic effect]) :sdl/c "SDL_GetHapticEffectStatus" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GetHapticEffectStatus" [:pointer :int] :bool)

(ffi/defcfn set-haptic-gain
  "bool SDL_SetHapticGain(SDL_Haptic * haptic, int gain)"
  {:arglists '([haptic gain]) :sdl/c "SDL_SetHapticGain" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetHapticGain" [:pointer :int] :bool)

(ffi/defcfn set-haptic-autocenter
  "bool SDL_SetHapticAutocenter(SDL_Haptic * haptic, int autocenter)"
  {:arglists '([haptic autocenter]) :sdl/c "SDL_SetHapticAutocenter" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetHapticAutocenter" [:pointer :int] :bool)

(ffi/defcfn pause-haptic
  "bool SDL_PauseHaptic(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_PauseHaptic" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_PauseHaptic" [:pointer] :bool)

(ffi/defcfn resume-haptic
  "bool SDL_ResumeHaptic(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_ResumeHaptic" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ResumeHaptic" [:pointer] :bool)

(ffi/defcfn stop-haptic-effects
  "bool SDL_StopHapticEffects(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_StopHapticEffects" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_StopHapticEffects" [:pointer] :bool)

(ffi/defcfn haptic-rumble-supported
  "bool SDL_HapticRumbleSupported(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_HapticRumbleSupported" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_HapticRumbleSupported" [:pointer] :bool)

(ffi/defcfn init-haptic-rumble
  "bool SDL_InitHapticRumble(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_InitHapticRumble" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_InitHapticRumble" [:pointer] :bool)

(ffi/defcfn play-haptic-rumble
  "bool SDL_PlayHapticRumble(SDL_Haptic * haptic, float strength, Uint32 length)"
  {:arglists '([haptic strength length]) :sdl/c "SDL_PlayHapticRumble" :sdl/args [:pointer :float :uint32] :sdl/ret :bool}
  "SDL_PlayHapticRumble" [:pointer :float :uint32] :bool)

(ffi/defcfn stop-haptic-rumble
  "bool SDL_StopHapticRumble(SDL_Haptic * haptic)"
  {:arglists '([haptic]) :sdl/c "SDL_StopHapticRumble" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_StopHapticRumble" [:pointer] :bool)
