;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.hidapi
  "Raw bindings for SDL_hidapi.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def hid-device-info
  "ffi/layout of SDL_hid_device_info."
  (ffi/layout [:struct [[:path :pointer] [:vendor-id :uint16] [:product-id :uint16] [:serial-number :pointer] [:release-number :uint16] [:manufacturer-string :pointer] [:product-string :pointer] [:usage-page :uint16] [:usage :uint16] [:interface-number :int] [:interface-class :int] [:interface-subclass :int] [:interface-protocol :int] [:bus-type :int] [:next :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn hid-init
  "int SDL_hid_init(void)"
  {:arglists '([]) :sdl/c "SDL_hid_init" :sdl/args [] :sdl/ret :int}
  "SDL_hid_init" [] :int)

(ffi/defcfn hid-exit
  "int SDL_hid_exit(void)"
  {:arglists '([]) :sdl/c "SDL_hid_exit" :sdl/args [] :sdl/ret :int}
  "SDL_hid_exit" [] :int)

(ffi/defcfn hid-device-change-count
  "Uint32 SDL_hid_device_change_count(void)"
  {:arglists '([]) :sdl/c "SDL_hid_device_change_count" :sdl/args [] :sdl/ret :uint32}
  "SDL_hid_device_change_count" [] :uint32)

(ffi/defcfn hid-enumerate
  "SDL_hid_device_info * SDL_hid_enumerate(unsigned short vendor_id, unsigned short product_id)"
  {:arglists '([vendor-id product-id]) :sdl/c "SDL_hid_enumerate" :sdl/args [:uint16 :uint16] :sdl/ret :pointer}
  "SDL_hid_enumerate" [:uint16 :uint16] :pointer)

(ffi/defcfn hid-free-enumeration
  "void SDL_hid_free_enumeration(SDL_hid_device_info * devs)"
  {:arglists '([devs]) :sdl/c "SDL_hid_free_enumeration" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_hid_free_enumeration" [:pointer] :void)

(ffi/defcfn hid-open
  "SDL_hid_device * SDL_hid_open(unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)"
  {:arglists '([vendor-id product-id serial-number]) :sdl/c "SDL_hid_open" :sdl/args [:uint16 :uint16 :pointer] :sdl/ret :pointer}
  "SDL_hid_open" [:uint16 :uint16 :pointer] :pointer)

(ffi/defcfn hid-open-path
  "SDL_hid_device * SDL_hid_open_path(const char * path)"
  {:arglists '([path]) :sdl/c "SDL_hid_open_path" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_hid_open_path" [:string] :pointer)

(ffi/defcfn hid-get-properties
  "SDL_PropertiesID SDL_hid_get_properties(SDL_hid_device * dev)"
  {:arglists '([dev]) :sdl/c "SDL_hid_get_properties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_hid_get_properties" [:pointer] :uint32)

(ffi/defcfn hid-write
  "int SDL_hid_write(SDL_hid_device * dev, const unsigned char * data, size_t length)"
  {:arglists '([dev data length]) :sdl/c "SDL_hid_write" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_write" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-read-timeout
  "int SDL_hid_read_timeout(SDL_hid_device * dev, unsigned char * data, size_t length, int milliseconds)"
  {:arglists '([dev data length milliseconds]) :sdl/c "SDL_hid_read_timeout" :sdl/args [:pointer :pointer :size_t :int] :sdl/ret :int}
  "SDL_hid_read_timeout" [:pointer :pointer :size_t :int] :int)

(ffi/defcfn hid-read
  "int SDL_hid_read(SDL_hid_device * dev, unsigned char * data, size_t length)"
  {:arglists '([dev data length]) :sdl/c "SDL_hid_read" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_read" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-set-nonblocking
  "int SDL_hid_set_nonblocking(SDL_hid_device * dev, int nonblock)"
  {:arglists '([dev nonblock]) :sdl/c "SDL_hid_set_nonblocking" :sdl/args [:pointer :int] :sdl/ret :int}
  "SDL_hid_set_nonblocking" [:pointer :int] :int)

(ffi/defcfn hid-send-feature-report
  "int SDL_hid_send_feature_report(SDL_hid_device * dev, const unsigned char * data, size_t length)"
  {:arglists '([dev data length]) :sdl/c "SDL_hid_send_feature_report" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_send_feature_report" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-get-feature-report
  "int SDL_hid_get_feature_report(SDL_hid_device * dev, unsigned char * data, size_t length)"
  {:arglists '([dev data length]) :sdl/c "SDL_hid_get_feature_report" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_feature_report" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-get-input-report
  "int SDL_hid_get_input_report(SDL_hid_device * dev, unsigned char * data, size_t length)"
  {:arglists '([dev data length]) :sdl/c "SDL_hid_get_input_report" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_input_report" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-close
  "int SDL_hid_close(SDL_hid_device * dev)"
  {:arglists '([dev]) :sdl/c "SDL_hid_close" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_hid_close" [:pointer] :int)

(ffi/defcfn hid-get-manufacturer-string
  "int SDL_hid_get_manufacturer_string(SDL_hid_device * dev, wchar_t * string, size_t maxlen)"
  {:arglists '([dev string maxlen]) :sdl/c "SDL_hid_get_manufacturer_string" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_manufacturer_string" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-get-product-string
  "int SDL_hid_get_product_string(SDL_hid_device * dev, wchar_t * string, size_t maxlen)"
  {:arglists '([dev string maxlen]) :sdl/c "SDL_hid_get_product_string" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_product_string" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-get-serial-number-string
  "int SDL_hid_get_serial_number_string(SDL_hid_device * dev, wchar_t * string, size_t maxlen)"
  {:arglists '([dev string maxlen]) :sdl/c "SDL_hid_get_serial_number_string" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_serial_number_string" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-get-indexed-string
  "int SDL_hid_get_indexed_string(SDL_hid_device * dev, int string_index, wchar_t * string, size_t maxlen)"
  {:arglists '([dev string-index string maxlen]) :sdl/c "SDL_hid_get_indexed_string" :sdl/args [:pointer :int :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_indexed_string" [:pointer :int :pointer :size_t] :int)

(ffi/defcfn hid-get-device-info
  "SDL_hid_device_info * SDL_hid_get_device_info(SDL_hid_device * dev)"
  {:arglists '([dev]) :sdl/c "SDL_hid_get_device_info" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_hid_get_device_info" [:pointer] :pointer)

(ffi/defcfn hid-get-report-descriptor
  "int SDL_hid_get_report_descriptor(SDL_hid_device * dev, unsigned char * buf, size_t buf_size)"
  {:arglists '([dev buf buf-size]) :sdl/c "SDL_hid_get_report_descriptor" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_hid_get_report_descriptor" [:pointer :pointer :size_t] :int)

(ffi/defcfn hid-ble-scan
  "void SDL_hid_ble_scan(bool active)"
  {:arglists '([active]) :sdl/c "SDL_hid_ble_scan" :sdl/args [:bool] :sdl/ret :void}
  "SDL_hid_ble_scan" [:bool] :void)
