;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.hints
  "Raw bindings for SDL_hints.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn set-hint-with-priority
  "bool SDL_SetHintWithPriority(const char * name, const char * value, SDL_HintPriority priority)"
  {:arglists '([name value priority]) :sdl/c "SDL_SetHintWithPriority" :sdl/args [:string :string :int] :sdl/ret :bool}
  "SDL_SetHintWithPriority" [:string :string :int] :bool)

(ffi/defcfn set-hint
  "bool SDL_SetHint(const char * name, const char * value)"
  {:arglists '([name value]) :sdl/c "SDL_SetHint" :sdl/args [:string :string] :sdl/ret :bool}
  "SDL_SetHint" [:string :string] :bool)

(ffi/defcfn reset-hint
  "bool SDL_ResetHint(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_ResetHint" :sdl/args [:string] :sdl/ret :bool}
  "SDL_ResetHint" [:string] :bool)

(ffi/defcfn reset-hints
  "void SDL_ResetHints(void)"
  {:arglists '([]) :sdl/c "SDL_ResetHints" :sdl/args [] :sdl/ret :void}
  "SDL_ResetHints" [] :void)

(ffi/defcfn get-hint
  "const char * SDL_GetHint(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_GetHint" :sdl/args [:string] :sdl/ret :string}
  "SDL_GetHint" [:string] :string)

(ffi/defcfn get-hint-boolean
  "bool SDL_GetHintBoolean(const char * name, bool default_value)"
  {:arglists '([name default-value]) :sdl/c "SDL_GetHintBoolean" :sdl/args [:string :bool] :sdl/ret :bool}
  "SDL_GetHintBoolean" [:string :bool] :bool)

(ffi/defcfn add-hint-callback
  "bool SDL_AddHintCallback(const char * name, SDL_HintCallback callback, void * userdata)"
  {:arglists '([name callback userdata]) :sdl/c "SDL_AddHintCallback" :sdl/args [:string :pointer :pointer] :sdl/ret :bool}
  "SDL_AddHintCallback" [:string :pointer :pointer] :bool)

(ffi/defcfn remove-hint-callback
  "void SDL_RemoveHintCallback(const char * name, SDL_HintCallback callback, void * userdata)"
  {:arglists '([name callback userdata]) :sdl/c "SDL_RemoveHintCallback" :sdl/args [:string :pointer :pointer] :sdl/ret :void}
  "SDL_RemoveHintCallback" [:string :pointer :pointer] :void)
