;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.init
  "Raw bindings for SDL_init.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn init
  "bool SDL_Init(SDL_InitFlags flags)"
  {:arglists '([flags]) :sdl/c "SDL_Init" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_Init" [:uint32] :bool)

(ffi/defcfn init-sub-system
  "bool SDL_InitSubSystem(SDL_InitFlags flags)"
  {:arglists '([flags]) :sdl/c "SDL_InitSubSystem" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_InitSubSystem" [:uint32] :bool)

(ffi/defcfn quit-sub-system
  "void SDL_QuitSubSystem(SDL_InitFlags flags)"
  {:arglists '([flags]) :sdl/c "SDL_QuitSubSystem" :sdl/args [:uint32] :sdl/ret :void}
  "SDL_QuitSubSystem" [:uint32] :void)

(ffi/defcfn was-init
  "SDL_InitFlags SDL_WasInit(SDL_InitFlags flags)"
  {:arglists '([flags]) :sdl/c "SDL_WasInit" :sdl/args [:uint32] :sdl/ret :uint32}
  "SDL_WasInit" [:uint32] :uint32)

(ffi/defcfn quit
  "void SDL_Quit(void)"
  {:arglists '([]) :sdl/c "SDL_Quit" :sdl/args [] :sdl/ret :void}
  "SDL_Quit" [] :void)

(ffi/defcfn is-main-thread
  "bool SDL_IsMainThread(void)"
  {:arglists '([]) :sdl/c "SDL_IsMainThread" :sdl/args [] :sdl/ret :bool}
  "SDL_IsMainThread" [] :bool)

(ffi/defcfn run-on-main-thread
  "bool SDL_RunOnMainThread(SDL_MainThreadCallback callback, void * userdata, bool wait_complete)"
  {:arglists '([callback userdata wait-complete]) :sdl/c "SDL_RunOnMainThread" :sdl/args [:pointer :pointer :bool] :sdl/ret :bool}
  "SDL_RunOnMainThread" [:pointer :pointer :bool] :bool)

(ffi/defcfn set-app-metadata
  "bool SDL_SetAppMetadata(const char * appname, const char * appversion, const char * appidentifier)"
  {:arglists '([appname appversion appidentifier]) :sdl/c "SDL_SetAppMetadata" :sdl/args [:string :string :string] :sdl/ret :bool}
  "SDL_SetAppMetadata" [:string :string :string] :bool)

(ffi/defcfn set-app-metadata-property
  "bool SDL_SetAppMetadataProperty(const char * name, const char * value)"
  {:arglists '([name value]) :sdl/c "SDL_SetAppMetadataProperty" :sdl/args [:string :string] :sdl/ret :bool}
  "SDL_SetAppMetadataProperty" [:string :string] :bool)

(ffi/defcfn get-app-metadata-property
  "const char * SDL_GetAppMetadataProperty(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_GetAppMetadataProperty" :sdl/args [:string] :sdl/ret :string}
  "SDL_GetAppMetadataProperty" [:string] :string)
