;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.iostream
  "Raw bindings for SDL_iostream.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:refer-clojure :exclude [load-file])
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def io-stream-interface
  "ffi/layout of SDL_IOStreamInterface."
  (ffi/layout [:struct [[:version :uint32] [:size :pointer] [:seek :pointer] [:read :pointer] [:write :pointer] [:flush :pointer] [:close :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn io-from-file
  "SDL_IOStream * SDL_IOFromFile(const char * file, const char * mode)"
  {:arglists '([file mode]) :sdl/c "SDL_IOFromFile" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_IOFromFile" [:string :string] :pointer)

(ffi/defcfn io-from-mem
  "SDL_IOStream * SDL_IOFromMem(void * mem, size_t size)"
  {:arglists '([mem size]) :sdl/c "SDL_IOFromMem" :sdl/args [:pointer :size_t] :sdl/ret :pointer}
  "SDL_IOFromMem" [:pointer :size_t] :pointer)

(ffi/defcfn io-from-const-mem
  "SDL_IOStream * SDL_IOFromConstMem(const void * mem, size_t size)"
  {:arglists '([mem size]) :sdl/c "SDL_IOFromConstMem" :sdl/args [:pointer :size_t] :sdl/ret :pointer}
  "SDL_IOFromConstMem" [:pointer :size_t] :pointer)

(ffi/defcfn io-from-dynamic-mem
  "SDL_IOStream * SDL_IOFromDynamicMem(void)"
  {:arglists '([]) :sdl/c "SDL_IOFromDynamicMem" :sdl/args [] :sdl/ret :pointer}
  "SDL_IOFromDynamicMem" [] :pointer)

(ffi/defcfn open-io
  "SDL_IOStream * SDL_OpenIO(const SDL_IOStreamInterface * iface, void * userdata)"
  {:arglists '([iface userdata]) :sdl/c "SDL_OpenIO" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_OpenIO" [:pointer :pointer] :pointer)

(ffi/defcfn close-io
  "bool SDL_CloseIO(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_CloseIO" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_CloseIO" [:pointer] :bool)

(ffi/defcfn get-io-properties
  "SDL_PropertiesID SDL_GetIOProperties(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_GetIOProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetIOProperties" [:pointer] :uint32)

(ffi/defcfn get-io-status
  "SDL_IOStatus SDL_GetIOStatus(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_GetIOStatus" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetIOStatus" [:pointer] :int)

(ffi/defcfn get-io-size
  "Sint64 SDL_GetIOSize(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_GetIOSize" :sdl/args [:pointer] :sdl/ret :int64}
  "SDL_GetIOSize" [:pointer] :int64)

(ffi/defcfn seek-io
  "Sint64 SDL_SeekIO(SDL_IOStream * context, Sint64 offset, SDL_IOWhence whence)"
  {:arglists '([context offset whence]) :sdl/c "SDL_SeekIO" :sdl/args [:pointer :int64 :int] :sdl/ret :int64}
  "SDL_SeekIO" [:pointer :int64 :int] :int64)

(ffi/defcfn tell-io
  "Sint64 SDL_TellIO(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_TellIO" :sdl/args [:pointer] :sdl/ret :int64}
  "SDL_TellIO" [:pointer] :int64)

(ffi/defcfn read-io
  "size_t SDL_ReadIO(SDL_IOStream * context, void * ptr, size_t size)"
  {:arglists '([context ptr size]) :sdl/c "SDL_ReadIO" :sdl/args [:pointer :pointer :size_t] :sdl/ret :size_t}
  "SDL_ReadIO" [:pointer :pointer :size_t] :size_t)

(ffi/defcfn write-io
  "size_t SDL_WriteIO(SDL_IOStream * context, const void * ptr, size_t size)"
  {:arglists '([context ptr size]) :sdl/c "SDL_WriteIO" :sdl/args [:pointer :pointer :size_t] :sdl/ret :size_t}
  "SDL_WriteIO" [:pointer :pointer :size_t] :size_t)

(ffi/defcfn io-printf
  "size_t SDL_IOprintf(SDL_IOStream * context, const char * fmt, ...)"
  {:arglists '([context fmt & varargs]) :sdl/c "SDL_IOprintf" :sdl/args [:pointer :string :&] :sdl/ret :size_t}
  "SDL_IOprintf" [:pointer :string :&] :size_t)

(ffi/defcfn flush-io
  "bool SDL_FlushIO(SDL_IOStream * context)"
  {:arglists '([context]) :sdl/c "SDL_FlushIO" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_FlushIO" [:pointer] :bool)

(ffi/defcfn load-file-io
  "void * SDL_LoadFile_IO(SDL_IOStream * src, size_t * datasize, bool closeio)"
  {:arglists '([src datasize closeio]) :sdl/c "SDL_LoadFile_IO" :sdl/args [:pointer :pointer :bool] :sdl/ret :pointer}
  "SDL_LoadFile_IO" [:pointer :pointer :bool] :pointer)

(ffi/defcfn load-file
  "void * SDL_LoadFile(const char * file, size_t * datasize)"
  {:arglists '([file datasize]) :sdl/c "SDL_LoadFile" :sdl/args [:string :pointer] :sdl/ret :pointer}
  "SDL_LoadFile" [:string :pointer] :pointer)

(ffi/defcfn save-file-io
  "bool SDL_SaveFile_IO(SDL_IOStream * src, const void * data, size_t datasize, bool closeio)"
  {:arglists '([src data datasize closeio]) :sdl/c "SDL_SaveFile_IO" :sdl/args [:pointer :pointer :size_t :bool] :sdl/ret :bool}
  "SDL_SaveFile_IO" [:pointer :pointer :size_t :bool] :bool)

(ffi/defcfn save-file
  "bool SDL_SaveFile(const char * file, const void * data, size_t datasize)"
  {:arglists '([file data datasize]) :sdl/c "SDL_SaveFile" :sdl/args [:string :pointer :size_t] :sdl/ret :bool}
  "SDL_SaveFile" [:string :pointer :size_t] :bool)

(ffi/defcfn read-u8
  "bool SDL_ReadU8(SDL_IOStream * src, Uint8 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU8" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU8" [:pointer :pointer] :bool)

(ffi/defcfn read-s8
  "bool SDL_ReadS8(SDL_IOStream * src, Sint8 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS8" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS8" [:pointer :pointer] :bool)

(ffi/defcfn read-u16-le
  "bool SDL_ReadU16LE(SDL_IOStream * src, Uint16 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU16LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU16LE" [:pointer :pointer] :bool)

(ffi/defcfn read-s16-le
  "bool SDL_ReadS16LE(SDL_IOStream * src, Sint16 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS16LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS16LE" [:pointer :pointer] :bool)

(ffi/defcfn read-u16-be
  "bool SDL_ReadU16BE(SDL_IOStream * src, Uint16 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU16BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU16BE" [:pointer :pointer] :bool)

(ffi/defcfn read-s16-be
  "bool SDL_ReadS16BE(SDL_IOStream * src, Sint16 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS16BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS16BE" [:pointer :pointer] :bool)

(ffi/defcfn read-u32-le
  "bool SDL_ReadU32LE(SDL_IOStream * src, Uint32 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU32LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU32LE" [:pointer :pointer] :bool)

(ffi/defcfn read-s32-le
  "bool SDL_ReadS32LE(SDL_IOStream * src, Sint32 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS32LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS32LE" [:pointer :pointer] :bool)

(ffi/defcfn read-u32-be
  "bool SDL_ReadU32BE(SDL_IOStream * src, Uint32 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU32BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU32BE" [:pointer :pointer] :bool)

(ffi/defcfn read-s32-be
  "bool SDL_ReadS32BE(SDL_IOStream * src, Sint32 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS32BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS32BE" [:pointer :pointer] :bool)

(ffi/defcfn read-u64-le
  "bool SDL_ReadU64LE(SDL_IOStream * src, Uint64 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU64LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU64LE" [:pointer :pointer] :bool)

(ffi/defcfn read-s64-le
  "bool SDL_ReadS64LE(SDL_IOStream * src, Sint64 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS64LE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS64LE" [:pointer :pointer] :bool)

(ffi/defcfn read-u64-be
  "bool SDL_ReadU64BE(SDL_IOStream * src, Uint64 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadU64BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadU64BE" [:pointer :pointer] :bool)

(ffi/defcfn read-s64-be
  "bool SDL_ReadS64BE(SDL_IOStream * src, Sint64 * value)"
  {:arglists '([src value]) :sdl/c "SDL_ReadS64BE" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ReadS64BE" [:pointer :pointer] :bool)

(ffi/defcfn write-u8
  "bool SDL_WriteU8(SDL_IOStream * dst, Uint8 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU8" :sdl/args [:pointer :uint8] :sdl/ret :bool}
  "SDL_WriteU8" [:pointer :uint8] :bool)

(ffi/defcfn write-s8
  "bool SDL_WriteS8(SDL_IOStream * dst, Sint8 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS8" :sdl/args [:pointer :int8] :sdl/ret :bool}
  "SDL_WriteS8" [:pointer :int8] :bool)

(ffi/defcfn write-u16-le
  "bool SDL_WriteU16LE(SDL_IOStream * dst, Uint16 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU16LE" :sdl/args [:pointer :uint16] :sdl/ret :bool}
  "SDL_WriteU16LE" [:pointer :uint16] :bool)

(ffi/defcfn write-s16-le
  "bool SDL_WriteS16LE(SDL_IOStream * dst, Sint16 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS16LE" :sdl/args [:pointer :int16] :sdl/ret :bool}
  "SDL_WriteS16LE" [:pointer :int16] :bool)

(ffi/defcfn write-u16-be
  "bool SDL_WriteU16BE(SDL_IOStream * dst, Uint16 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU16BE" :sdl/args [:pointer :uint16] :sdl/ret :bool}
  "SDL_WriteU16BE" [:pointer :uint16] :bool)

(ffi/defcfn write-s16-be
  "bool SDL_WriteS16BE(SDL_IOStream * dst, Sint16 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS16BE" :sdl/args [:pointer :int16] :sdl/ret :bool}
  "SDL_WriteS16BE" [:pointer :int16] :bool)

(ffi/defcfn write-u32-le
  "bool SDL_WriteU32LE(SDL_IOStream * dst, Uint32 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU32LE" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_WriteU32LE" [:pointer :uint32] :bool)

(ffi/defcfn write-s32-le
  "bool SDL_WriteS32LE(SDL_IOStream * dst, Sint32 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS32LE" :sdl/args [:pointer :int32] :sdl/ret :bool}
  "SDL_WriteS32LE" [:pointer :int32] :bool)

(ffi/defcfn write-u32-be
  "bool SDL_WriteU32BE(SDL_IOStream * dst, Uint32 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU32BE" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_WriteU32BE" [:pointer :uint32] :bool)

(ffi/defcfn write-s32-be
  "bool SDL_WriteS32BE(SDL_IOStream * dst, Sint32 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS32BE" :sdl/args [:pointer :int32] :sdl/ret :bool}
  "SDL_WriteS32BE" [:pointer :int32] :bool)

(ffi/defcfn write-u64-le
  "bool SDL_WriteU64LE(SDL_IOStream * dst, Uint64 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU64LE" :sdl/args [:pointer :uint64] :sdl/ret :bool}
  "SDL_WriteU64LE" [:pointer :uint64] :bool)

(ffi/defcfn write-s64-le
  "bool SDL_WriteS64LE(SDL_IOStream * dst, Sint64 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS64LE" :sdl/args [:pointer :int64] :sdl/ret :bool}
  "SDL_WriteS64LE" [:pointer :int64] :bool)

(ffi/defcfn write-u64-be
  "bool SDL_WriteU64BE(SDL_IOStream * dst, Uint64 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteU64BE" :sdl/args [:pointer :uint64] :sdl/ret :bool}
  "SDL_WriteU64BE" [:pointer :uint64] :bool)

(ffi/defcfn write-s64-be
  "bool SDL_WriteS64BE(SDL_IOStream * dst, Sint64 value)"
  {:arglists '([dst value]) :sdl/c "SDL_WriteS64BE" :sdl/args [:pointer :int64] :sdl/ret :bool}
  "SDL_WriteS64BE" [:pointer :int64] :bool)
