;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.joystick
  "Raw bindings for SDL_joystick.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def virtual-joystick-touchpad-desc
  "ffi/layout of SDL_VirtualJoystickTouchpadDesc."
  (ffi/layout [:struct [[:nfingers :uint16] [:padding [:array :uint16 3]]]]))

(def virtual-joystick-sensor-desc
  "ffi/layout of SDL_VirtualJoystickSensorDesc."
  (ffi/layout [:struct [[:type :int] [:rate :float]]]))

(def virtual-joystick-desc
  "ffi/layout of SDL_VirtualJoystickDesc."
  (ffi/layout [:struct [[:version :uint32] [:type :uint16] [:padding :uint16] [:vendor-id :uint16] [:product-id :uint16] [:naxes :uint16] [:nbuttons :uint16] [:nballs :uint16] [:nhats :uint16] [:ntouchpads :uint16] [:nsensors :uint16] [:padding2 [:array :uint16 2]] [:button-mask :uint32] [:axis-mask :uint32] [:name :pointer] [:touchpads :pointer] [:sensors :pointer] [:userdata :pointer] [:update :pointer] [:set-player-index :pointer] [:rumble :pointer] [:rumble-triggers :pointer] [:set-led :pointer] [:send-effect :pointer] [:set-sensors-enabled :pointer] [:cleanup :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn lock-joysticks
  "void SDL_LockJoysticks(void)"
  {:arglists '([]) :sdl/c "SDL_LockJoysticks" :sdl/args [] :sdl/ret :void}
  "SDL_LockJoysticks" [] :void)

(ffi/defcfn unlock-joysticks
  "void SDL_UnlockJoysticks(void)"
  {:arglists '([]) :sdl/c "SDL_UnlockJoysticks" :sdl/args [] :sdl/ret :void}
  "SDL_UnlockJoysticks" [] :void)

(ffi/defcfn has-joystick
  "bool SDL_HasJoystick(void)"
  {:arglists '([]) :sdl/c "SDL_HasJoystick" :sdl/args [] :sdl/ret :bool}
  "SDL_HasJoystick" [] :bool)

(ffi/defcfn get-joysticks
  "SDL_JoystickID * SDL_GetJoysticks(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetJoysticks" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetJoysticks" [:pointer] :pointer)

(ffi/defcfn get-joystick-name-for-id
  "const char * SDL_GetJoystickNameForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickNameForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetJoystickNameForID" [:uint32] :string)

(ffi/defcfn get-joystick-path-for-id
  "const char * SDL_GetJoystickPathForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickPathForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetJoystickPathForID" [:uint32] :string)

(ffi/defcfn get-joystick-player-index-for-id
  "int SDL_GetJoystickPlayerIndexForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickPlayerIndexForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetJoystickPlayerIndexForID" [:uint32] :int)

(ffi/defcfn get-joystick-guid-for-id
  "SDL_GUID SDL_GetJoystickGUIDForID(SDL_JoystickID instance_id)"
  {:arglists '([out instance-id]) :sdl/c "SDL_GetJoystickGUIDForID" :sdl/args [:uint32] :sdl/ret [:by-value [:struct [[:data [:array :uint8 16]]]]]}
  "SDL_GetJoystickGUIDForID" [:uint32] [:by-value [:struct [[:data [:array :uint8 16]]]]])

(ffi/defcfn get-joystick-vendor-for-id
  "Uint16 SDL_GetJoystickVendorForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickVendorForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetJoystickVendorForID" [:uint32] :uint16)

(ffi/defcfn get-joystick-product-for-id
  "Uint16 SDL_GetJoystickProductForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickProductForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetJoystickProductForID" [:uint32] :uint16)

(ffi/defcfn get-joystick-product-version-for-id
  "Uint16 SDL_GetJoystickProductVersionForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickProductVersionForID" :sdl/args [:uint32] :sdl/ret :uint16}
  "SDL_GetJoystickProductVersionForID" [:uint32] :uint16)

(ffi/defcfn get-joystick-type-for-id
  "SDL_JoystickType SDL_GetJoystickTypeForID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickTypeForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetJoystickTypeForID" [:uint32] :int)

(ffi/defcfn open-joystick
  "SDL_Joystick * SDL_OpenJoystick(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_OpenJoystick" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_OpenJoystick" [:uint32] :pointer)

(ffi/defcfn get-joystick-from-id
  "SDL_Joystick * SDL_GetJoystickFromID(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetJoystickFromID" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_GetJoystickFromID" [:uint32] :pointer)

(ffi/defcfn get-joystick-from-player-index
  "SDL_Joystick * SDL_GetJoystickFromPlayerIndex(int player_index)"
  {:arglists '([player-index]) :sdl/c "SDL_GetJoystickFromPlayerIndex" :sdl/args [:int] :sdl/ret :pointer}
  "SDL_GetJoystickFromPlayerIndex" [:int] :pointer)

(ffi/defcfn attach-virtual-joystick
  "SDL_JoystickID SDL_AttachVirtualJoystick(const SDL_VirtualJoystickDesc * desc)"
  {:arglists '([desc]) :sdl/c "SDL_AttachVirtualJoystick" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_AttachVirtualJoystick" [:pointer] :uint32)

(ffi/defcfn detach-virtual-joystick
  "bool SDL_DetachVirtualJoystick(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_DetachVirtualJoystick" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_DetachVirtualJoystick" [:uint32] :bool)

(ffi/defcfn is-joystick-virtual
  "bool SDL_IsJoystickVirtual(SDL_JoystickID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_IsJoystickVirtual" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_IsJoystickVirtual" [:uint32] :bool)

(ffi/defcfn set-joystick-virtual-axis
  "bool SDL_SetJoystickVirtualAxis(SDL_Joystick * joystick, int axis, Sint16 value)"
  {:arglists '([joystick axis value]) :sdl/c "SDL_SetJoystickVirtualAxis" :sdl/args [:pointer :int :int16] :sdl/ret :bool}
  "SDL_SetJoystickVirtualAxis" [:pointer :int :int16] :bool)

(ffi/defcfn set-joystick-virtual-ball
  "bool SDL_SetJoystickVirtualBall(SDL_Joystick * joystick, int ball, Sint16 xrel, Sint16 yrel)"
  {:arglists '([joystick ball xrel yrel]) :sdl/c "SDL_SetJoystickVirtualBall" :sdl/args [:pointer :int :int16 :int16] :sdl/ret :bool}
  "SDL_SetJoystickVirtualBall" [:pointer :int :int16 :int16] :bool)

(ffi/defcfn set-joystick-virtual-button
  "bool SDL_SetJoystickVirtualButton(SDL_Joystick * joystick, int button, bool down)"
  {:arglists '([joystick button down]) :sdl/c "SDL_SetJoystickVirtualButton" :sdl/args [:pointer :int :bool] :sdl/ret :bool}
  "SDL_SetJoystickVirtualButton" [:pointer :int :bool] :bool)

(ffi/defcfn set-joystick-virtual-hat
  "bool SDL_SetJoystickVirtualHat(SDL_Joystick * joystick, int hat, Uint8 value)"
  {:arglists '([joystick hat value]) :sdl/c "SDL_SetJoystickVirtualHat" :sdl/args [:pointer :int :uint8] :sdl/ret :bool}
  "SDL_SetJoystickVirtualHat" [:pointer :int :uint8] :bool)

(ffi/defcfn set-joystick-virtual-touchpad
  "bool SDL_SetJoystickVirtualTouchpad(SDL_Joystick * joystick, int touchpad, int finger, bool down, float x, float y, float pressure)"
  {:arglists '([joystick touchpad finger down x y pressure]) :sdl/c "SDL_SetJoystickVirtualTouchpad" :sdl/args [:pointer :int :int :bool :float :float :float] :sdl/ret :bool}
  "SDL_SetJoystickVirtualTouchpad" [:pointer :int :int :bool :float :float :float] :bool)

(ffi/defcfn send-joystick-virtual-sensor-data
  "bool SDL_SendJoystickVirtualSensorData(SDL_Joystick * joystick, SDL_SensorType type, Uint64 sensor_timestamp, const float * data, int num_values)"
  {:arglists '([joystick type sensor-timestamp data num-values]) :sdl/c "SDL_SendJoystickVirtualSensorData" :sdl/args [:pointer :int :uint64 :pointer :int] :sdl/ret :bool}
  "SDL_SendJoystickVirtualSensorData" [:pointer :int :uint64 :pointer :int] :bool)

(ffi/defcfn get-joystick-properties
  "SDL_PropertiesID SDL_GetJoystickProperties(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetJoystickProperties" [:pointer] :uint32)

(ffi/defcfn get-joystick-name
  "const char * SDL_GetJoystickName(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetJoystickName" [:pointer] :string)

(ffi/defcfn get-joystick-path
  "const char * SDL_GetJoystickPath(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickPath" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetJoystickPath" [:pointer] :string)

(ffi/defcfn get-joystick-player-index
  "int SDL_GetJoystickPlayerIndex(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickPlayerIndex" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetJoystickPlayerIndex" [:pointer] :int)

(ffi/defcfn set-joystick-player-index
  "bool SDL_SetJoystickPlayerIndex(SDL_Joystick * joystick, int player_index)"
  {:arglists '([joystick player-index]) :sdl/c "SDL_SetJoystickPlayerIndex" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetJoystickPlayerIndex" [:pointer :int] :bool)

(ffi/defcfn get-joystick-guid
  "SDL_GUID SDL_GetJoystickGUID(SDL_Joystick * joystick)"
  {:arglists '([out joystick]) :sdl/c "SDL_GetJoystickGUID" :sdl/args [:pointer] :sdl/ret [:by-value [:struct [[:data [:array :uint8 16]]]]]}
  "SDL_GetJoystickGUID" [:pointer] [:by-value [:struct [[:data [:array :uint8 16]]]]])

(ffi/defcfn get-joystick-vendor
  "Uint16 SDL_GetJoystickVendor(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickVendor" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetJoystickVendor" [:pointer] :uint16)

(ffi/defcfn get-joystick-product
  "Uint16 SDL_GetJoystickProduct(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickProduct" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetJoystickProduct" [:pointer] :uint16)

(ffi/defcfn get-joystick-product-version
  "Uint16 SDL_GetJoystickProductVersion(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickProductVersion" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetJoystickProductVersion" [:pointer] :uint16)

(ffi/defcfn get-joystick-firmware-version
  "Uint16 SDL_GetJoystickFirmwareVersion(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickFirmwareVersion" :sdl/args [:pointer] :sdl/ret :uint16}
  "SDL_GetJoystickFirmwareVersion" [:pointer] :uint16)

(ffi/defcfn get-joystick-serial
  "const char * SDL_GetJoystickSerial(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickSerial" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetJoystickSerial" [:pointer] :string)

(ffi/defcfn get-joystick-type
  "SDL_JoystickType SDL_GetJoystickType(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickType" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetJoystickType" [:pointer] :int)

(ffi/defcfn get-joystick-guid-info
  "void SDL_GetJoystickGUIDInfo(SDL_GUID guid, Uint16 * vendor, Uint16 * product, Uint16 * version, Uint16 * crc16)"
  {:arglists '([guid vendor product version crc16]) :sdl/c "SDL_GetJoystickGUIDInfo" :sdl/args [[:by-value [:struct [[:data [:array :uint8 16]]]]] :pointer :pointer :pointer :pointer] :sdl/ret :void}
  "SDL_GetJoystickGUIDInfo" [[:by-value [:struct [[:data [:array :uint8 16]]]]] :pointer :pointer :pointer :pointer] :void)

(ffi/defcfn joystick-connected
  "bool SDL_JoystickConnected(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_JoystickConnected" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_JoystickConnected" [:pointer] :bool)

(ffi/defcfn get-joystick-id
  "SDL_JoystickID SDL_GetJoystickID(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickID" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetJoystickID" [:pointer] :uint32)

(ffi/defcfn get-num-joystick-axes
  "int SDL_GetNumJoystickAxes(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetNumJoystickAxes" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumJoystickAxes" [:pointer] :int)

(ffi/defcfn get-num-joystick-balls
  "int SDL_GetNumJoystickBalls(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetNumJoystickBalls" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumJoystickBalls" [:pointer] :int)

(ffi/defcfn get-num-joystick-hats
  "int SDL_GetNumJoystickHats(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetNumJoystickHats" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumJoystickHats" [:pointer] :int)

(ffi/defcfn get-num-joystick-buttons
  "int SDL_GetNumJoystickButtons(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetNumJoystickButtons" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetNumJoystickButtons" [:pointer] :int)

(ffi/defcfn set-joystick-events-enabled
  "void SDL_SetJoystickEventsEnabled(bool enabled)"
  {:arglists '([enabled]) :sdl/c "SDL_SetJoystickEventsEnabled" :sdl/args [:bool] :sdl/ret :void}
  "SDL_SetJoystickEventsEnabled" [:bool] :void)

(ffi/defcfn joystick-events-enabled
  "bool SDL_JoystickEventsEnabled(void)"
  {:arglists '([]) :sdl/c "SDL_JoystickEventsEnabled" :sdl/args [] :sdl/ret :bool}
  "SDL_JoystickEventsEnabled" [] :bool)

(ffi/defcfn update-joysticks
  "void SDL_UpdateJoysticks(void)"
  {:arglists '([]) :sdl/c "SDL_UpdateJoysticks" :sdl/args [] :sdl/ret :void}
  "SDL_UpdateJoysticks" [] :void)

(ffi/defcfn get-joystick-axis
  "Sint16 SDL_GetJoystickAxis(SDL_Joystick * joystick, int axis)"
  {:arglists '([joystick axis]) :sdl/c "SDL_GetJoystickAxis" :sdl/args [:pointer :int] :sdl/ret :int16}
  "SDL_GetJoystickAxis" [:pointer :int] :int16)

(ffi/defcfn get-joystick-axis-initial-state
  "bool SDL_GetJoystickAxisInitialState(SDL_Joystick * joystick, int axis, Sint16 * state)"
  {:arglists '([joystick axis state]) :sdl/c "SDL_GetJoystickAxisInitialState" :sdl/args [:pointer :int :pointer] :sdl/ret :bool}
  "SDL_GetJoystickAxisInitialState" [:pointer :int :pointer] :bool)

(ffi/defcfn get-joystick-ball
  "bool SDL_GetJoystickBall(SDL_Joystick * joystick, int ball, int * dx, int * dy)"
  {:arglists '([joystick ball dx dy]) :sdl/c "SDL_GetJoystickBall" :sdl/args [:pointer :int :pointer :pointer] :sdl/ret :bool}
  "SDL_GetJoystickBall" [:pointer :int :pointer :pointer] :bool)

(ffi/defcfn get-joystick-hat
  "Uint8 SDL_GetJoystickHat(SDL_Joystick * joystick, int hat)"
  {:arglists '([joystick hat]) :sdl/c "SDL_GetJoystickHat" :sdl/args [:pointer :int] :sdl/ret :uint8}
  "SDL_GetJoystickHat" [:pointer :int] :uint8)

(ffi/defcfn get-joystick-button
  "bool SDL_GetJoystickButton(SDL_Joystick * joystick, int button)"
  {:arglists '([joystick button]) :sdl/c "SDL_GetJoystickButton" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_GetJoystickButton" [:pointer :int] :bool)

(ffi/defcfn rumble-joystick
  "bool SDL_RumbleJoystick(SDL_Joystick * joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)"
  {:arglists '([joystick low-frequency-rumble high-frequency-rumble duration-ms]) :sdl/c "SDL_RumbleJoystick" :sdl/args [:pointer :uint16 :uint16 :uint32] :sdl/ret :bool}
  "SDL_RumbleJoystick" [:pointer :uint16 :uint16 :uint32] :bool)

(ffi/defcfn rumble-joystick-triggers
  "bool SDL_RumbleJoystickTriggers(SDL_Joystick * joystick, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)"
  {:arglists '([joystick left-rumble right-rumble duration-ms]) :sdl/c "SDL_RumbleJoystickTriggers" :sdl/args [:pointer :uint16 :uint16 :uint32] :sdl/ret :bool}
  "SDL_RumbleJoystickTriggers" [:pointer :uint16 :uint16 :uint32] :bool)

(ffi/defcfn set-joystick-led
  "bool SDL_SetJoystickLED(SDL_Joystick * joystick, Uint8 red, Uint8 green, Uint8 blue)"
  {:arglists '([joystick red green blue]) :sdl/c "SDL_SetJoystickLED" :sdl/args [:pointer :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_SetJoystickLED" [:pointer :uint8 :uint8 :uint8] :bool)

(ffi/defcfn send-joystick-effect
  "bool SDL_SendJoystickEffect(SDL_Joystick * joystick, const void * data, int size)"
  {:arglists '([joystick data size]) :sdl/c "SDL_SendJoystickEffect" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_SendJoystickEffect" [:pointer :pointer :int] :bool)

(ffi/defcfn close-joystick
  "void SDL_CloseJoystick(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_CloseJoystick" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_CloseJoystick" [:pointer] :void)

(ffi/defcfn get-joystick-connection-state
  "SDL_JoystickConnectionState SDL_GetJoystickConnectionState(SDL_Joystick * joystick)"
  {:arglists '([joystick]) :sdl/c "SDL_GetJoystickConnectionState" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetJoystickConnectionState" [:pointer] :int)

(ffi/defcfn get-joystick-power-info
  "SDL_PowerState SDL_GetJoystickPowerInfo(SDL_Joystick * joystick, int * percent)"
  {:arglists '([joystick percent]) :sdl/c "SDL_GetJoystickPowerInfo" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "SDL_GetJoystickPowerInfo" [:pointer :pointer] :int)
