;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.keyboard
  "Raw bindings for SDL_keyboard.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn has-keyboard
  "bool SDL_HasKeyboard(void)"
  {:arglists '([]) :sdl/c "SDL_HasKeyboard" :sdl/args [] :sdl/ret :bool}
  "SDL_HasKeyboard" [] :bool)

(ffi/defcfn get-keyboards
  "SDL_KeyboardID * SDL_GetKeyboards(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetKeyboards" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetKeyboards" [:pointer] :pointer)

(ffi/defcfn get-keyboard-name-for-id
  "const char * SDL_GetKeyboardNameForID(SDL_KeyboardID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetKeyboardNameForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetKeyboardNameForID" [:uint32] :string)

(ffi/defcfn get-keyboard-focus
  "SDL_Window * SDL_GetKeyboardFocus(void)"
  {:arglists '([]) :sdl/c "SDL_GetKeyboardFocus" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetKeyboardFocus" [] :pointer)

(ffi/defcfn get-keyboard-state
  "const bool * SDL_GetKeyboardState(int * numkeys)"
  {:arglists '([numkeys]) :sdl/c "SDL_GetKeyboardState" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetKeyboardState" [:pointer] :pointer)

(ffi/defcfn reset-keyboard
  "void SDL_ResetKeyboard(void)"
  {:arglists '([]) :sdl/c "SDL_ResetKeyboard" :sdl/args [] :sdl/ret :void}
  "SDL_ResetKeyboard" [] :void)

(ffi/defcfn get-mod-state
  "SDL_Keymod SDL_GetModState(void)"
  {:arglists '([]) :sdl/c "SDL_GetModState" :sdl/args [] :sdl/ret :uint16}
  "SDL_GetModState" [] :uint16)

(ffi/defcfn set-mod-state
  "void SDL_SetModState(SDL_Keymod modstate)"
  {:arglists '([modstate]) :sdl/c "SDL_SetModState" :sdl/args [:uint16] :sdl/ret :void}
  "SDL_SetModState" [:uint16] :void)

(ffi/defcfn get-key-from-scancode
  "SDL_Keycode SDL_GetKeyFromScancode(SDL_Scancode scancode, SDL_Keymod modstate, bool key_event)"
  {:arglists '([scancode modstate key-event]) :sdl/c "SDL_GetKeyFromScancode" :sdl/args [:int :uint16 :bool] :sdl/ret :uint32}
  "SDL_GetKeyFromScancode" [:int :uint16 :bool] :uint32)

(ffi/defcfn get-scancode-from-key
  "SDL_Scancode SDL_GetScancodeFromKey(SDL_Keycode key, SDL_Keymod * modstate)"
  {:arglists '([key modstate]) :sdl/c "SDL_GetScancodeFromKey" :sdl/args [:uint32 :pointer] :sdl/ret :int}
  "SDL_GetScancodeFromKey" [:uint32 :pointer] :int)

(ffi/defcfn set-scancode-name
  "bool SDL_SetScancodeName(SDL_Scancode scancode, const char * name)"
  {:arglists '([scancode name]) :sdl/c "SDL_SetScancodeName" :sdl/args [:int :string] :sdl/ret :bool}
  "SDL_SetScancodeName" [:int :string] :bool)

(ffi/defcfn get-scancode-name
  "const char * SDL_GetScancodeName(SDL_Scancode scancode)"
  {:arglists '([scancode]) :sdl/c "SDL_GetScancodeName" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetScancodeName" [:int] :string)

(ffi/defcfn get-scancode-from-name
  "SDL_Scancode SDL_GetScancodeFromName(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_GetScancodeFromName" :sdl/args [:string] :sdl/ret :int}
  "SDL_GetScancodeFromName" [:string] :int)

(ffi/defcfn get-key-name
  "const char * SDL_GetKeyName(SDL_Keycode key)"
  {:arglists '([key]) :sdl/c "SDL_GetKeyName" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetKeyName" [:uint32] :string)

(ffi/defcfn get-key-from-name
  "SDL_Keycode SDL_GetKeyFromName(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_GetKeyFromName" :sdl/args [:string] :sdl/ret :uint32}
  "SDL_GetKeyFromName" [:string] :uint32)

(ffi/defcfn start-text-input
  "bool SDL_StartTextInput(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_StartTextInput" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_StartTextInput" [:pointer] :bool)

(ffi/defcfn start-text-input-with-properties
  "bool SDL_StartTextInputWithProperties(SDL_Window * window, SDL_PropertiesID props)"
  {:arglists '([window props]) :sdl/c "SDL_StartTextInputWithProperties" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_StartTextInputWithProperties" [:pointer :uint32] :bool)

(ffi/defcfn text-input-active
  "bool SDL_TextInputActive(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_TextInputActive" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TextInputActive" [:pointer] :bool)

(ffi/defcfn stop-text-input
  "bool SDL_StopTextInput(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_StopTextInput" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_StopTextInput" [:pointer] :bool)

(ffi/defcfn clear-composition
  "bool SDL_ClearComposition(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_ClearComposition" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ClearComposition" [:pointer] :bool)

(ffi/defcfn set-text-input-area
  "bool SDL_SetTextInputArea(SDL_Window * window, const SDL_Rect * rect, int cursor)"
  {:arglists '([window rect cursor]) :sdl/c "SDL_SetTextInputArea" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_SetTextInputArea" [:pointer :pointer :int] :bool)

(ffi/defcfn get-text-input-area
  "bool SDL_GetTextInputArea(SDL_Window * window, SDL_Rect * rect, int * cursor)"
  {:arglists '([window rect cursor]) :sdl/c "SDL_GetTextInputArea" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextInputArea" [:pointer :pointer :pointer] :bool)

(ffi/defcfn has-screen-keyboard-support
  "bool SDL_HasScreenKeyboardSupport(void)"
  {:arglists '([]) :sdl/c "SDL_HasScreenKeyboardSupport" :sdl/args [] :sdl/ret :bool}
  "SDL_HasScreenKeyboardSupport" [] :bool)

(ffi/defcfn screen-keyboard-shown
  "bool SDL_ScreenKeyboardShown(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_ScreenKeyboardShown" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ScreenKeyboardShown" [:pointer] :bool)
