;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.locale
  "Raw bindings for SDL_locale.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def locale
  "ffi/layout of SDL_Locale."
  (ffi/layout [:struct [[:language :pointer] [:country :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-preferred-locales
  "SDL_Locale ** SDL_GetPreferredLocales(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetPreferredLocales" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetPreferredLocales" [:pointer] :pointer)
