;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.log
  "Raw bindings for SDL_log.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn set-log-priorities
  "void SDL_SetLogPriorities(SDL_LogPriority priority)"
  {:arglists '([priority]) :sdl/c "SDL_SetLogPriorities" :sdl/args [:int] :sdl/ret :void}
  "SDL_SetLogPriorities" [:int] :void)

(ffi/defcfn set-log-priority
  "void SDL_SetLogPriority(int category, SDL_LogPriority priority)"
  {:arglists '([category priority]) :sdl/c "SDL_SetLogPriority" :sdl/args [:int :int] :sdl/ret :void}
  "SDL_SetLogPriority" [:int :int] :void)

(ffi/defcfn get-log-priority
  "SDL_LogPriority SDL_GetLogPriority(int category)"
  {:arglists '([category]) :sdl/c "SDL_GetLogPriority" :sdl/args [:int] :sdl/ret :int}
  "SDL_GetLogPriority" [:int] :int)

(ffi/defcfn reset-log-priorities
  "void SDL_ResetLogPriorities(void)"
  {:arglists '([]) :sdl/c "SDL_ResetLogPriorities" :sdl/args [] :sdl/ret :void}
  "SDL_ResetLogPriorities" [] :void)

(ffi/defcfn set-log-priority-prefix
  "bool SDL_SetLogPriorityPrefix(SDL_LogPriority priority, const char * prefix)"
  {:arglists '([priority prefix]) :sdl/c "SDL_SetLogPriorityPrefix" :sdl/args [:int :string] :sdl/ret :bool}
  "SDL_SetLogPriorityPrefix" [:int :string] :bool)

(ffi/defcfn log
  "void SDL_Log(const char * fmt, ...)"
  {:arglists '([fmt & varargs]) :sdl/c "SDL_Log" :sdl/args [:string :&] :sdl/ret :void}
  "SDL_Log" [:string :&] :void)

(ffi/defcfn log-trace
  "void SDL_LogTrace(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogTrace" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogTrace" [:int :string :&] :void)

(ffi/defcfn log-verbose
  "void SDL_LogVerbose(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogVerbose" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogVerbose" [:int :string :&] :void)

(ffi/defcfn log-debug
  "void SDL_LogDebug(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogDebug" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogDebug" [:int :string :&] :void)

(ffi/defcfn log-info
  "void SDL_LogInfo(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogInfo" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogInfo" [:int :string :&] :void)

(ffi/defcfn log-warn
  "void SDL_LogWarn(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogWarn" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogWarn" [:int :string :&] :void)

(ffi/defcfn log-error
  "void SDL_LogError(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogError" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogError" [:int :string :&] :void)

(ffi/defcfn log-critical
  "void SDL_LogCritical(int category, const char * fmt, ...)"
  {:arglists '([category fmt & varargs]) :sdl/c "SDL_LogCritical" :sdl/args [:int :string :&] :sdl/ret :void}
  "SDL_LogCritical" [:int :string :&] :void)

(ffi/defcfn log-message
  "void SDL_LogMessage(int category, SDL_LogPriority priority, const char * fmt, ...)"
  {:arglists '([category priority fmt & varargs]) :sdl/c "SDL_LogMessage" :sdl/args [:int :int :string :&] :sdl/ret :void}
  "SDL_LogMessage" [:int :int :string :&] :void)

(ffi/defcfn get-default-log-output-function
  "SDL_LogOutputFunction SDL_GetDefaultLogOutputFunction(void)"
  {:arglists '([]) :sdl/c "SDL_GetDefaultLogOutputFunction" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetDefaultLogOutputFunction" [] :pointer)

(ffi/defcfn get-log-output-function
  "void SDL_GetLogOutputFunction(SDL_LogOutputFunction * callback, void ** userdata)"
  {:arglists '([callback userdata]) :sdl/c "SDL_GetLogOutputFunction" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_GetLogOutputFunction" [:pointer :pointer] :void)

(ffi/defcfn set-log-output-function
  "void SDL_SetLogOutputFunction(SDL_LogOutputFunction callback, void * userdata)"
  {:arglists '([callback userdata]) :sdl/c "SDL_SetLogOutputFunction" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_SetLogOutputFunction" [:pointer :pointer] :void)
