;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.messagebox
  "Raw bindings for SDL_messagebox.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def message-box-button-data
  "ffi/layout of SDL_MessageBoxButtonData."
  (ffi/layout [:struct [[:flags :uint32] [:button-id :int] [:text :pointer]]]))

(def message-box-color
  "ffi/layout of SDL_MessageBoxColor."
  (ffi/layout [:struct [[:r :uint8] [:g :uint8] [:b :uint8]]]))

(def message-box-color-scheme
  "ffi/layout of SDL_MessageBoxColorScheme."
  (ffi/layout [:struct [[:colors [:array [:struct [[:r :uint8] [:g :uint8] [:b :uint8]]] 5]]]]))

(def message-box-data
  "ffi/layout of SDL_MessageBoxData."
  (ffi/layout [:struct [[:flags :uint32] [:window :pointer] [:title :pointer] [:message :pointer] [:numbuttons :int] [:buttons :pointer] [:color-scheme :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn show-message-box
  "bool SDL_ShowMessageBox(const SDL_MessageBoxData * messageboxdata, int * buttonid)"
  {:arglists '([messageboxdata buttonid]) :sdl/c "SDL_ShowMessageBox" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ShowMessageBox" [:pointer :pointer] :bool :blocking)

(ffi/defcfn show-simple-message-box
  "bool SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, const char * title, const char * message, SDL_Window * window)"
  {:arglists '([flags title message window]) :sdl/c "SDL_ShowSimpleMessageBox" :sdl/args [:uint32 :string :string :pointer] :sdl/ret :bool}
  "SDL_ShowSimpleMessageBox" [:uint32 :string :string :pointer] :bool)
