;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.metal
  "Raw bindings for SDL_metal.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn metal-create-view
  "SDL_MetalView SDL_Metal_CreateView(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_Metal_CreateView" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_Metal_CreateView" [:pointer] :pointer)

(ffi/defcfn metal-destroy-view
  "void SDL_Metal_DestroyView(SDL_MetalView view)"
  {:arglists '([view]) :sdl/c "SDL_Metal_DestroyView" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_Metal_DestroyView" [:pointer] :void)

(ffi/defcfn metal-get-layer
  "void * SDL_Metal_GetLayer(SDL_MetalView view)"
  {:arglists '([view]) :sdl/c "SDL_Metal_GetLayer" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_Metal_GetLayer" [:pointer] :pointer)
