;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.mutex
  "Raw bindings for SDL_mutex.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def init-state
  "ffi/layout of SDL_InitState."
  (ffi/layout [:struct [[:status [:struct [[:value :int]]]] [:thread :uint64] [:reserved :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn create-mutex
  "SDL_Mutex * SDL_CreateMutex(void)"
  {:arglists '([]) :sdl/c "SDL_CreateMutex" :sdl/args [] :sdl/ret :pointer}
  "SDL_CreateMutex" [] :pointer)

(ffi/defcfn lock-mutex
  "void SDL_LockMutex(SDL_Mutex * mutex)"
  {:arglists '([mutex]) :sdl/c "SDL_LockMutex" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_LockMutex" [:pointer] :void :blocking)

(ffi/defcfn try-lock-mutex
  "bool SDL_TryLockMutex(SDL_Mutex * mutex)"
  {:arglists '([mutex]) :sdl/c "SDL_TryLockMutex" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TryLockMutex" [:pointer] :bool)

(ffi/defcfn unlock-mutex
  "void SDL_UnlockMutex(SDL_Mutex * mutex)"
  {:arglists '([mutex]) :sdl/c "SDL_UnlockMutex" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnlockMutex" [:pointer] :void)

(ffi/defcfn destroy-mutex
  "void SDL_DestroyMutex(SDL_Mutex * mutex)"
  {:arglists '([mutex]) :sdl/c "SDL_DestroyMutex" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyMutex" [:pointer] :void)

(ffi/defcfn create-rw-lock
  "SDL_RWLock * SDL_CreateRWLock(void)"
  {:arglists '([]) :sdl/c "SDL_CreateRWLock" :sdl/args [] :sdl/ret :pointer}
  "SDL_CreateRWLock" [] :pointer)

(ffi/defcfn lock-rw-lock-for-reading
  "void SDL_LockRWLockForReading(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_LockRWLockForReading" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_LockRWLockForReading" [:pointer] :void :blocking)

(ffi/defcfn lock-rw-lock-for-writing
  "void SDL_LockRWLockForWriting(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_LockRWLockForWriting" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_LockRWLockForWriting" [:pointer] :void :blocking)

(ffi/defcfn try-lock-rw-lock-for-reading
  "bool SDL_TryLockRWLockForReading(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_TryLockRWLockForReading" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TryLockRWLockForReading" [:pointer] :bool)

(ffi/defcfn try-lock-rw-lock-for-writing
  "bool SDL_TryLockRWLockForWriting(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_TryLockRWLockForWriting" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TryLockRWLockForWriting" [:pointer] :bool)

(ffi/defcfn unlock-rw-lock
  "void SDL_UnlockRWLock(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_UnlockRWLock" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnlockRWLock" [:pointer] :void)

(ffi/defcfn destroy-rw-lock
  "void SDL_DestroyRWLock(SDL_RWLock * rwlock)"
  {:arglists '([rwlock]) :sdl/c "SDL_DestroyRWLock" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyRWLock" [:pointer] :void)

(ffi/defcfn create-semaphore
  "SDL_Semaphore * SDL_CreateSemaphore(Uint32 initial_value)"
  {:arglists '([initial-value]) :sdl/c "SDL_CreateSemaphore" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_CreateSemaphore" [:uint32] :pointer)

(ffi/defcfn destroy-semaphore
  "void SDL_DestroySemaphore(SDL_Semaphore * sem)"
  {:arglists '([sem]) :sdl/c "SDL_DestroySemaphore" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroySemaphore" [:pointer] :void)

(ffi/defcfn wait-semaphore
  "void SDL_WaitSemaphore(SDL_Semaphore * sem)"
  {:arglists '([sem]) :sdl/c "SDL_WaitSemaphore" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_WaitSemaphore" [:pointer] :void :blocking)

(ffi/defcfn try-wait-semaphore
  "bool SDL_TryWaitSemaphore(SDL_Semaphore * sem)"
  {:arglists '([sem]) :sdl/c "SDL_TryWaitSemaphore" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_TryWaitSemaphore" [:pointer] :bool)

(ffi/defcfn wait-semaphore-timeout
  "bool SDL_WaitSemaphoreTimeout(SDL_Semaphore * sem, Sint32 timeoutMS)"
  {:arglists '([sem timeout-ms]) :sdl/c "SDL_WaitSemaphoreTimeout" :sdl/args [:pointer :int32] :sdl/ret :bool}
  "SDL_WaitSemaphoreTimeout" [:pointer :int32] :bool :blocking)

(ffi/defcfn signal-semaphore
  "void SDL_SignalSemaphore(SDL_Semaphore * sem)"
  {:arglists '([sem]) :sdl/c "SDL_SignalSemaphore" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_SignalSemaphore" [:pointer] :void)

(ffi/defcfn get-semaphore-value
  "Uint32 SDL_GetSemaphoreValue(SDL_Semaphore * sem)"
  {:arglists '([sem]) :sdl/c "SDL_GetSemaphoreValue" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetSemaphoreValue" [:pointer] :uint32)

(ffi/defcfn create-condition
  "SDL_Condition * SDL_CreateCondition(void)"
  {:arglists '([]) :sdl/c "SDL_CreateCondition" :sdl/args [] :sdl/ret :pointer}
  "SDL_CreateCondition" [] :pointer)

(ffi/defcfn destroy-condition
  "void SDL_DestroyCondition(SDL_Condition * cond)"
  {:arglists '([cond]) :sdl/c "SDL_DestroyCondition" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyCondition" [:pointer] :void)

(ffi/defcfn signal-condition
  "void SDL_SignalCondition(SDL_Condition * cond)"
  {:arglists '([cond]) :sdl/c "SDL_SignalCondition" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_SignalCondition" [:pointer] :void)

(ffi/defcfn broadcast-condition
  "void SDL_BroadcastCondition(SDL_Condition * cond)"
  {:arglists '([cond]) :sdl/c "SDL_BroadcastCondition" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_BroadcastCondition" [:pointer] :void)

(ffi/defcfn wait-condition
  "void SDL_WaitCondition(SDL_Condition * cond, SDL_Mutex * mutex)"
  {:arglists '([cond mutex]) :sdl/c "SDL_WaitCondition" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_WaitCondition" [:pointer :pointer] :void :blocking)

(ffi/defcfn wait-condition-timeout
  "bool SDL_WaitConditionTimeout(SDL_Condition * cond, SDL_Mutex * mutex, Sint32 timeoutMS)"
  {:arglists '([cond mutex timeout-ms]) :sdl/c "SDL_WaitConditionTimeout" :sdl/args [:pointer :pointer :int32] :sdl/ret :bool}
  "SDL_WaitConditionTimeout" [:pointer :pointer :int32] :bool :blocking)

(ffi/defcfn should-init
  "bool SDL_ShouldInit(SDL_InitState * state)"
  {:arglists '([state]) :sdl/c "SDL_ShouldInit" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ShouldInit" [:pointer] :bool)

(ffi/defcfn should-quit
  "bool SDL_ShouldQuit(SDL_InitState * state)"
  {:arglists '([state]) :sdl/c "SDL_ShouldQuit" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_ShouldQuit" [:pointer] :bool)

(ffi/defcfn set-initialized
  "void SDL_SetInitialized(SDL_InitState * state, bool initialized)"
  {:arglists '([state initialized]) :sdl/c "SDL_SetInitialized" :sdl/args [:pointer :bool] :sdl/ret :void}
  "SDL_SetInitialized" [:pointer :bool] :void)
