;; GENERATED by tools/gen.clj from the SDL_net headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from SDL_net, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.net
  "Raw bindings for SDL_net.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its NET_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def datagram
  "ffi/layout of NET_Datagram."
  (ffi/layout [:struct [[:addr :pointer] [:port :uint16] [:buf :pointer] [:buflen :int]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn version
  "int NET_Version(void)"
  {:arglists '([]) :sdl/c "NET_Version" :sdl/args [] :sdl/ret :int}
  "NET_Version" [] :int)

(ffi/defcfn init
  "bool NET_Init(void)"
  {:arglists '([]) :sdl/c "NET_Init" :sdl/args [] :sdl/ret :bool}
  "NET_Init" [] :bool)

(ffi/defcfn quit
  "void NET_Quit(void)"
  {:arglists '([]) :sdl/c "NET_Quit" :sdl/args [] :sdl/ret :void}
  "NET_Quit" [] :void)

(ffi/defcfn resolve-hostname
  "NET_Address * NET_ResolveHostname(const char * host)"
  {:arglists '([host]) :sdl/c "NET_ResolveHostname" :sdl/args [:string] :sdl/ret :pointer}
  "NET_ResolveHostname" [:string] :pointer)

(ffi/defcfn wait-until-resolved
  "NET_Status NET_WaitUntilResolved(NET_Address * address, Sint32 timeout)"
  {:arglists '([address timeout]) :sdl/c "NET_WaitUntilResolved" :sdl/args [:pointer :int32] :sdl/ret :int}
  "NET_WaitUntilResolved" [:pointer :int32] :int :blocking)

(ffi/defcfn get-address-status
  "NET_Status NET_GetAddressStatus(NET_Address * address)"
  {:arglists '([address]) :sdl/c "NET_GetAddressStatus" :sdl/args [:pointer] :sdl/ret :int}
  "NET_GetAddressStatus" [:pointer] :int)

(ffi/defcfn get-address-string
  "const char * NET_GetAddressString(NET_Address * address)"
  {:arglists '([address]) :sdl/c "NET_GetAddressString" :sdl/args [:pointer] :sdl/ret :string}
  "NET_GetAddressString" [:pointer] :string)

(ffi/defcfn get-address-bytes
  "const void * NET_GetAddressBytes(NET_Address * address, int * num_bytes)"
  {:arglists '([address num-bytes]) :sdl/c "NET_GetAddressBytes" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "NET_GetAddressBytes" [:pointer :pointer] :pointer)

(ffi/defcfn ref-address
  "NET_Address * NET_RefAddress(NET_Address * address)"
  {:arglists '([address]) :sdl/c "NET_RefAddress" :sdl/args [:pointer] :sdl/ret :pointer}
  "NET_RefAddress" [:pointer] :pointer)

(ffi/defcfn unref-address
  "void NET_UnrefAddress(NET_Address * address)"
  {:arglists '([address]) :sdl/c "NET_UnrefAddress" :sdl/args [:pointer] :sdl/ret :void}
  "NET_UnrefAddress" [:pointer] :void)

(ffi/defcfn simulate-address-resolution-loss
  "void NET_SimulateAddressResolutionLoss(int percent_loss)"
  {:arglists '([percent-loss]) :sdl/c "NET_SimulateAddressResolutionLoss" :sdl/args [:int] :sdl/ret :void}
  "NET_SimulateAddressResolutionLoss" [:int] :void)

(ffi/defcfn compare-addresses
  "int NET_CompareAddresses(const NET_Address * a, const NET_Address * b)"
  {:arglists '([a b]) :sdl/c "NET_CompareAddresses" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "NET_CompareAddresses" [:pointer :pointer] :int)

(ffi/defcfn get-local-addresses
  "NET_Address ** NET_GetLocalAddresses(int * num_addresses)"
  {:arglists '([num-addresses]) :sdl/c "NET_GetLocalAddresses" :sdl/args [:pointer] :sdl/ret :pointer}
  "NET_GetLocalAddresses" [:pointer] :pointer)

(ffi/defcfn free-local-addresses
  "void NET_FreeLocalAddresses(NET_Address ** addresses)"
  {:arglists '([addresses]) :sdl/c "NET_FreeLocalAddresses" :sdl/args [:pointer] :sdl/ret :void}
  "NET_FreeLocalAddresses" [:pointer] :void)

(ffi/defcfn create-client
  "NET_StreamSocket * NET_CreateClient(NET_Address * address, Uint16 port, SDL_PropertiesID props)"
  {:arglists '([address port props]) :sdl/c "NET_CreateClient" :sdl/args [:pointer :uint16 :uint32] :sdl/ret :pointer}
  "NET_CreateClient" [:pointer :uint16 :uint32] :pointer)

(ffi/defcfn wait-until-connected
  "NET_Status NET_WaitUntilConnected(NET_StreamSocket * sock, Sint32 timeout)"
  {:arglists '([sock timeout]) :sdl/c "NET_WaitUntilConnected" :sdl/args [:pointer :int32] :sdl/ret :int}
  "NET_WaitUntilConnected" [:pointer :int32] :int :blocking)

(ffi/defcfn create-server
  "NET_Server * NET_CreateServer(NET_Address * addr, Uint16 port, SDL_PropertiesID props)"
  {:arglists '([addr port props]) :sdl/c "NET_CreateServer" :sdl/args [:pointer :uint16 :uint32] :sdl/ret :pointer}
  "NET_CreateServer" [:pointer :uint16 :uint32] :pointer)

(ffi/defcfn accept-client
  "bool NET_AcceptClient(NET_Server * server, NET_StreamSocket ** client_stream)"
  {:arglists '([server client-stream]) :sdl/c "NET_AcceptClient" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "NET_AcceptClient" [:pointer :pointer] :bool)

(ffi/defcfn destroy-server
  "void NET_DestroyServer(NET_Server * server)"
  {:arglists '([server]) :sdl/c "NET_DestroyServer" :sdl/args [:pointer] :sdl/ret :void}
  "NET_DestroyServer" [:pointer] :void)

(ffi/defcfn get-stream-socket-address
  "NET_Address * NET_GetStreamSocketAddress(NET_StreamSocket * sock)"
  {:arglists '([sock]) :sdl/c "NET_GetStreamSocketAddress" :sdl/args [:pointer] :sdl/ret :pointer}
  "NET_GetStreamSocketAddress" [:pointer] :pointer)

(ffi/defcfn get-connection-status
  "NET_Status NET_GetConnectionStatus(NET_StreamSocket * sock)"
  {:arglists '([sock]) :sdl/c "NET_GetConnectionStatus" :sdl/args [:pointer] :sdl/ret :int}
  "NET_GetConnectionStatus" [:pointer] :int)

(ffi/defcfn write-to-stream-socket
  "bool NET_WriteToStreamSocket(NET_StreamSocket * sock, const void * buf, int buflen)"
  {:arglists '([sock buf buflen]) :sdl/c "NET_WriteToStreamSocket" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "NET_WriteToStreamSocket" [:pointer :pointer :int] :bool)

(ffi/defcfn get-stream-socket-pending-writes
  "int NET_GetStreamSocketPendingWrites(NET_StreamSocket * sock)"
  {:arglists '([sock]) :sdl/c "NET_GetStreamSocketPendingWrites" :sdl/args [:pointer] :sdl/ret :int}
  "NET_GetStreamSocketPendingWrites" [:pointer] :int)

(ffi/defcfn wait-until-stream-socket-drained
  "int NET_WaitUntilStreamSocketDrained(NET_StreamSocket * sock, Sint32 timeout)"
  {:arglists '([sock timeout]) :sdl/c "NET_WaitUntilStreamSocketDrained" :sdl/args [:pointer :int32] :sdl/ret :int}
  "NET_WaitUntilStreamSocketDrained" [:pointer :int32] :int :blocking)

(ffi/defcfn read-from-stream-socket
  "int NET_ReadFromStreamSocket(NET_StreamSocket * sock, void * buf, int buflen)"
  {:arglists '([sock buf buflen]) :sdl/c "NET_ReadFromStreamSocket" :sdl/args [:pointer :pointer :int] :sdl/ret :int}
  "NET_ReadFromStreamSocket" [:pointer :pointer :int] :int)

(ffi/defcfn simulate-stream-packet-loss
  "void NET_SimulateStreamPacketLoss(NET_StreamSocket * sock, int percent_loss)"
  {:arglists '([sock percent-loss]) :sdl/c "NET_SimulateStreamPacketLoss" :sdl/args [:pointer :int] :sdl/ret :void}
  "NET_SimulateStreamPacketLoss" [:pointer :int] :void)

(ffi/defcfn destroy-stream-socket
  "void NET_DestroyStreamSocket(NET_StreamSocket * sock)"
  {:arglists '([sock]) :sdl/c "NET_DestroyStreamSocket" :sdl/args [:pointer] :sdl/ret :void}
  "NET_DestroyStreamSocket" [:pointer] :void)

(ffi/defcfn create-datagram-socket
  "NET_DatagramSocket * NET_CreateDatagramSocket(NET_Address * addr, Uint16 port, SDL_PropertiesID props)"
  {:arglists '([addr port props]) :sdl/c "NET_CreateDatagramSocket" :sdl/args [:pointer :uint16 :uint32] :sdl/ret :pointer}
  "NET_CreateDatagramSocket" [:pointer :uint16 :uint32] :pointer)

(ffi/defcfn send-datagram
  "bool NET_SendDatagram(NET_DatagramSocket * sock, NET_Address * address, Uint16 port, const void * buf, int buflen)"
  {:arglists '([sock address port buf buflen]) :sdl/c "NET_SendDatagram" :sdl/args [:pointer :pointer :uint16 :pointer :int] :sdl/ret :bool}
  "NET_SendDatagram" [:pointer :pointer :uint16 :pointer :int] :bool)

(ffi/defcfn receive-datagram
  "bool NET_ReceiveDatagram(NET_DatagramSocket * sock, NET_Datagram ** dgram)"
  {:arglists '([sock dgram]) :sdl/c "NET_ReceiveDatagram" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "NET_ReceiveDatagram" [:pointer :pointer] :bool)

(ffi/defcfn destroy-datagram
  "void NET_DestroyDatagram(NET_Datagram * dgram)"
  {:arglists '([dgram]) :sdl/c "NET_DestroyDatagram" :sdl/args [:pointer] :sdl/ret :void}
  "NET_DestroyDatagram" [:pointer] :void)

(ffi/defcfn simulate-datagram-packet-loss
  "void NET_SimulateDatagramPacketLoss(NET_DatagramSocket * sock, int percent_loss)"
  {:arglists '([sock percent-loss]) :sdl/c "NET_SimulateDatagramPacketLoss" :sdl/args [:pointer :int] :sdl/ret :void}
  "NET_SimulateDatagramPacketLoss" [:pointer :int] :void)

(ffi/defcfn destroy-datagram-socket
  "void NET_DestroyDatagramSocket(NET_DatagramSocket * sock)"
  {:arglists '([sock]) :sdl/c "NET_DestroyDatagramSocket" :sdl/args [:pointer] :sdl/ret :void}
  "NET_DestroyDatagramSocket" [:pointer] :void)

(ffi/defcfn wait-until-input-available
  "int NET_WaitUntilInputAvailable(void ** vsockets, int numsockets, Sint32 timeout)"
  {:arglists '([vsockets numsockets timeout]) :sdl/c "NET_WaitUntilInputAvailable" :sdl/args [:pointer :int :int32] :sdl/ret :int}
  "NET_WaitUntilInputAvailable" [:pointer :int :int32] :int :blocking)
