;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.rect
  "Raw bindings for SDL_rect.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def point
  "ffi/layout of SDL_Point."
  (ffi/layout [:struct [[:x :int] [:y :int]]]))

(def fpoint
  "ffi/layout of SDL_FPoint."
  (ffi/layout [:struct [[:x :float] [:y :float]]]))

(def rect
  "ffi/layout of SDL_Rect."
  (ffi/layout [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]))

(def frect
  "ffi/layout of SDL_FRect."
  (ffi/layout [:struct [[:x :float] [:y :float] [:w :float] [:h :float]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn has-rect-intersection
  "bool SDL_HasRectIntersection(const SDL_Rect * A, const SDL_Rect * B)"
  {:arglists '([a b]) :sdl/c "SDL_HasRectIntersection" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_HasRectIntersection" [:pointer :pointer] :bool)

(ffi/defcfn get-rect-intersection
  "bool SDL_GetRectIntersection(const SDL_Rect * A, const SDL_Rect * B, SDL_Rect * result)"
  {:arglists '([a b result]) :sdl/c "SDL_GetRectIntersection" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectIntersection" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-rect-union
  "bool SDL_GetRectUnion(const SDL_Rect * A, const SDL_Rect * B, SDL_Rect * result)"
  {:arglists '([a b result]) :sdl/c "SDL_GetRectUnion" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectUnion" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-rect-enclosing-points
  "bool SDL_GetRectEnclosingPoints(const SDL_Point * points, int count, const SDL_Rect * clip, SDL_Rect * result)"
  {:arglists '([points count clip result]) :sdl/c "SDL_GetRectEnclosingPoints" :sdl/args [:pointer :int :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectEnclosingPoints" [:pointer :int :pointer :pointer] :bool)

(ffi/defcfn get-rect-and-line-intersection
  "bool SDL_GetRectAndLineIntersection(const SDL_Rect * rect, int * X1, int * Y1, int * X2, int * Y2)"
  {:arglists '([rect x1 y1 x2 y2]) :sdl/c "SDL_GetRectAndLineIntersection" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectAndLineIntersection" [:pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn has-rect-intersection-float
  "bool SDL_HasRectIntersectionFloat(const SDL_FRect * A, const SDL_FRect * B)"
  {:arglists '([a b]) :sdl/c "SDL_HasRectIntersectionFloat" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_HasRectIntersectionFloat" [:pointer :pointer] :bool)

(ffi/defcfn get-rect-intersection-float
  "bool SDL_GetRectIntersectionFloat(const SDL_FRect * A, const SDL_FRect * B, SDL_FRect * result)"
  {:arglists '([a b result]) :sdl/c "SDL_GetRectIntersectionFloat" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectIntersectionFloat" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-rect-union-float
  "bool SDL_GetRectUnionFloat(const SDL_FRect * A, const SDL_FRect * B, SDL_FRect * result)"
  {:arglists '([a b result]) :sdl/c "SDL_GetRectUnionFloat" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectUnionFloat" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-rect-enclosing-points-float
  "bool SDL_GetRectEnclosingPointsFloat(const SDL_FPoint * points, int count, const SDL_FRect * clip, SDL_FRect * result)"
  {:arglists '([points count clip result]) :sdl/c "SDL_GetRectEnclosingPointsFloat" :sdl/args [:pointer :int :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectEnclosingPointsFloat" [:pointer :int :pointer :pointer] :bool)

(ffi/defcfn get-rect-and-line-intersection-float
  "bool SDL_GetRectAndLineIntersectionFloat(const SDL_FRect * rect, float * X1, float * Y1, float * X2, float * Y2)"
  {:arglists '([rect x1 y1 x2 y2]) :sdl/c "SDL_GetRectAndLineIntersectionFloat" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRectAndLineIntersectionFloat" [:pointer :pointer :pointer :pointer :pointer] :bool)
