;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.render
  "Raw bindings for SDL_render.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def vertex
  "ffi/layout of SDL_Vertex."
  (ffi/layout [:struct [[:position [:struct [[:x :float] [:y :float]]]] [:color [:struct [[:r :float] [:g :float] [:b :float] [:a :float]]]] [:tex-coord [:struct [[:x :float] [:y :float]]]]]]))

(def gpu-render-state-create-info
  "ffi/layout of SDL_GPURenderStateCreateInfo."
  (ffi/layout [:struct [[:fragment-shader :pointer] [:num-sampler-bindings :int32] [:sampler-bindings :pointer] [:num-storage-textures :int32] [:storage-textures :pointer] [:num-storage-buffers :int32] [:storage-buffers :pointer] [:props :uint32]]]))

(def texture
  "ffi/layout of SDL_Texture."
  (ffi/layout [:struct [[:format :int] [:w :int] [:h :int] [:refcount :int]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-num-render-drivers
  "int SDL_GetNumRenderDrivers(void)"
  {:arglists '([]) :sdl/c "SDL_GetNumRenderDrivers" :sdl/args [] :sdl/ret :int}
  "SDL_GetNumRenderDrivers" [] :int)

(ffi/defcfn get-render-driver
  "const char * SDL_GetRenderDriver(int index)"
  {:arglists '([index]) :sdl/c "SDL_GetRenderDriver" :sdl/args [:int] :sdl/ret :string}
  "SDL_GetRenderDriver" [:int] :string)

(ffi/defcfn create-window-and-renderer
  "bool SDL_CreateWindowAndRenderer(const char * title, int width, int height, SDL_WindowFlags window_flags, SDL_Window ** window, SDL_Renderer ** renderer)"
  {:arglists '([title width height window-flags window renderer]) :sdl/c "SDL_CreateWindowAndRenderer" :sdl/args [:string :int :int :uint64 :pointer :pointer] :sdl/ret :bool}
  "SDL_CreateWindowAndRenderer" [:string :int :int :uint64 :pointer :pointer] :bool)

(ffi/defcfn create-renderer
  "SDL_Renderer * SDL_CreateRenderer(SDL_Window * window, const char * name)"
  {:arglists '([window name]) :sdl/c "SDL_CreateRenderer" :sdl/args [:pointer :string] :sdl/ret :pointer}
  "SDL_CreateRenderer" [:pointer :string] :pointer)

(ffi/defcfn create-renderer-with-properties
  "SDL_Renderer * SDL_CreateRendererWithProperties(SDL_PropertiesID props)"
  {:arglists '([props]) :sdl/c "SDL_CreateRendererWithProperties" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_CreateRendererWithProperties" [:uint32] :pointer)

(ffi/defcfn create-gpu-renderer
  "SDL_Renderer * SDL_CreateGPURenderer(SDL_GPUDevice * device, SDL_Window * window)"
  {:arglists '([device window]) :sdl/c "SDL_CreateGPURenderer" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateGPURenderer" [:pointer :pointer] :pointer)

(ffi/defcfn get-gpu-renderer-device
  "SDL_GPUDevice * SDL_GetGPURendererDevice(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetGPURendererDevice" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetGPURendererDevice" [:pointer] :pointer)

(ffi/defcfn create-software-renderer
  "SDL_Renderer * SDL_CreateSoftwareRenderer(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_CreateSoftwareRenderer" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_CreateSoftwareRenderer" [:pointer] :pointer)

(ffi/defcfn get-renderer
  "SDL_Renderer * SDL_GetRenderer(SDL_Window * window)"
  {:arglists '([window]) :sdl/c "SDL_GetRenderer" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRenderer" [:pointer] :pointer)

(ffi/defcfn get-render-window
  "SDL_Window * SDL_GetRenderWindow(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRenderWindow" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRenderWindow" [:pointer] :pointer)

(ffi/defcfn get-renderer-name
  "const char * SDL_GetRendererName(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRendererName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetRendererName" [:pointer] :string)

(ffi/defcfn get-renderer-properties
  "SDL_PropertiesID SDL_GetRendererProperties(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRendererProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetRendererProperties" [:pointer] :uint32)

(ffi/defcfn get-render-output-size
  "bool SDL_GetRenderOutputSize(SDL_Renderer * renderer, int * w, int * h)"
  {:arglists '([renderer w h]) :sdl/c "SDL_GetRenderOutputSize" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderOutputSize" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-current-render-output-size
  "bool SDL_GetCurrentRenderOutputSize(SDL_Renderer * renderer, int * w, int * h)"
  {:arglists '([renderer w h]) :sdl/c "SDL_GetCurrentRenderOutputSize" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetCurrentRenderOutputSize" [:pointer :pointer :pointer] :bool)

(ffi/defcfn create-texture
  "SDL_Texture * SDL_CreateTexture(SDL_Renderer * renderer, SDL_PixelFormat format, SDL_TextureAccess access, int w, int h)"
  {:arglists '([renderer format access w h]) :sdl/c "SDL_CreateTexture" :sdl/args [:pointer :int :int :int :int] :sdl/ret :pointer}
  "SDL_CreateTexture" [:pointer :int :int :int :int] :pointer)

(ffi/defcfn create-texture-from-surface
  "SDL_Texture * SDL_CreateTextureFromSurface(SDL_Renderer * renderer, SDL_Surface * surface)"
  {:arglists '([renderer surface]) :sdl/c "SDL_CreateTextureFromSurface" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateTextureFromSurface" [:pointer :pointer] :pointer)

(ffi/defcfn create-texture-with-properties
  "SDL_Texture * SDL_CreateTextureWithProperties(SDL_Renderer * renderer, SDL_PropertiesID props)"
  {:arglists '([renderer props]) :sdl/c "SDL_CreateTextureWithProperties" :sdl/args [:pointer :uint32] :sdl/ret :pointer}
  "SDL_CreateTextureWithProperties" [:pointer :uint32] :pointer)

(ffi/defcfn get-texture-properties
  "SDL_PropertiesID SDL_GetTextureProperties(SDL_Texture * texture)"
  {:arglists '([texture]) :sdl/c "SDL_GetTextureProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetTextureProperties" [:pointer] :uint32)

(ffi/defcfn get-renderer-from-texture
  "SDL_Renderer * SDL_GetRendererFromTexture(SDL_Texture * texture)"
  {:arglists '([texture]) :sdl/c "SDL_GetRendererFromTexture" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRendererFromTexture" [:pointer] :pointer)

(ffi/defcfn get-texture-size
  "bool SDL_GetTextureSize(SDL_Texture * texture, float * w, float * h)"
  {:arglists '([texture w h]) :sdl/c "SDL_GetTextureSize" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureSize" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-texture-palette
  "bool SDL_SetTexturePalette(SDL_Texture * texture, SDL_Palette * palette)"
  {:arglists '([texture palette]) :sdl/c "SDL_SetTexturePalette" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetTexturePalette" [:pointer :pointer] :bool)

(ffi/defcfn get-texture-palette
  "SDL_Palette * SDL_GetTexturePalette(SDL_Texture * texture)"
  {:arglists '([texture]) :sdl/c "SDL_GetTexturePalette" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTexturePalette" [:pointer] :pointer)

(ffi/defcfn set-texture-color-mod
  "bool SDL_SetTextureColorMod(SDL_Texture * texture, Uint8 r, Uint8 g, Uint8 b)"
  {:arglists '([texture r g b]) :sdl/c "SDL_SetTextureColorMod" :sdl/args [:pointer :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_SetTextureColorMod" [:pointer :uint8 :uint8 :uint8] :bool)

(ffi/defcfn set-texture-color-mod-float
  "bool SDL_SetTextureColorModFloat(SDL_Texture * texture, float r, float g, float b)"
  {:arglists '([texture r g b]) :sdl/c "SDL_SetTextureColorModFloat" :sdl/args [:pointer :float :float :float] :sdl/ret :bool}
  "SDL_SetTextureColorModFloat" [:pointer :float :float :float] :bool)

(ffi/defcfn get-texture-color-mod
  "bool SDL_GetTextureColorMod(SDL_Texture * texture, Uint8 * r, Uint8 * g, Uint8 * b)"
  {:arglists '([texture r g b]) :sdl/c "SDL_GetTextureColorMod" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureColorMod" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn get-texture-color-mod-float
  "bool SDL_GetTextureColorModFloat(SDL_Texture * texture, float * r, float * g, float * b)"
  {:arglists '([texture r g b]) :sdl/c "SDL_GetTextureColorModFloat" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureColorModFloat" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn set-texture-alpha-mod
  "bool SDL_SetTextureAlphaMod(SDL_Texture * texture, Uint8 alpha)"
  {:arglists '([texture alpha]) :sdl/c "SDL_SetTextureAlphaMod" :sdl/args [:pointer :uint8] :sdl/ret :bool}
  "SDL_SetTextureAlphaMod" [:pointer :uint8] :bool)

(ffi/defcfn set-texture-alpha-mod-float
  "bool SDL_SetTextureAlphaModFloat(SDL_Texture * texture, float alpha)"
  {:arglists '([texture alpha]) :sdl/c "SDL_SetTextureAlphaModFloat" :sdl/args [:pointer :float] :sdl/ret :bool}
  "SDL_SetTextureAlphaModFloat" [:pointer :float] :bool)

(ffi/defcfn get-texture-alpha-mod
  "bool SDL_GetTextureAlphaMod(SDL_Texture * texture, Uint8 * alpha)"
  {:arglists '([texture alpha]) :sdl/c "SDL_GetTextureAlphaMod" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureAlphaMod" [:pointer :pointer] :bool)

(ffi/defcfn get-texture-alpha-mod-float
  "bool SDL_GetTextureAlphaModFloat(SDL_Texture * texture, float * alpha)"
  {:arglists '([texture alpha]) :sdl/c "SDL_GetTextureAlphaModFloat" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureAlphaModFloat" [:pointer :pointer] :bool)

(ffi/defcfn set-texture-blend-mode
  "bool SDL_SetTextureBlendMode(SDL_Texture * texture, SDL_BlendMode blendMode)"
  {:arglists '([texture blend-mode]) :sdl/c "SDL_SetTextureBlendMode" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_SetTextureBlendMode" [:pointer :uint32] :bool)

(ffi/defcfn get-texture-blend-mode
  "bool SDL_GetTextureBlendMode(SDL_Texture * texture, SDL_BlendMode * blendMode)"
  {:arglists '([texture blend-mode]) :sdl/c "SDL_GetTextureBlendMode" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureBlendMode" [:pointer :pointer] :bool)

(ffi/defcfn set-texture-scale-mode
  "bool SDL_SetTextureScaleMode(SDL_Texture * texture, SDL_ScaleMode scaleMode)"
  {:arglists '([texture scale-mode]) :sdl/c "SDL_SetTextureScaleMode" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetTextureScaleMode" [:pointer :int] :bool)

(ffi/defcfn get-texture-scale-mode
  "bool SDL_GetTextureScaleMode(SDL_Texture * texture, SDL_ScaleMode * scaleMode)"
  {:arglists '([texture scale-mode]) :sdl/c "SDL_GetTextureScaleMode" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetTextureScaleMode" [:pointer :pointer] :bool)

(ffi/defcfn update-texture
  "bool SDL_UpdateTexture(SDL_Texture * texture, const SDL_Rect * rect, const void * pixels, int pitch)"
  {:arglists '([texture rect pixels pitch]) :sdl/c "SDL_UpdateTexture" :sdl/args [:pointer :pointer :pointer :int] :sdl/ret :bool}
  "SDL_UpdateTexture" [:pointer :pointer :pointer :int] :bool)

(ffi/defcfn update-yuv-texture
  "bool SDL_UpdateYUVTexture(SDL_Texture * texture, const SDL_Rect * rect, const Uint8 * Yplane, int Ypitch, const Uint8 * Uplane, int Upitch, const Uint8 * Vplane, int Vpitch)"
  {:arglists '([texture rect yplane ypitch uplane upitch vplane vpitch]) :sdl/c "SDL_UpdateYUVTexture" :sdl/args [:pointer :pointer :pointer :int :pointer :int :pointer :int] :sdl/ret :bool}
  "SDL_UpdateYUVTexture" [:pointer :pointer :pointer :int :pointer :int :pointer :int] :bool)

(ffi/defcfn update-nv-texture
  "bool SDL_UpdateNVTexture(SDL_Texture * texture, const SDL_Rect * rect, const Uint8 * Yplane, int Ypitch, const Uint8 * UVplane, int UVpitch)"
  {:arglists '([texture rect yplane ypitch u-vplane u-vpitch]) :sdl/c "SDL_UpdateNVTexture" :sdl/args [:pointer :pointer :pointer :int :pointer :int] :sdl/ret :bool}
  "SDL_UpdateNVTexture" [:pointer :pointer :pointer :int :pointer :int] :bool)

(ffi/defcfn lock-texture
  "bool SDL_LockTexture(SDL_Texture * texture, const SDL_Rect * rect, void ** pixels, int * pitch)"
  {:arglists '([texture rect pixels pitch]) :sdl/c "SDL_LockTexture" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_LockTexture" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn lock-texture-to-surface
  "bool SDL_LockTextureToSurface(SDL_Texture * texture, const SDL_Rect * rect, SDL_Surface ** surface)"
  {:arglists '([texture rect surface]) :sdl/c "SDL_LockTextureToSurface" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_LockTextureToSurface" [:pointer :pointer :pointer] :bool)

(ffi/defcfn unlock-texture
  "void SDL_UnlockTexture(SDL_Texture * texture)"
  {:arglists '([texture]) :sdl/c "SDL_UnlockTexture" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnlockTexture" [:pointer] :void)

(ffi/defcfn set-render-target
  "bool SDL_SetRenderTarget(SDL_Renderer * renderer, SDL_Texture * texture)"
  {:arglists '([renderer texture]) :sdl/c "SDL_SetRenderTarget" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetRenderTarget" [:pointer :pointer] :bool)

(ffi/defcfn get-render-target
  "SDL_Texture * SDL_GetRenderTarget(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRenderTarget" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRenderTarget" [:pointer] :pointer)

(ffi/defcfn set-render-logical-presentation
  "bool SDL_SetRenderLogicalPresentation(SDL_Renderer * renderer, int w, int h, SDL_RendererLogicalPresentation mode)"
  {:arglists '([renderer w h mode]) :sdl/c "SDL_SetRenderLogicalPresentation" :sdl/args [:pointer :int :int :int] :sdl/ret :bool}
  "SDL_SetRenderLogicalPresentation" [:pointer :int :int :int] :bool)

(ffi/defcfn get-render-logical-presentation
  "bool SDL_GetRenderLogicalPresentation(SDL_Renderer * renderer, int * w, int * h, SDL_RendererLogicalPresentation * mode)"
  {:arglists '([renderer w h mode]) :sdl/c "SDL_GetRenderLogicalPresentation" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderLogicalPresentation" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn get-render-logical-presentation-rect
  "bool SDL_GetRenderLogicalPresentationRect(SDL_Renderer * renderer, SDL_FRect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_GetRenderLogicalPresentationRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderLogicalPresentationRect" [:pointer :pointer] :bool)

(ffi/defcfn render-coordinates-from-window
  "bool SDL_RenderCoordinatesFromWindow(SDL_Renderer * renderer, float window_x, float window_y, float * x, float * y)"
  {:arglists '([renderer window-x window-y x y]) :sdl/c "SDL_RenderCoordinatesFromWindow" :sdl/args [:pointer :float :float :pointer :pointer] :sdl/ret :bool}
  "SDL_RenderCoordinatesFromWindow" [:pointer :float :float :pointer :pointer] :bool)

(ffi/defcfn render-coordinates-to-window
  "bool SDL_RenderCoordinatesToWindow(SDL_Renderer * renderer, float x, float y, float * window_x, float * window_y)"
  {:arglists '([renderer x y window-x window-y]) :sdl/c "SDL_RenderCoordinatesToWindow" :sdl/args [:pointer :float :float :pointer :pointer] :sdl/ret :bool}
  "SDL_RenderCoordinatesToWindow" [:pointer :float :float :pointer :pointer] :bool)

(ffi/defcfn convert-event-to-render-coordinates
  "bool SDL_ConvertEventToRenderCoordinates(SDL_Renderer * renderer, SDL_Event * event)"
  {:arglists '([renderer event]) :sdl/c "SDL_ConvertEventToRenderCoordinates" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_ConvertEventToRenderCoordinates" [:pointer :pointer] :bool)

(ffi/defcfn set-render-viewport
  "bool SDL_SetRenderViewport(SDL_Renderer * renderer, const SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_SetRenderViewport" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetRenderViewport" [:pointer :pointer] :bool)

(ffi/defcfn get-render-viewport
  "bool SDL_GetRenderViewport(SDL_Renderer * renderer, SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_GetRenderViewport" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderViewport" [:pointer :pointer] :bool)

(ffi/defcfn render-viewport-set
  "bool SDL_RenderViewportSet(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_RenderViewportSet" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_RenderViewportSet" [:pointer] :bool)

(ffi/defcfn get-render-safe-area
  "bool SDL_GetRenderSafeArea(SDL_Renderer * renderer, SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_GetRenderSafeArea" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderSafeArea" [:pointer :pointer] :bool)

(ffi/defcfn set-render-clip-rect
  "bool SDL_SetRenderClipRect(SDL_Renderer * renderer, const SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_SetRenderClipRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetRenderClipRect" [:pointer :pointer] :bool)

(ffi/defcfn get-render-clip-rect
  "bool SDL_GetRenderClipRect(SDL_Renderer * renderer, SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_GetRenderClipRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderClipRect" [:pointer :pointer] :bool)

(ffi/defcfn render-clip-enabled
  "bool SDL_RenderClipEnabled(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_RenderClipEnabled" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_RenderClipEnabled" [:pointer] :bool)

(ffi/defcfn set-render-scale
  "bool SDL_SetRenderScale(SDL_Renderer * renderer, float scaleX, float scaleY)"
  {:arglists '([renderer scale-x scale-y]) :sdl/c "SDL_SetRenderScale" :sdl/args [:pointer :float :float] :sdl/ret :bool}
  "SDL_SetRenderScale" [:pointer :float :float] :bool)

(ffi/defcfn get-render-scale
  "bool SDL_GetRenderScale(SDL_Renderer * renderer, float * scaleX, float * scaleY)"
  {:arglists '([renderer scale-x scale-y]) :sdl/c "SDL_GetRenderScale" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderScale" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-render-draw-color
  "bool SDL_SetRenderDrawColor(SDL_Renderer * renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)"
  {:arglists '([renderer r g b a]) :sdl/c "SDL_SetRenderDrawColor" :sdl/args [:pointer :uint8 :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_SetRenderDrawColor" [:pointer :uint8 :uint8 :uint8 :uint8] :bool)

(ffi/defcfn set-render-draw-color-float
  "bool SDL_SetRenderDrawColorFloat(SDL_Renderer * renderer, float r, float g, float b, float a)"
  {:arglists '([renderer r g b a]) :sdl/c "SDL_SetRenderDrawColorFloat" :sdl/args [:pointer :float :float :float :float] :sdl/ret :bool}
  "SDL_SetRenderDrawColorFloat" [:pointer :float :float :float :float] :bool)

(ffi/defcfn get-render-draw-color
  "bool SDL_GetRenderDrawColor(SDL_Renderer * renderer, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a)"
  {:arglists '([renderer r g b a]) :sdl/c "SDL_GetRenderDrawColor" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderDrawColor" [:pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn get-render-draw-color-float
  "bool SDL_GetRenderDrawColorFloat(SDL_Renderer * renderer, float * r, float * g, float * b, float * a)"
  {:arglists '([renderer r g b a]) :sdl/c "SDL_GetRenderDrawColorFloat" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderDrawColorFloat" [:pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn set-render-color-scale
  "bool SDL_SetRenderColorScale(SDL_Renderer * renderer, float scale)"
  {:arglists '([renderer scale]) :sdl/c "SDL_SetRenderColorScale" :sdl/args [:pointer :float] :sdl/ret :bool}
  "SDL_SetRenderColorScale" [:pointer :float] :bool)

(ffi/defcfn get-render-color-scale
  "bool SDL_GetRenderColorScale(SDL_Renderer * renderer, float * scale)"
  {:arglists '([renderer scale]) :sdl/c "SDL_GetRenderColorScale" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderColorScale" [:pointer :pointer] :bool)

(ffi/defcfn set-render-draw-blend-mode
  "bool SDL_SetRenderDrawBlendMode(SDL_Renderer * renderer, SDL_BlendMode blendMode)"
  {:arglists '([renderer blend-mode]) :sdl/c "SDL_SetRenderDrawBlendMode" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_SetRenderDrawBlendMode" [:pointer :uint32] :bool)

(ffi/defcfn get-render-draw-blend-mode
  "bool SDL_GetRenderDrawBlendMode(SDL_Renderer * renderer, SDL_BlendMode * blendMode)"
  {:arglists '([renderer blend-mode]) :sdl/c "SDL_GetRenderDrawBlendMode" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderDrawBlendMode" [:pointer :pointer] :bool)

(ffi/defcfn render-clear
  "bool SDL_RenderClear(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_RenderClear" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_RenderClear" [:pointer] :bool)

(ffi/defcfn render-point
  "bool SDL_RenderPoint(SDL_Renderer * renderer, float x, float y)"
  {:arglists '([renderer x y]) :sdl/c "SDL_RenderPoint" :sdl/args [:pointer :float :float] :sdl/ret :bool}
  "SDL_RenderPoint" [:pointer :float :float] :bool)

(ffi/defcfn render-points
  "bool SDL_RenderPoints(SDL_Renderer * renderer, const SDL_FPoint * points, int count)"
  {:arglists '([renderer points count]) :sdl/c "SDL_RenderPoints" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_RenderPoints" [:pointer :pointer :int] :bool)

(ffi/defcfn render-line
  "bool SDL_RenderLine(SDL_Renderer * renderer, float x1, float y1, float x2, float y2)"
  {:arglists '([renderer x1 y1 x2 y2]) :sdl/c "SDL_RenderLine" :sdl/args [:pointer :float :float :float :float] :sdl/ret :bool}
  "SDL_RenderLine" [:pointer :float :float :float :float] :bool)

(ffi/defcfn render-lines
  "bool SDL_RenderLines(SDL_Renderer * renderer, const SDL_FPoint * points, int count)"
  {:arglists '([renderer points count]) :sdl/c "SDL_RenderLines" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_RenderLines" [:pointer :pointer :int] :bool)

(ffi/defcfn render-rect
  "bool SDL_RenderRect(SDL_Renderer * renderer, const SDL_FRect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_RenderRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_RenderRect" [:pointer :pointer] :bool)

(ffi/defcfn render-rects
  "bool SDL_RenderRects(SDL_Renderer * renderer, const SDL_FRect * rects, int count)"
  {:arglists '([renderer rects count]) :sdl/c "SDL_RenderRects" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_RenderRects" [:pointer :pointer :int] :bool)

(ffi/defcfn render-fill-rect
  "bool SDL_RenderFillRect(SDL_Renderer * renderer, const SDL_FRect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_RenderFillRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_RenderFillRect" [:pointer :pointer] :bool)

(ffi/defcfn render-fill-rects
  "bool SDL_RenderFillRects(SDL_Renderer * renderer, const SDL_FRect * rects, int count)"
  {:arglists '([renderer rects count]) :sdl/c "SDL_RenderFillRects" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_RenderFillRects" [:pointer :pointer :int] :bool)

(ffi/defcfn render-texture
  "bool SDL_RenderTexture(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect)"
  {:arglists '([renderer texture srcrect dstrect]) :sdl/c "SDL_RenderTexture" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_RenderTexture" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn render-texture-rotated
  "bool SDL_RenderTextureRotated(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect, double angle, const SDL_FPoint * center, SDL_FlipMode flip)"
  {:arglists '([renderer texture srcrect dstrect angle center flip]) :sdl/c "SDL_RenderTextureRotated" :sdl/args [:pointer :pointer :pointer :pointer :double :pointer :int] :sdl/ret :bool}
  "SDL_RenderTextureRotated" [:pointer :pointer :pointer :pointer :double :pointer :int] :bool)

(ffi/defcfn render-texture-affine
  "bool SDL_RenderTextureAffine(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FPoint * origin, const SDL_FPoint * right, const SDL_FPoint * down)"
  {:arglists '([renderer texture srcrect origin right down]) :sdl/c "SDL_RenderTextureAffine" :sdl/args [:pointer :pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_RenderTextureAffine" [:pointer :pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn render-texture-tiled
  "bool SDL_RenderTextureTiled(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float scale, const SDL_FRect * dstrect)"
  {:arglists '([renderer texture srcrect scale dstrect]) :sdl/c "SDL_RenderTextureTiled" :sdl/args [:pointer :pointer :pointer :float :pointer] :sdl/ret :bool}
  "SDL_RenderTextureTiled" [:pointer :pointer :pointer :float :pointer] :bool)

(ffi/defcfn render-texture-9-grid
  "bool SDL_RenderTexture9Grid(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect * dstrect)"
  {:arglists '([renderer texture srcrect left-width right-width top-height bottom-height scale dstrect]) :sdl/c "SDL_RenderTexture9Grid" :sdl/args [:pointer :pointer :pointer :float :float :float :float :float :pointer] :sdl/ret :bool}
  "SDL_RenderTexture9Grid" [:pointer :pointer :pointer :float :float :float :float :float :pointer] :bool)

(ffi/defcfn render-texture-9-grid-tiled
  "bool SDL_RenderTexture9GridTiled(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect * dstrect, float tileScale)"
  {:arglists '([renderer texture srcrect left-width right-width top-height bottom-height scale dstrect tile-scale]) :sdl/c "SDL_RenderTexture9GridTiled" :sdl/args [:pointer :pointer :pointer :float :float :float :float :float :pointer :float] :sdl/ret :bool}
  "SDL_RenderTexture9GridTiled" [:pointer :pointer :pointer :float :float :float :float :float :pointer :float] :bool)

(ffi/defcfn render-geometry
  "bool SDL_RenderGeometry(SDL_Renderer * renderer, SDL_Texture * texture, const SDL_Vertex * vertices, int num_vertices, const int * indices, int num_indices)"
  {:arglists '([renderer texture vertices num-vertices indices num-indices]) :sdl/c "SDL_RenderGeometry" :sdl/args [:pointer :pointer :pointer :int :pointer :int] :sdl/ret :bool}
  "SDL_RenderGeometry" [:pointer :pointer :pointer :int :pointer :int] :bool)

(ffi/defcfn render-geometry-raw
  "bool SDL_RenderGeometryRaw(SDL_Renderer * renderer, SDL_Texture * texture, const float * xy, int xy_stride, const SDL_FColor * color, int color_stride, const float * uv, int uv_stride, int num_vertices, const void * indices, int num_indices, int size_indices)"
  {:arglists '([renderer texture xy xy-stride color color-stride uv uv-stride num-vertices indices num-indices size-indices]) :sdl/c "SDL_RenderGeometryRaw" :sdl/args [:pointer :pointer :pointer :int :pointer :int :pointer :int :int :pointer :int :int] :sdl/ret :bool}
  "SDL_RenderGeometryRaw" [:pointer :pointer :pointer :int :pointer :int :pointer :int :int :pointer :int :int] :bool)

(ffi/defcfn set-render-texture-address-mode
  "bool SDL_SetRenderTextureAddressMode(SDL_Renderer * renderer, SDL_TextureAddressMode u_mode, SDL_TextureAddressMode v_mode)"
  {:arglists '([renderer u-mode v-mode]) :sdl/c "SDL_SetRenderTextureAddressMode" :sdl/args [:pointer :int :int] :sdl/ret :bool}
  "SDL_SetRenderTextureAddressMode" [:pointer :int :int] :bool)

(ffi/defcfn get-render-texture-address-mode
  "bool SDL_GetRenderTextureAddressMode(SDL_Renderer * renderer, SDL_TextureAddressMode * u_mode, SDL_TextureAddressMode * v_mode)"
  {:arglists '([renderer u-mode v-mode]) :sdl/c "SDL_GetRenderTextureAddressMode" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderTextureAddressMode" [:pointer :pointer :pointer] :bool)

(ffi/defcfn render-read-pixels
  "SDL_Surface * SDL_RenderReadPixels(SDL_Renderer * renderer, const SDL_Rect * rect)"
  {:arglists '([renderer rect]) :sdl/c "SDL_RenderReadPixels" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_RenderReadPixels" [:pointer :pointer] :pointer)

(ffi/defcfn render-present
  "bool SDL_RenderPresent(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_RenderPresent" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_RenderPresent" [:pointer] :bool)

(ffi/defcfn destroy-texture
  "void SDL_DestroyTexture(SDL_Texture * texture)"
  {:arglists '([texture]) :sdl/c "SDL_DestroyTexture" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyTexture" [:pointer] :void)

(ffi/defcfn destroy-renderer
  "void SDL_DestroyRenderer(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_DestroyRenderer" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyRenderer" [:pointer] :void)

(ffi/defcfn flush-renderer
  "bool SDL_FlushRenderer(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_FlushRenderer" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_FlushRenderer" [:pointer] :bool)

(ffi/defcfn get-render-metal-layer
  "void * SDL_GetRenderMetalLayer(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRenderMetalLayer" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRenderMetalLayer" [:pointer] :pointer)

(ffi/defcfn get-render-metal-command-encoder
  "void * SDL_GetRenderMetalCommandEncoder(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "SDL_GetRenderMetalCommandEncoder" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetRenderMetalCommandEncoder" [:pointer] :pointer)

(ffi/defcfn add-vulkan-render-semaphores
  "bool SDL_AddVulkanRenderSemaphores(SDL_Renderer * renderer, Uint32 wait_stage_mask, Sint64 wait_semaphore, Sint64 signal_semaphore)"
  {:arglists '([renderer wait-stage-mask wait-semaphore signal-semaphore]) :sdl/c "SDL_AddVulkanRenderSemaphores" :sdl/args [:pointer :uint32 :int64 :int64] :sdl/ret :bool}
  "SDL_AddVulkanRenderSemaphores" [:pointer :uint32 :int64 :int64] :bool)

(ffi/defcfn set-render-vsync
  "bool SDL_SetRenderVSync(SDL_Renderer * renderer, int vsync)"
  {:arglists '([renderer vsync]) :sdl/c "SDL_SetRenderVSync" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetRenderVSync" [:pointer :int] :bool)

(ffi/defcfn get-render-vsync
  "bool SDL_GetRenderVSync(SDL_Renderer * renderer, int * vsync)"
  {:arglists '([renderer vsync]) :sdl/c "SDL_GetRenderVSync" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetRenderVSync" [:pointer :pointer] :bool)

(ffi/defcfn render-debug-text
  "bool SDL_RenderDebugText(SDL_Renderer * renderer, float x, float y, const char * str)"
  {:arglists '([renderer x y str]) :sdl/c "SDL_RenderDebugText" :sdl/args [:pointer :float :float :string] :sdl/ret :bool}
  "SDL_RenderDebugText" [:pointer :float :float :string] :bool)

(ffi/defcfn render-debug-text-format
  "bool SDL_RenderDebugTextFormat(SDL_Renderer * renderer, float x, float y, const char * fmt, ...)"
  {:arglists '([renderer x y fmt & varargs]) :sdl/c "SDL_RenderDebugTextFormat" :sdl/args [:pointer :float :float :string :&] :sdl/ret :bool}
  "SDL_RenderDebugTextFormat" [:pointer :float :float :string :&] :bool)

(ffi/defcfn set-default-texture-scale-mode
  "bool SDL_SetDefaultTextureScaleMode(SDL_Renderer * renderer, SDL_ScaleMode scale_mode)"
  {:arglists '([renderer scale-mode]) :sdl/c "SDL_SetDefaultTextureScaleMode" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetDefaultTextureScaleMode" [:pointer :int] :bool)

(ffi/defcfn get-default-texture-scale-mode
  "bool SDL_GetDefaultTextureScaleMode(SDL_Renderer * renderer, SDL_ScaleMode * scale_mode)"
  {:arglists '([renderer scale-mode]) :sdl/c "SDL_GetDefaultTextureScaleMode" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetDefaultTextureScaleMode" [:pointer :pointer] :bool)

(ffi/defcfn create-gpu-render-state
  "SDL_GPURenderState * SDL_CreateGPURenderState(SDL_Renderer * renderer, const SDL_GPURenderStateCreateInfo * createinfo)"
  {:arglists '([renderer createinfo]) :sdl/c "SDL_CreateGPURenderState" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateGPURenderState" [:pointer :pointer] :pointer)

(ffi/defcfn set-gpu-render-state-fragment-uniforms
  "bool SDL_SetGPURenderStateFragmentUniforms(SDL_GPURenderState * state, Uint32 slot_index, const void * data, Uint32 length)"
  {:arglists '([state slot-index data length]) :sdl/c "SDL_SetGPURenderStateFragmentUniforms" :sdl/args [:pointer :uint32 :pointer :uint32] :sdl/ret :bool}
  "SDL_SetGPURenderStateFragmentUniforms" [:pointer :uint32 :pointer :uint32] :bool)

(ffi/defcfn set-gpu-render-state
  "bool SDL_SetGPURenderState(SDL_Renderer * renderer, SDL_GPURenderState * state)"
  {:arglists '([renderer state]) :sdl/c "SDL_SetGPURenderState" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetGPURenderState" [:pointer :pointer] :bool)

(ffi/defcfn destroy-gpu-render-state
  "void SDL_DestroyGPURenderState(SDL_GPURenderState * state)"
  {:arglists '([state]) :sdl/c "SDL_DestroyGPURenderState" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyGPURenderState" [:pointer] :void)
