;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.sensor
  "Raw bindings for SDL_sensor.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-sensors
  "SDL_SensorID * SDL_GetSensors(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetSensors" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetSensors" [:pointer] :pointer)

(ffi/defcfn get-sensor-name-for-id
  "const char * SDL_GetSensorNameForID(SDL_SensorID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetSensorNameForID" :sdl/args [:uint32] :sdl/ret :string}
  "SDL_GetSensorNameForID" [:uint32] :string)

(ffi/defcfn get-sensor-type-for-id
  "SDL_SensorType SDL_GetSensorTypeForID(SDL_SensorID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetSensorTypeForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetSensorTypeForID" [:uint32] :int)

(ffi/defcfn get-sensor-non-portable-type-for-id
  "int SDL_GetSensorNonPortableTypeForID(SDL_SensorID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetSensorNonPortableTypeForID" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetSensorNonPortableTypeForID" [:uint32] :int)

(ffi/defcfn open-sensor
  "SDL_Sensor * SDL_OpenSensor(SDL_SensorID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_OpenSensor" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_OpenSensor" [:uint32] :pointer)

(ffi/defcfn get-sensor-from-id
  "SDL_Sensor * SDL_GetSensorFromID(SDL_SensorID instance_id)"
  {:arglists '([instance-id]) :sdl/c "SDL_GetSensorFromID" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_GetSensorFromID" [:uint32] :pointer)

(ffi/defcfn get-sensor-properties
  "SDL_PropertiesID SDL_GetSensorProperties(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_GetSensorProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetSensorProperties" [:pointer] :uint32)

(ffi/defcfn get-sensor-name
  "const char * SDL_GetSensorName(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_GetSensorName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetSensorName" [:pointer] :string)

(ffi/defcfn get-sensor-type
  "SDL_SensorType SDL_GetSensorType(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_GetSensorType" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetSensorType" [:pointer] :int)

(ffi/defcfn get-sensor-non-portable-type
  "int SDL_GetSensorNonPortableType(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_GetSensorNonPortableType" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetSensorNonPortableType" [:pointer] :int)

(ffi/defcfn get-sensor-id
  "SDL_SensorID SDL_GetSensorID(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_GetSensorID" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetSensorID" [:pointer] :uint32)

(ffi/defcfn get-sensor-data
  "bool SDL_GetSensorData(SDL_Sensor * sensor, float * data, int num_values)"
  {:arglists '([sensor data num-values]) :sdl/c "SDL_GetSensorData" :sdl/args [:pointer :pointer :int] :sdl/ret :bool}
  "SDL_GetSensorData" [:pointer :pointer :int] :bool)

(ffi/defcfn close-sensor
  "void SDL_CloseSensor(SDL_Sensor * sensor)"
  {:arglists '([sensor]) :sdl/c "SDL_CloseSensor" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_CloseSensor" [:pointer] :void)

(ffi/defcfn update-sensors
  "void SDL_UpdateSensors(void)"
  {:arglists '([]) :sdl/c "SDL_UpdateSensors" :sdl/args [] :sdl/ret :void}
  "SDL_UpdateSensors" [] :void)
