;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.stdinc
  "Raw bindings for SDL_stdinc.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:refer-clojure :exclude [abs rand])
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def alignment-test
  "ffi/layout of SDL_alignment_test."
  (ffi/layout [:struct [[:a :uint8] [:b :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn malloc
  "void * SDL_malloc(size_t size)"
  {:arglists '([size]) :sdl/c "SDL_malloc" :sdl/args [:size_t] :sdl/ret :pointer}
  "SDL_malloc" [:size_t] :pointer)

(ffi/defcfn calloc
  "void * SDL_calloc(size_t nmemb, size_t size)"
  {:arglists '([nmemb size]) :sdl/c "SDL_calloc" :sdl/args [:size_t :size_t] :sdl/ret :pointer}
  "SDL_calloc" [:size_t :size_t] :pointer)

(ffi/defcfn realloc
  "void * SDL_realloc(void * mem, size_t size)"
  {:arglists '([mem size]) :sdl/c "SDL_realloc" :sdl/args [:pointer :size_t] :sdl/ret :pointer}
  "SDL_realloc" [:pointer :size_t] :pointer)

(ffi/defcfn free
  "void SDL_free(void * mem)"
  {:arglists '([mem]) :sdl/c "SDL_free" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_free" [:pointer] :void)

(ffi/defcfn get-original-memory-functions
  "void SDL_GetOriginalMemoryFunctions(SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func)"
  {:arglists '([malloc-func calloc-func realloc-func free-func]) :sdl/c "SDL_GetOriginalMemoryFunctions" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :void}
  "SDL_GetOriginalMemoryFunctions" [:pointer :pointer :pointer :pointer] :void)

(ffi/defcfn get-memory-functions
  "void SDL_GetMemoryFunctions(SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func)"
  {:arglists '([malloc-func calloc-func realloc-func free-func]) :sdl/c "SDL_GetMemoryFunctions" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :void}
  "SDL_GetMemoryFunctions" [:pointer :pointer :pointer :pointer] :void)

(ffi/defcfn set-memory-functions
  "bool SDL_SetMemoryFunctions(SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func)"
  {:arglists '([malloc-func calloc-func realloc-func free-func]) :sdl/c "SDL_SetMemoryFunctions" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_SetMemoryFunctions" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn aligned-alloc
  "void * SDL_aligned_alloc(size_t alignment, size_t size)"
  {:arglists '([alignment size]) :sdl/c "SDL_aligned_alloc" :sdl/args [:size_t :size_t] :sdl/ret :pointer}
  "SDL_aligned_alloc" [:size_t :size_t] :pointer)

(ffi/defcfn aligned-free
  "void SDL_aligned_free(void * mem)"
  {:arglists '([mem]) :sdl/c "SDL_aligned_free" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_aligned_free" [:pointer] :void)

(ffi/defcfn get-num-allocations
  "int SDL_GetNumAllocations(void)"
  {:arglists '([]) :sdl/c "SDL_GetNumAllocations" :sdl/args [] :sdl/ret :int}
  "SDL_GetNumAllocations" [] :int)

(ffi/defcfn get-environment
  "SDL_Environment * SDL_GetEnvironment(void)"
  {:arglists '([]) :sdl/c "SDL_GetEnvironment" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetEnvironment" [] :pointer)

(ffi/defcfn create-environment
  "SDL_Environment * SDL_CreateEnvironment(bool populated)"
  {:arglists '([populated]) :sdl/c "SDL_CreateEnvironment" :sdl/args [:bool] :sdl/ret :pointer}
  "SDL_CreateEnvironment" [:bool] :pointer)

(ffi/defcfn get-environment-variable
  "const char * SDL_GetEnvironmentVariable(SDL_Environment * env, const char * name)"
  {:arglists '([env name]) :sdl/c "SDL_GetEnvironmentVariable" :sdl/args [:pointer :string] :sdl/ret :string}
  "SDL_GetEnvironmentVariable" [:pointer :string] :string)

(ffi/defcfn get-environment-variables
  "char ** SDL_GetEnvironmentVariables(SDL_Environment * env)"
  {:arglists '([env]) :sdl/c "SDL_GetEnvironmentVariables" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetEnvironmentVariables" [:pointer] :pointer)

(ffi/defcfn set-environment-variable
  "bool SDL_SetEnvironmentVariable(SDL_Environment * env, const char * name, const char * value, bool overwrite)"
  {:arglists '([env name value overwrite]) :sdl/c "SDL_SetEnvironmentVariable" :sdl/args [:pointer :string :string :bool] :sdl/ret :bool}
  "SDL_SetEnvironmentVariable" [:pointer :string :string :bool] :bool)

(ffi/defcfn unset-environment-variable
  "bool SDL_UnsetEnvironmentVariable(SDL_Environment * env, const char * name)"
  {:arglists '([env name]) :sdl/c "SDL_UnsetEnvironmentVariable" :sdl/args [:pointer :string] :sdl/ret :bool}
  "SDL_UnsetEnvironmentVariable" [:pointer :string] :bool)

(ffi/defcfn destroy-environment
  "void SDL_DestroyEnvironment(SDL_Environment * env)"
  {:arglists '([env]) :sdl/c "SDL_DestroyEnvironment" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyEnvironment" [:pointer] :void)

(ffi/defcfn getenv
  "const char * SDL_getenv(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_getenv" :sdl/args [:string] :sdl/ret :string}
  "SDL_getenv" [:string] :string)

(ffi/defcfn getenv-unsafe
  "const char * SDL_getenv_unsafe(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_getenv_unsafe" :sdl/args [:string] :sdl/ret :string}
  "SDL_getenv_unsafe" [:string] :string)

(ffi/defcfn setenv-unsafe
  "int SDL_setenv_unsafe(const char * name, const char * value, int overwrite)"
  {:arglists '([name value overwrite]) :sdl/c "SDL_setenv_unsafe" :sdl/args [:string :string :int] :sdl/ret :int}
  "SDL_setenv_unsafe" [:string :string :int] :int)

(ffi/defcfn unsetenv-unsafe
  "int SDL_unsetenv_unsafe(const char * name)"
  {:arglists '([name]) :sdl/c "SDL_unsetenv_unsafe" :sdl/args [:string] :sdl/ret :int}
  "SDL_unsetenv_unsafe" [:string] :int)

(ffi/defcfn qsort
  "void SDL_qsort(void * base, size_t nmemb, size_t size, SDL_CompareCallback compare)"
  {:arglists '([base nmemb size compare]) :sdl/c "SDL_qsort" :sdl/args [:pointer :size_t :size_t :pointer] :sdl/ret :void}
  "SDL_qsort" [:pointer :size_t :size_t :pointer] :void)

(ffi/defcfn bsearch
  "void * SDL_bsearch(const void * key, const void * base, size_t nmemb, size_t size, SDL_CompareCallback compare)"
  {:arglists '([key base nmemb size compare]) :sdl/c "SDL_bsearch" :sdl/args [:pointer :pointer :size_t :size_t :pointer] :sdl/ret :pointer}
  "SDL_bsearch" [:pointer :pointer :size_t :size_t :pointer] :pointer)

(ffi/defcfn qsort-r
  "void SDL_qsort_r(void * base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void * userdata)"
  {:arglists '([base nmemb size compare userdata]) :sdl/c "SDL_qsort_r" :sdl/args [:pointer :size_t :size_t :pointer :pointer] :sdl/ret :void}
  "SDL_qsort_r" [:pointer :size_t :size_t :pointer :pointer] :void)

(ffi/defcfn bsearch-r
  "void * SDL_bsearch_r(const void * key, const void * base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void * userdata)"
  {:arglists '([key base nmemb size compare userdata]) :sdl/c "SDL_bsearch_r" :sdl/args [:pointer :pointer :size_t :size_t :pointer :pointer] :sdl/ret :pointer}
  "SDL_bsearch_r" [:pointer :pointer :size_t :size_t :pointer :pointer] :pointer)

(ffi/defcfn abs
  "int SDL_abs(int x)"
  {:arglists '([x]) :sdl/c "SDL_abs" :sdl/args [:int] :sdl/ret :int}
  "SDL_abs" [:int] :int)

(ffi/defcfn isalpha
  "int SDL_isalpha(int x)"
  {:arglists '([x]) :sdl/c "SDL_isalpha" :sdl/args [:int] :sdl/ret :int}
  "SDL_isalpha" [:int] :int)

(ffi/defcfn isalnum
  "int SDL_isalnum(int x)"
  {:arglists '([x]) :sdl/c "SDL_isalnum" :sdl/args [:int] :sdl/ret :int}
  "SDL_isalnum" [:int] :int)

(ffi/defcfn isblank
  "int SDL_isblank(int x)"
  {:arglists '([x]) :sdl/c "SDL_isblank" :sdl/args [:int] :sdl/ret :int}
  "SDL_isblank" [:int] :int)

(ffi/defcfn iscntrl
  "int SDL_iscntrl(int x)"
  {:arglists '([x]) :sdl/c "SDL_iscntrl" :sdl/args [:int] :sdl/ret :int}
  "SDL_iscntrl" [:int] :int)

(ffi/defcfn isdigit
  "int SDL_isdigit(int x)"
  {:arglists '([x]) :sdl/c "SDL_isdigit" :sdl/args [:int] :sdl/ret :int}
  "SDL_isdigit" [:int] :int)

(ffi/defcfn isxdigit
  "int SDL_isxdigit(int x)"
  {:arglists '([x]) :sdl/c "SDL_isxdigit" :sdl/args [:int] :sdl/ret :int}
  "SDL_isxdigit" [:int] :int)

(ffi/defcfn ispunct
  "int SDL_ispunct(int x)"
  {:arglists '([x]) :sdl/c "SDL_ispunct" :sdl/args [:int] :sdl/ret :int}
  "SDL_ispunct" [:int] :int)

(ffi/defcfn isspace
  "int SDL_isspace(int x)"
  {:arglists '([x]) :sdl/c "SDL_isspace" :sdl/args [:int] :sdl/ret :int}
  "SDL_isspace" [:int] :int)

(ffi/defcfn isupper
  "int SDL_isupper(int x)"
  {:arglists '([x]) :sdl/c "SDL_isupper" :sdl/args [:int] :sdl/ret :int}
  "SDL_isupper" [:int] :int)

(ffi/defcfn islower
  "int SDL_islower(int x)"
  {:arglists '([x]) :sdl/c "SDL_islower" :sdl/args [:int] :sdl/ret :int}
  "SDL_islower" [:int] :int)

(ffi/defcfn isprint
  "int SDL_isprint(int x)"
  {:arglists '([x]) :sdl/c "SDL_isprint" :sdl/args [:int] :sdl/ret :int}
  "SDL_isprint" [:int] :int)

(ffi/defcfn isgraph
  "int SDL_isgraph(int x)"
  {:arglists '([x]) :sdl/c "SDL_isgraph" :sdl/args [:int] :sdl/ret :int}
  "SDL_isgraph" [:int] :int)

(ffi/defcfn toupper
  "int SDL_toupper(int x)"
  {:arglists '([x]) :sdl/c "SDL_toupper" :sdl/args [:int] :sdl/ret :int}
  "SDL_toupper" [:int] :int)

(ffi/defcfn tolower
  "int SDL_tolower(int x)"
  {:arglists '([x]) :sdl/c "SDL_tolower" :sdl/args [:int] :sdl/ret :int}
  "SDL_tolower" [:int] :int)

(ffi/defcfn crc16
  "Uint16 SDL_crc16(Uint16 crc, const void * data, size_t len)"
  {:arglists '([crc data len]) :sdl/c "SDL_crc16" :sdl/args [:uint16 :pointer :size_t] :sdl/ret :uint16}
  "SDL_crc16" [:uint16 :pointer :size_t] :uint16)

(ffi/defcfn crc32
  "Uint32 SDL_crc32(Uint32 crc, const void * data, size_t len)"
  {:arglists '([crc data len]) :sdl/c "SDL_crc32" :sdl/args [:uint32 :pointer :size_t] :sdl/ret :uint32}
  "SDL_crc32" [:uint32 :pointer :size_t] :uint32)

(ffi/defcfn murmur3-32
  "Uint32 SDL_murmur3_32(const void * data, size_t len, Uint32 seed)"
  {:arglists '([data len seed]) :sdl/c "SDL_murmur3_32" :sdl/args [:pointer :size_t :uint32] :sdl/ret :uint32}
  "SDL_murmur3_32" [:pointer :size_t :uint32] :uint32)

(ffi/defcfn memcpy
  "void * SDL_memcpy(void * dst, const void * src, size_t len)"
  {:arglists '([dst src len]) :sdl/c "SDL_memcpy" :sdl/args [:pointer :pointer :size_t] :sdl/ret :pointer}
  "SDL_memcpy" [:pointer :pointer :size_t] :pointer)

(ffi/defcfn memmove
  "void * SDL_memmove(void * dst, const void * src, size_t len)"
  {:arglists '([dst src len]) :sdl/c "SDL_memmove" :sdl/args [:pointer :pointer :size_t] :sdl/ret :pointer}
  "SDL_memmove" [:pointer :pointer :size_t] :pointer)

(ffi/defcfn memset
  "void * SDL_memset(void * dst, int c, size_t len)"
  {:arglists '([dst c len]) :sdl/c "SDL_memset" :sdl/args [:pointer :int :size_t] :sdl/ret :pointer}
  "SDL_memset" [:pointer :int :size_t] :pointer)

(ffi/defcfn memset4
  "void * SDL_memset4(void * dst, Uint32 val, size_t dwords)"
  {:arglists '([dst val dwords]) :sdl/c "SDL_memset4" :sdl/args [:pointer :uint32 :size_t] :sdl/ret :pointer}
  "SDL_memset4" [:pointer :uint32 :size_t] :pointer)

(ffi/defcfn memcmp
  "int SDL_memcmp(const void * s1, const void * s2, size_t len)"
  {:arglists '([s1 s2 len]) :sdl/c "SDL_memcmp" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_memcmp" [:pointer :pointer :size_t] :int)

(ffi/defcfn wcslen
  "size_t SDL_wcslen(const wchar_t * wstr)"
  {:arglists '([wstr]) :sdl/c "SDL_wcslen" :sdl/args [:pointer] :sdl/ret :size_t}
  "SDL_wcslen" [:pointer] :size_t)

(ffi/defcfn wcsnlen
  "size_t SDL_wcsnlen(const wchar_t * wstr, size_t maxlen)"
  {:arglists '([wstr maxlen]) :sdl/c "SDL_wcsnlen" :sdl/args [:pointer :size_t] :sdl/ret :size_t}
  "SDL_wcsnlen" [:pointer :size_t] :size_t)

(ffi/defcfn wcslcpy
  "size_t SDL_wcslcpy(wchar_t * dst, const wchar_t * src, size_t maxlen)"
  {:arglists '([dst src maxlen]) :sdl/c "SDL_wcslcpy" :sdl/args [:pointer :pointer :size_t] :sdl/ret :size_t}
  "SDL_wcslcpy" [:pointer :pointer :size_t] :size_t)

(ffi/defcfn wcslcat
  "size_t SDL_wcslcat(wchar_t * dst, const wchar_t * src, size_t maxlen)"
  {:arglists '([dst src maxlen]) :sdl/c "SDL_wcslcat" :sdl/args [:pointer :pointer :size_t] :sdl/ret :size_t}
  "SDL_wcslcat" [:pointer :pointer :size_t] :size_t)

(ffi/defcfn wcsdup
  "wchar_t * SDL_wcsdup(const wchar_t * wstr)"
  {:arglists '([wstr]) :sdl/c "SDL_wcsdup" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_wcsdup" [:pointer] :pointer)

(ffi/defcfn wcsstr
  "wchar_t * SDL_wcsstr(const wchar_t * haystack, const wchar_t * needle)"
  {:arglists '([haystack needle]) :sdl/c "SDL_wcsstr" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_wcsstr" [:pointer :pointer] :pointer)

(ffi/defcfn wcsnstr
  "wchar_t * SDL_wcsnstr(const wchar_t * haystack, const wchar_t * needle, size_t maxlen)"
  {:arglists '([haystack needle maxlen]) :sdl/c "SDL_wcsnstr" :sdl/args [:pointer :pointer :size_t] :sdl/ret :pointer}
  "SDL_wcsnstr" [:pointer :pointer :size_t] :pointer)

(ffi/defcfn wcscmp
  "int SDL_wcscmp(const wchar_t * str1, const wchar_t * str2)"
  {:arglists '([str1 str2]) :sdl/c "SDL_wcscmp" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "SDL_wcscmp" [:pointer :pointer] :int)

(ffi/defcfn wcsncmp
  "int SDL_wcsncmp(const wchar_t * str1, const wchar_t * str2, size_t maxlen)"
  {:arglists '([str1 str2 maxlen]) :sdl/c "SDL_wcsncmp" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_wcsncmp" [:pointer :pointer :size_t] :int)

(ffi/defcfn wcscasecmp
  "int SDL_wcscasecmp(const wchar_t * str1, const wchar_t * str2)"
  {:arglists '([str1 str2]) :sdl/c "SDL_wcscasecmp" :sdl/args [:pointer :pointer] :sdl/ret :int}
  "SDL_wcscasecmp" [:pointer :pointer] :int)

(ffi/defcfn wcsncasecmp
  "int SDL_wcsncasecmp(const wchar_t * str1, const wchar_t * str2, size_t maxlen)"
  {:arglists '([str1 str2 maxlen]) :sdl/c "SDL_wcsncasecmp" :sdl/args [:pointer :pointer :size_t] :sdl/ret :int}
  "SDL_wcsncasecmp" [:pointer :pointer :size_t] :int)

(ffi/defcfn wcstol
  "long SDL_wcstol(const wchar_t * str, wchar_t ** endp, int base)"
  {:arglists '([str endp base]) :sdl/c "SDL_wcstol" :sdl/args [:pointer :pointer :int] :sdl/ret :long}
  "SDL_wcstol" [:pointer :pointer :int] :long)

(ffi/defcfn strlen
  "size_t SDL_strlen(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_strlen" :sdl/args [:string] :sdl/ret :size_t}
  "SDL_strlen" [:string] :size_t)

(ffi/defcfn strnlen
  "size_t SDL_strnlen(const char * str, size_t maxlen)"
  {:arglists '([str maxlen]) :sdl/c "SDL_strnlen" :sdl/args [:string :size_t] :sdl/ret :size_t}
  "SDL_strnlen" [:string :size_t] :size_t)

(ffi/defcfn strlcpy
  "size_t SDL_strlcpy(char * dst, const char * src, size_t maxlen)"
  {:arglists '([dst src maxlen]) :sdl/c "SDL_strlcpy" :sdl/args [:pointer :string :size_t] :sdl/ret :size_t}
  "SDL_strlcpy" [:pointer :string :size_t] :size_t)

(ffi/defcfn utf8strlcpy
  "size_t SDL_utf8strlcpy(char * dst, const char * src, size_t dst_bytes)"
  {:arglists '([dst src dst-bytes]) :sdl/c "SDL_utf8strlcpy" :sdl/args [:pointer :string :size_t] :sdl/ret :size_t}
  "SDL_utf8strlcpy" [:pointer :string :size_t] :size_t)

(ffi/defcfn strlcat
  "size_t SDL_strlcat(char * dst, const char * src, size_t maxlen)"
  {:arglists '([dst src maxlen]) :sdl/c "SDL_strlcat" :sdl/args [:pointer :string :size_t] :sdl/ret :size_t}
  "SDL_strlcat" [:pointer :string :size_t] :size_t)

(ffi/defcfn strdup
  "char * SDL_strdup(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_strdup" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_strdup" [:string] :pointer)

(ffi/defcfn strndup
  "char * SDL_strndup(const char * str, size_t maxlen)"
  {:arglists '([str maxlen]) :sdl/c "SDL_strndup" :sdl/args [:string :size_t] :sdl/ret :pointer}
  "SDL_strndup" [:string :size_t] :pointer)

(ffi/defcfn strrev
  "char * SDL_strrev(char * str)"
  {:arglists '([str]) :sdl/c "SDL_strrev" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_strrev" [:pointer] :pointer)

(ffi/defcfn strupr
  "char * SDL_strupr(char * str)"
  {:arglists '([str]) :sdl/c "SDL_strupr" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_strupr" [:pointer] :pointer)

(ffi/defcfn strlwr
  "char * SDL_strlwr(char * str)"
  {:arglists '([str]) :sdl/c "SDL_strlwr" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_strlwr" [:pointer] :pointer)

(ffi/defcfn strchr
  "char * SDL_strchr(const char * str, int c)"
  {:arglists '([str c]) :sdl/c "SDL_strchr" :sdl/args [:string :int] :sdl/ret :pointer}
  "SDL_strchr" [:string :int] :pointer)

(ffi/defcfn strrchr
  "char * SDL_strrchr(const char * str, int c)"
  {:arglists '([str c]) :sdl/c "SDL_strrchr" :sdl/args [:string :int] :sdl/ret :pointer}
  "SDL_strrchr" [:string :int] :pointer)

(ffi/defcfn strstr
  "char * SDL_strstr(const char * haystack, const char * needle)"
  {:arglists '([haystack needle]) :sdl/c "SDL_strstr" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_strstr" [:string :string] :pointer)

(ffi/defcfn strnstr
  "char * SDL_strnstr(const char * haystack, const char * needle, size_t maxlen)"
  {:arglists '([haystack needle maxlen]) :sdl/c "SDL_strnstr" :sdl/args [:string :string :size_t] :sdl/ret :pointer}
  "SDL_strnstr" [:string :string :size_t] :pointer)

(ffi/defcfn strcasestr
  "char * SDL_strcasestr(const char * haystack, const char * needle)"
  {:arglists '([haystack needle]) :sdl/c "SDL_strcasestr" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_strcasestr" [:string :string] :pointer)

(ffi/defcfn strtok-r
  "char * SDL_strtok_r(char * str, const char * delim, char ** saveptr)"
  {:arglists '([str delim saveptr]) :sdl/c "SDL_strtok_r" :sdl/args [:pointer :string :pointer] :sdl/ret :pointer}
  "SDL_strtok_r" [:pointer :string :pointer] :pointer)

(ffi/defcfn utf8strlen
  "size_t SDL_utf8strlen(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_utf8strlen" :sdl/args [:string] :sdl/ret :size_t}
  "SDL_utf8strlen" [:string] :size_t)

(ffi/defcfn utf8strnlen
  "size_t SDL_utf8strnlen(const char * str, size_t bytes)"
  {:arglists '([str bytes]) :sdl/c "SDL_utf8strnlen" :sdl/args [:string :size_t] :sdl/ret :size_t}
  "SDL_utf8strnlen" [:string :size_t] :size_t)

(ffi/defcfn itoa
  "char * SDL_itoa(int value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_itoa" :sdl/args [:int :pointer :int] :sdl/ret :pointer}
  "SDL_itoa" [:int :pointer :int] :pointer)

(ffi/defcfn uitoa
  "char * SDL_uitoa(unsigned int value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_uitoa" :sdl/args [:uint :pointer :int] :sdl/ret :pointer}
  "SDL_uitoa" [:uint :pointer :int] :pointer)

(ffi/defcfn ltoa
  "char * SDL_ltoa(long value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_ltoa" :sdl/args [:long :pointer :int] :sdl/ret :pointer}
  "SDL_ltoa" [:long :pointer :int] :pointer)

(ffi/defcfn ultoa
  "char * SDL_ultoa(unsigned long value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_ultoa" :sdl/args [:ulong :pointer :int] :sdl/ret :pointer}
  "SDL_ultoa" [:ulong :pointer :int] :pointer)

(ffi/defcfn lltoa
  "char * SDL_lltoa(long long value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_lltoa" :sdl/args [:int64 :pointer :int] :sdl/ret :pointer}
  "SDL_lltoa" [:int64 :pointer :int] :pointer)

(ffi/defcfn ulltoa
  "char * SDL_ulltoa(unsigned long long value, char * str, int radix)"
  {:arglists '([value str radix]) :sdl/c "SDL_ulltoa" :sdl/args [:uint64 :pointer :int] :sdl/ret :pointer}
  "SDL_ulltoa" [:uint64 :pointer :int] :pointer)

(ffi/defcfn atoi
  "int SDL_atoi(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_atoi" :sdl/args [:string] :sdl/ret :int}
  "SDL_atoi" [:string] :int)

(ffi/defcfn atof
  "double SDL_atof(const char * str)"
  {:arglists '([str]) :sdl/c "SDL_atof" :sdl/args [:string] :sdl/ret :double}
  "SDL_atof" [:string] :double)

(ffi/defcfn strtol
  "long SDL_strtol(const char * str, char ** endp, int base)"
  {:arglists '([str endp base]) :sdl/c "SDL_strtol" :sdl/args [:string :pointer :int] :sdl/ret :long}
  "SDL_strtol" [:string :pointer :int] :long)

(ffi/defcfn strtoul
  "unsigned long SDL_strtoul(const char * str, char ** endp, int base)"
  {:arglists '([str endp base]) :sdl/c "SDL_strtoul" :sdl/args [:string :pointer :int] :sdl/ret :ulong}
  "SDL_strtoul" [:string :pointer :int] :ulong)

(ffi/defcfn strtoll
  "long long SDL_strtoll(const char * str, char ** endp, int base)"
  {:arglists '([str endp base]) :sdl/c "SDL_strtoll" :sdl/args [:string :pointer :int] :sdl/ret :int64}
  "SDL_strtoll" [:string :pointer :int] :int64)

(ffi/defcfn strtoull
  "unsigned long long SDL_strtoull(const char * str, char ** endp, int base)"
  {:arglists '([str endp base]) :sdl/c "SDL_strtoull" :sdl/args [:string :pointer :int] :sdl/ret :uint64}
  "SDL_strtoull" [:string :pointer :int] :uint64)

(ffi/defcfn strtod
  "double SDL_strtod(const char * str, char ** endp)"
  {:arglists '([str endp]) :sdl/c "SDL_strtod" :sdl/args [:string :pointer] :sdl/ret :double}
  "SDL_strtod" [:string :pointer] :double)

(ffi/defcfn strcmp
  "int SDL_strcmp(const char * str1, const char * str2)"
  {:arglists '([str1 str2]) :sdl/c "SDL_strcmp" :sdl/args [:string :string] :sdl/ret :int}
  "SDL_strcmp" [:string :string] :int)

(ffi/defcfn strncmp
  "int SDL_strncmp(const char * str1, const char * str2, size_t maxlen)"
  {:arglists '([str1 str2 maxlen]) :sdl/c "SDL_strncmp" :sdl/args [:string :string :size_t] :sdl/ret :int}
  "SDL_strncmp" [:string :string :size_t] :int)

(ffi/defcfn strcasecmp
  "int SDL_strcasecmp(const char * str1, const char * str2)"
  {:arglists '([str1 str2]) :sdl/c "SDL_strcasecmp" :sdl/args [:string :string] :sdl/ret :int}
  "SDL_strcasecmp" [:string :string] :int)

(ffi/defcfn strncasecmp
  "int SDL_strncasecmp(const char * str1, const char * str2, size_t maxlen)"
  {:arglists '([str1 str2 maxlen]) :sdl/c "SDL_strncasecmp" :sdl/args [:string :string :size_t] :sdl/ret :int}
  "SDL_strncasecmp" [:string :string :size_t] :int)

(ffi/defcfn strpbrk
  "char * SDL_strpbrk(const char * str, const char * breakset)"
  {:arglists '([str breakset]) :sdl/c "SDL_strpbrk" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_strpbrk" [:string :string] :pointer)

(ffi/defcfn step-utf8
  "Uint32 SDL_StepUTF8(const char ** pstr, size_t * pslen)"
  {:arglists '([pstr pslen]) :sdl/c "SDL_StepUTF8" :sdl/args [:pointer :pointer] :sdl/ret :uint32}
  "SDL_StepUTF8" [:pointer :pointer] :uint32)

(ffi/defcfn step-back-utf8
  "Uint32 SDL_StepBackUTF8(const char * start, const char ** pstr)"
  {:arglists '([start pstr]) :sdl/c "SDL_StepBackUTF8" :sdl/args [:string :pointer] :sdl/ret :uint32}
  "SDL_StepBackUTF8" [:string :pointer] :uint32)

(ffi/defcfn ucs4-to-utf8
  "char * SDL_UCS4ToUTF8(Uint32 codepoint, char * dst)"
  {:arglists '([codepoint dst]) :sdl/c "SDL_UCS4ToUTF8" :sdl/args [:uint32 :pointer] :sdl/ret :pointer}
  "SDL_UCS4ToUTF8" [:uint32 :pointer] :pointer)

(ffi/defcfn sscanf
  "int SDL_sscanf(const char * text, const char * fmt, ...)"
  {:arglists '([text fmt & varargs]) :sdl/c "SDL_sscanf" :sdl/args [:string :string :&] :sdl/ret :int}
  "SDL_sscanf" [:string :string :&] :int)

(ffi/defcfn snprintf
  "int SDL_snprintf(char * text, size_t maxlen, const char * fmt, ...)"
  {:arglists '([text maxlen fmt & varargs]) :sdl/c "SDL_snprintf" :sdl/args [:pointer :size_t :string :&] :sdl/ret :int}
  "SDL_snprintf" [:pointer :size_t :string :&] :int)

(ffi/defcfn swprintf
  "int SDL_swprintf(wchar_t * text, size_t maxlen, const wchar_t * fmt, ...)"
  {:arglists '([text maxlen fmt & varargs]) :sdl/c "SDL_swprintf" :sdl/args [:pointer :size_t :pointer :&] :sdl/ret :int}
  "SDL_swprintf" [:pointer :size_t :pointer :&] :int)

(ffi/defcfn asprintf
  "int SDL_asprintf(char ** strp, const char * fmt, ...)"
  {:arglists '([strp fmt & varargs]) :sdl/c "SDL_asprintf" :sdl/args [:pointer :string :&] :sdl/ret :int}
  "SDL_asprintf" [:pointer :string :&] :int)

(ffi/defcfn srand
  "void SDL_srand(Uint64 seed)"
  {:arglists '([seed]) :sdl/c "SDL_srand" :sdl/args [:uint64] :sdl/ret :void}
  "SDL_srand" [:uint64] :void)

(ffi/defcfn rand
  "Sint32 SDL_rand(Sint32 n)"
  {:arglists '([n]) :sdl/c "SDL_rand" :sdl/args [:int32] :sdl/ret :int32}
  "SDL_rand" [:int32] :int32)

(ffi/defcfn randf
  "float SDL_randf(void)"
  {:arglists '([]) :sdl/c "SDL_randf" :sdl/args [] :sdl/ret :float}
  "SDL_randf" [] :float)

(ffi/defcfn rand-bits
  "Uint32 SDL_rand_bits(void)"
  {:arglists '([]) :sdl/c "SDL_rand_bits" :sdl/args [] :sdl/ret :uint32}
  "SDL_rand_bits" [] :uint32)

(ffi/defcfn rand-r
  "Sint32 SDL_rand_r(Uint64 * state, Sint32 n)"
  {:arglists '([state n]) :sdl/c "SDL_rand_r" :sdl/args [:pointer :int32] :sdl/ret :int32}
  "SDL_rand_r" [:pointer :int32] :int32)

(ffi/defcfn randf-r
  "float SDL_randf_r(Uint64 * state)"
  {:arglists '([state]) :sdl/c "SDL_randf_r" :sdl/args [:pointer] :sdl/ret :float}
  "SDL_randf_r" [:pointer] :float)

(ffi/defcfn rand-bits-r
  "Uint32 SDL_rand_bits_r(Uint64 * state)"
  {:arglists '([state]) :sdl/c "SDL_rand_bits_r" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_rand_bits_r" [:pointer] :uint32)

(ffi/defcfn acos
  "double SDL_acos(double x)"
  {:arglists '([x]) :sdl/c "SDL_acos" :sdl/args [:double] :sdl/ret :double}
  "SDL_acos" [:double] :double)

(ffi/defcfn acosf
  "float SDL_acosf(float x)"
  {:arglists '([x]) :sdl/c "SDL_acosf" :sdl/args [:float] :sdl/ret :float}
  "SDL_acosf" [:float] :float)

(ffi/defcfn asin
  "double SDL_asin(double x)"
  {:arglists '([x]) :sdl/c "SDL_asin" :sdl/args [:double] :sdl/ret :double}
  "SDL_asin" [:double] :double)

(ffi/defcfn asinf
  "float SDL_asinf(float x)"
  {:arglists '([x]) :sdl/c "SDL_asinf" :sdl/args [:float] :sdl/ret :float}
  "SDL_asinf" [:float] :float)

(ffi/defcfn atan
  "double SDL_atan(double x)"
  {:arglists '([x]) :sdl/c "SDL_atan" :sdl/args [:double] :sdl/ret :double}
  "SDL_atan" [:double] :double)

(ffi/defcfn atanf
  "float SDL_atanf(float x)"
  {:arglists '([x]) :sdl/c "SDL_atanf" :sdl/args [:float] :sdl/ret :float}
  "SDL_atanf" [:float] :float)

(ffi/defcfn atan2
  "double SDL_atan2(double y, double x)"
  {:arglists '([y x]) :sdl/c "SDL_atan2" :sdl/args [:double :double] :sdl/ret :double}
  "SDL_atan2" [:double :double] :double)

(ffi/defcfn atan2f
  "float SDL_atan2f(float y, float x)"
  {:arglists '([y x]) :sdl/c "SDL_atan2f" :sdl/args [:float :float] :sdl/ret :float}
  "SDL_atan2f" [:float :float] :float)

(ffi/defcfn ceil
  "double SDL_ceil(double x)"
  {:arglists '([x]) :sdl/c "SDL_ceil" :sdl/args [:double] :sdl/ret :double}
  "SDL_ceil" [:double] :double)

(ffi/defcfn ceilf
  "float SDL_ceilf(float x)"
  {:arglists '([x]) :sdl/c "SDL_ceilf" :sdl/args [:float] :sdl/ret :float}
  "SDL_ceilf" [:float] :float)

(ffi/defcfn copysign
  "double SDL_copysign(double x, double y)"
  {:arglists '([x y]) :sdl/c "SDL_copysign" :sdl/args [:double :double] :sdl/ret :double}
  "SDL_copysign" [:double :double] :double)

(ffi/defcfn copysignf
  "float SDL_copysignf(float x, float y)"
  {:arglists '([x y]) :sdl/c "SDL_copysignf" :sdl/args [:float :float] :sdl/ret :float}
  "SDL_copysignf" [:float :float] :float)

(ffi/defcfn cos
  "double SDL_cos(double x)"
  {:arglists '([x]) :sdl/c "SDL_cos" :sdl/args [:double] :sdl/ret :double}
  "SDL_cos" [:double] :double)

(ffi/defcfn cosf
  "float SDL_cosf(float x)"
  {:arglists '([x]) :sdl/c "SDL_cosf" :sdl/args [:float] :sdl/ret :float}
  "SDL_cosf" [:float] :float)

(ffi/defcfn exp
  "double SDL_exp(double x)"
  {:arglists '([x]) :sdl/c "SDL_exp" :sdl/args [:double] :sdl/ret :double}
  "SDL_exp" [:double] :double)

(ffi/defcfn expf
  "float SDL_expf(float x)"
  {:arglists '([x]) :sdl/c "SDL_expf" :sdl/args [:float] :sdl/ret :float}
  "SDL_expf" [:float] :float)

(ffi/defcfn fabs
  "double SDL_fabs(double x)"
  {:arglists '([x]) :sdl/c "SDL_fabs" :sdl/args [:double] :sdl/ret :double}
  "SDL_fabs" [:double] :double)

(ffi/defcfn fabsf
  "float SDL_fabsf(float x)"
  {:arglists '([x]) :sdl/c "SDL_fabsf" :sdl/args [:float] :sdl/ret :float}
  "SDL_fabsf" [:float] :float)

(ffi/defcfn floor
  "double SDL_floor(double x)"
  {:arglists '([x]) :sdl/c "SDL_floor" :sdl/args [:double] :sdl/ret :double}
  "SDL_floor" [:double] :double)

(ffi/defcfn floorf
  "float SDL_floorf(float x)"
  {:arglists '([x]) :sdl/c "SDL_floorf" :sdl/args [:float] :sdl/ret :float}
  "SDL_floorf" [:float] :float)

(ffi/defcfn trunc
  "double SDL_trunc(double x)"
  {:arglists '([x]) :sdl/c "SDL_trunc" :sdl/args [:double] :sdl/ret :double}
  "SDL_trunc" [:double] :double)

(ffi/defcfn truncf
  "float SDL_truncf(float x)"
  {:arglists '([x]) :sdl/c "SDL_truncf" :sdl/args [:float] :sdl/ret :float}
  "SDL_truncf" [:float] :float)

(ffi/defcfn fmod
  "double SDL_fmod(double x, double y)"
  {:arglists '([x y]) :sdl/c "SDL_fmod" :sdl/args [:double :double] :sdl/ret :double}
  "SDL_fmod" [:double :double] :double)

(ffi/defcfn fmodf
  "float SDL_fmodf(float x, float y)"
  {:arglists '([x y]) :sdl/c "SDL_fmodf" :sdl/args [:float :float] :sdl/ret :float}
  "SDL_fmodf" [:float :float] :float)

(ffi/defcfn isinf
  "int SDL_isinf(double x)"
  {:arglists '([x]) :sdl/c "SDL_isinf" :sdl/args [:double] :sdl/ret :int}
  "SDL_isinf" [:double] :int)

(ffi/defcfn isinff
  "int SDL_isinff(float x)"
  {:arglists '([x]) :sdl/c "SDL_isinff" :sdl/args [:float] :sdl/ret :int}
  "SDL_isinff" [:float] :int)

(ffi/defcfn isnan
  "int SDL_isnan(double x)"
  {:arglists '([x]) :sdl/c "SDL_isnan" :sdl/args [:double] :sdl/ret :int}
  "SDL_isnan" [:double] :int)

(ffi/defcfn isnanf
  "int SDL_isnanf(float x)"
  {:arglists '([x]) :sdl/c "SDL_isnanf" :sdl/args [:float] :sdl/ret :int}
  "SDL_isnanf" [:float] :int)

(ffi/defcfn log
  "double SDL_log(double x)"
  {:arglists '([x]) :sdl/c "SDL_log" :sdl/args [:double] :sdl/ret :double}
  "SDL_log" [:double] :double)

(ffi/defcfn logf
  "float SDL_logf(float x)"
  {:arglists '([x]) :sdl/c "SDL_logf" :sdl/args [:float] :sdl/ret :float}
  "SDL_logf" [:float] :float)

(ffi/defcfn log10
  "double SDL_log10(double x)"
  {:arglists '([x]) :sdl/c "SDL_log10" :sdl/args [:double] :sdl/ret :double}
  "SDL_log10" [:double] :double)

(ffi/defcfn log10f
  "float SDL_log10f(float x)"
  {:arglists '([x]) :sdl/c "SDL_log10f" :sdl/args [:float] :sdl/ret :float}
  "SDL_log10f" [:float] :float)

(ffi/defcfn modf
  "double SDL_modf(double x, double * y)"
  {:arglists '([x y]) :sdl/c "SDL_modf" :sdl/args [:double :pointer] :sdl/ret :double}
  "SDL_modf" [:double :pointer] :double)

(ffi/defcfn modff
  "float SDL_modff(float x, float * y)"
  {:arglists '([x y]) :sdl/c "SDL_modff" :sdl/args [:float :pointer] :sdl/ret :float}
  "SDL_modff" [:float :pointer] :float)

(ffi/defcfn pow
  "double SDL_pow(double x, double y)"
  {:arglists '([x y]) :sdl/c "SDL_pow" :sdl/args [:double :double] :sdl/ret :double}
  "SDL_pow" [:double :double] :double)

(ffi/defcfn powf
  "float SDL_powf(float x, float y)"
  {:arglists '([x y]) :sdl/c "SDL_powf" :sdl/args [:float :float] :sdl/ret :float}
  "SDL_powf" [:float :float] :float)

(ffi/defcfn round
  "double SDL_round(double x)"
  {:arglists '([x]) :sdl/c "SDL_round" :sdl/args [:double] :sdl/ret :double}
  "SDL_round" [:double] :double)

(ffi/defcfn roundf
  "float SDL_roundf(float x)"
  {:arglists '([x]) :sdl/c "SDL_roundf" :sdl/args [:float] :sdl/ret :float}
  "SDL_roundf" [:float] :float)

(ffi/defcfn lround
  "long SDL_lround(double x)"
  {:arglists '([x]) :sdl/c "SDL_lround" :sdl/args [:double] :sdl/ret :long}
  "SDL_lround" [:double] :long)

(ffi/defcfn lroundf
  "long SDL_lroundf(float x)"
  {:arglists '([x]) :sdl/c "SDL_lroundf" :sdl/args [:float] :sdl/ret :long}
  "SDL_lroundf" [:float] :long)

(ffi/defcfn scalbn
  "double SDL_scalbn(double x, int n)"
  {:arglists '([x n]) :sdl/c "SDL_scalbn" :sdl/args [:double :int] :sdl/ret :double}
  "SDL_scalbn" [:double :int] :double)

(ffi/defcfn scalbnf
  "float SDL_scalbnf(float x, int n)"
  {:arglists '([x n]) :sdl/c "SDL_scalbnf" :sdl/args [:float :int] :sdl/ret :float}
  "SDL_scalbnf" [:float :int] :float)

(ffi/defcfn sin
  "double SDL_sin(double x)"
  {:arglists '([x]) :sdl/c "SDL_sin" :sdl/args [:double] :sdl/ret :double}
  "SDL_sin" [:double] :double)

(ffi/defcfn sinf
  "float SDL_sinf(float x)"
  {:arglists '([x]) :sdl/c "SDL_sinf" :sdl/args [:float] :sdl/ret :float}
  "SDL_sinf" [:float] :float)

(ffi/defcfn sqrt
  "double SDL_sqrt(double x)"
  {:arglists '([x]) :sdl/c "SDL_sqrt" :sdl/args [:double] :sdl/ret :double}
  "SDL_sqrt" [:double] :double)

(ffi/defcfn sqrtf
  "float SDL_sqrtf(float x)"
  {:arglists '([x]) :sdl/c "SDL_sqrtf" :sdl/args [:float] :sdl/ret :float}
  "SDL_sqrtf" [:float] :float)

(ffi/defcfn tan
  "double SDL_tan(double x)"
  {:arglists '([x]) :sdl/c "SDL_tan" :sdl/args [:double] :sdl/ret :double}
  "SDL_tan" [:double] :double)

(ffi/defcfn tanf
  "float SDL_tanf(float x)"
  {:arglists '([x]) :sdl/c "SDL_tanf" :sdl/args [:float] :sdl/ret :float}
  "SDL_tanf" [:float] :float)

(ffi/defcfn iconv-open
  "SDL_iconv_t SDL_iconv_open(const char * tocode, const char * fromcode)"
  {:arglists '([tocode fromcode]) :sdl/c "SDL_iconv_open" :sdl/args [:string :string] :sdl/ret :pointer}
  "SDL_iconv_open" [:string :string] :pointer)

(ffi/defcfn iconv-close
  "int SDL_iconv_close(SDL_iconv_t cd)"
  {:arglists '([cd]) :sdl/c "SDL_iconv_close" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_iconv_close" [:pointer] :int)

(ffi/defcfn iconv
  "size_t SDL_iconv(SDL_iconv_t cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)"
  {:arglists '([cd inbuf inbytesleft outbuf outbytesleft]) :sdl/c "SDL_iconv" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :size_t}
  "SDL_iconv" [:pointer :pointer :pointer :pointer :pointer] :size_t)

(ffi/defcfn iconv-string
  "char * SDL_iconv_string(const char * tocode, const char * fromcode, const char * inbuf, size_t inbytesleft)"
  {:arglists '([tocode fromcode inbuf inbytesleft]) :sdl/c "SDL_iconv_string" :sdl/args [:string :string :string :size_t] :sdl/ret :pointer}
  "SDL_iconv_string" [:string :string :string :size_t] :pointer)
