;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.storage
  "Raw bindings for SDL_storage.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def storage-interface
  "ffi/layout of SDL_StorageInterface."
  (ffi/layout [:struct [[:version :uint32] [:close :pointer] [:ready :pointer] [:enumerate :pointer] [:info :pointer] [:read-file :pointer] [:write-file :pointer] [:mkdir :pointer] [:remove :pointer] [:rename :pointer] [:copy :pointer] [:space-remaining :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn open-title-storage
  "SDL_Storage * SDL_OpenTitleStorage(const char * override, SDL_PropertiesID props)"
  {:arglists '([override props]) :sdl/c "SDL_OpenTitleStorage" :sdl/args [:string :uint32] :sdl/ret :pointer}
  "SDL_OpenTitleStorage" [:string :uint32] :pointer)

(ffi/defcfn open-user-storage
  "SDL_Storage * SDL_OpenUserStorage(const char * org, const char * app, SDL_PropertiesID props)"
  {:arglists '([org app props]) :sdl/c "SDL_OpenUserStorage" :sdl/args [:string :string :uint32] :sdl/ret :pointer}
  "SDL_OpenUserStorage" [:string :string :uint32] :pointer)

(ffi/defcfn open-file-storage
  "SDL_Storage * SDL_OpenFileStorage(const char * path)"
  {:arglists '([path]) :sdl/c "SDL_OpenFileStorage" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_OpenFileStorage" [:string] :pointer)

(ffi/defcfn open-storage
  "SDL_Storage * SDL_OpenStorage(const SDL_StorageInterface * iface, void * userdata)"
  {:arglists '([iface userdata]) :sdl/c "SDL_OpenStorage" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_OpenStorage" [:pointer :pointer] :pointer)

(ffi/defcfn close-storage
  "bool SDL_CloseStorage(SDL_Storage * storage)"
  {:arglists '([storage]) :sdl/c "SDL_CloseStorage" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_CloseStorage" [:pointer] :bool)

(ffi/defcfn storage-ready
  "bool SDL_StorageReady(SDL_Storage * storage)"
  {:arglists '([storage]) :sdl/c "SDL_StorageReady" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_StorageReady" [:pointer] :bool)

(ffi/defcfn get-storage-file-size
  "bool SDL_GetStorageFileSize(SDL_Storage * storage, const char * path, Uint64 * length)"
  {:arglists '([storage path length]) :sdl/c "SDL_GetStorageFileSize" :sdl/args [:pointer :string :pointer] :sdl/ret :bool}
  "SDL_GetStorageFileSize" [:pointer :string :pointer] :bool)

(ffi/defcfn read-storage-file
  "bool SDL_ReadStorageFile(SDL_Storage * storage, const char * path, void * destination, Uint64 length)"
  {:arglists '([storage path destination length]) :sdl/c "SDL_ReadStorageFile" :sdl/args [:pointer :string :pointer :uint64] :sdl/ret :bool}
  "SDL_ReadStorageFile" [:pointer :string :pointer :uint64] :bool)

(ffi/defcfn write-storage-file
  "bool SDL_WriteStorageFile(SDL_Storage * storage, const char * path, const void * source, Uint64 length)"
  {:arglists '([storage path source length]) :sdl/c "SDL_WriteStorageFile" :sdl/args [:pointer :string :pointer :uint64] :sdl/ret :bool}
  "SDL_WriteStorageFile" [:pointer :string :pointer :uint64] :bool)

(ffi/defcfn create-storage-directory
  "bool SDL_CreateStorageDirectory(SDL_Storage * storage, const char * path)"
  {:arglists '([storage path]) :sdl/c "SDL_CreateStorageDirectory" :sdl/args [:pointer :string] :sdl/ret :bool}
  "SDL_CreateStorageDirectory" [:pointer :string] :bool)

(ffi/defcfn enumerate-storage-directory
  "bool SDL_EnumerateStorageDirectory(SDL_Storage * storage, const char * path, SDL_EnumerateDirectoryCallback callback, void * userdata)"
  {:arglists '([storage path callback userdata]) :sdl/c "SDL_EnumerateStorageDirectory" :sdl/args [:pointer :string :pointer :pointer] :sdl/ret :bool}
  "SDL_EnumerateStorageDirectory" [:pointer :string :pointer :pointer] :bool)

(ffi/defcfn remove-storage-path
  "bool SDL_RemoveStoragePath(SDL_Storage * storage, const char * path)"
  {:arglists '([storage path]) :sdl/c "SDL_RemoveStoragePath" :sdl/args [:pointer :string] :sdl/ret :bool}
  "SDL_RemoveStoragePath" [:pointer :string] :bool)

(ffi/defcfn rename-storage-path
  "bool SDL_RenameStoragePath(SDL_Storage * storage, const char * oldpath, const char * newpath)"
  {:arglists '([storage oldpath newpath]) :sdl/c "SDL_RenameStoragePath" :sdl/args [:pointer :string :string] :sdl/ret :bool}
  "SDL_RenameStoragePath" [:pointer :string :string] :bool)

(ffi/defcfn copy-storage-file
  "bool SDL_CopyStorageFile(SDL_Storage * storage, const char * oldpath, const char * newpath)"
  {:arglists '([storage oldpath newpath]) :sdl/c "SDL_CopyStorageFile" :sdl/args [:pointer :string :string] :sdl/ret :bool}
  "SDL_CopyStorageFile" [:pointer :string :string] :bool)

(ffi/defcfn get-storage-path-info
  "bool SDL_GetStoragePathInfo(SDL_Storage * storage, const char * path, SDL_PathInfo * info)"
  {:arglists '([storage path info]) :sdl/c "SDL_GetStoragePathInfo" :sdl/args [:pointer :string :pointer] :sdl/ret :bool}
  "SDL_GetStoragePathInfo" [:pointer :string :pointer] :bool)

(ffi/defcfn get-storage-space-remaining
  "Uint64 SDL_GetStorageSpaceRemaining(SDL_Storage * storage)"
  {:arglists '([storage]) :sdl/c "SDL_GetStorageSpaceRemaining" :sdl/args [:pointer] :sdl/ret :uint64}
  "SDL_GetStorageSpaceRemaining" [:pointer] :uint64)

(ffi/defcfn glob-storage-directory
  "char ** SDL_GlobStorageDirectory(SDL_Storage * storage, const char * path, const char * pattern, SDL_GlobFlags flags, int * count)"
  {:arglists '([storage path pattern flags count]) :sdl/c "SDL_GlobStorageDirectory" :sdl/args [:pointer :string :string :uint32 :pointer] :sdl/ret :pointer}
  "SDL_GlobStorageDirectory" [:pointer :string :string :uint32 :pointer] :pointer)
