;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.surface
  "Raw bindings for SDL_surface.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def surface
  "ffi/layout of SDL_Surface."
  (ffi/layout [:struct [[:flags :uint32] [:format :int] [:w :int] [:h :int] [:pitch :int] [:pixels :pointer] [:refcount :int] [:reserved :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn create-surface
  "SDL_Surface * SDL_CreateSurface(int width, int height, SDL_PixelFormat format)"
  {:arglists '([width height format]) :sdl/c "SDL_CreateSurface" :sdl/args [:int :int :int] :sdl/ret :pointer}
  "SDL_CreateSurface" [:int :int :int] :pointer)

(ffi/defcfn create-surface-from
  "SDL_Surface * SDL_CreateSurfaceFrom(int width, int height, SDL_PixelFormat format, void * pixels, int pitch)"
  {:arglists '([width height format pixels pitch]) :sdl/c "SDL_CreateSurfaceFrom" :sdl/args [:int :int :int :pointer :int] :sdl/ret :pointer}
  "SDL_CreateSurfaceFrom" [:int :int :int :pointer :int] :pointer)

(ffi/defcfn destroy-surface
  "void SDL_DestroySurface(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_DestroySurface" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroySurface" [:pointer] :void)

(ffi/defcfn get-surface-properties
  "SDL_PropertiesID SDL_GetSurfaceProperties(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_GetSurfaceProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "SDL_GetSurfaceProperties" [:pointer] :uint32)

(ffi/defcfn set-surface-colorspace
  "bool SDL_SetSurfaceColorspace(SDL_Surface * surface, SDL_Colorspace colorspace)"
  {:arglists '([surface colorspace]) :sdl/c "SDL_SetSurfaceColorspace" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_SetSurfaceColorspace" [:pointer :int] :bool)

(ffi/defcfn get-surface-colorspace
  "SDL_Colorspace SDL_GetSurfaceColorspace(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_GetSurfaceColorspace" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetSurfaceColorspace" [:pointer] :int)

(ffi/defcfn create-surface-palette
  "SDL_Palette * SDL_CreateSurfacePalette(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_CreateSurfacePalette" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_CreateSurfacePalette" [:pointer] :pointer)

(ffi/defcfn set-surface-palette
  "bool SDL_SetSurfacePalette(SDL_Surface * surface, SDL_Palette * palette)"
  {:arglists '([surface palette]) :sdl/c "SDL_SetSurfacePalette" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetSurfacePalette" [:pointer :pointer] :bool)

(ffi/defcfn get-surface-palette
  "SDL_Palette * SDL_GetSurfacePalette(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_GetSurfacePalette" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetSurfacePalette" [:pointer] :pointer)

(ffi/defcfn add-surface-alternate-image
  "bool SDL_AddSurfaceAlternateImage(SDL_Surface * surface, SDL_Surface * image)"
  {:arglists '([surface image]) :sdl/c "SDL_AddSurfaceAlternateImage" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_AddSurfaceAlternateImage" [:pointer :pointer] :bool)

(ffi/defcfn surface-has-alternate-images
  "bool SDL_SurfaceHasAlternateImages(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_SurfaceHasAlternateImages" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_SurfaceHasAlternateImages" [:pointer] :bool)

(ffi/defcfn get-surface-images
  "SDL_Surface ** SDL_GetSurfaceImages(SDL_Surface * surface, int * count)"
  {:arglists '([surface count]) :sdl/c "SDL_GetSurfaceImages" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_GetSurfaceImages" [:pointer :pointer] :pointer)

(ffi/defcfn remove-surface-alternate-images
  "void SDL_RemoveSurfaceAlternateImages(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_RemoveSurfaceAlternateImages" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_RemoveSurfaceAlternateImages" [:pointer] :void)

(ffi/defcfn lock-surface
  "bool SDL_LockSurface(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_LockSurface" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_LockSurface" [:pointer] :bool)

(ffi/defcfn unlock-surface
  "void SDL_UnlockSurface(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_UnlockSurface" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_UnlockSurface" [:pointer] :void)

(ffi/defcfn load-surface-io
  "SDL_Surface * SDL_LoadSurface_IO(SDL_IOStream * src, bool closeio)"
  {:arglists '([src closeio]) :sdl/c "SDL_LoadSurface_IO" :sdl/args [:pointer :bool] :sdl/ret :pointer}
  "SDL_LoadSurface_IO" [:pointer :bool] :pointer)

(ffi/defcfn load-surface
  "SDL_Surface * SDL_LoadSurface(const char * file)"
  {:arglists '([file]) :sdl/c "SDL_LoadSurface" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_LoadSurface" [:string] :pointer)

(ffi/defcfn load-bmp-io
  "SDL_Surface * SDL_LoadBMP_IO(SDL_IOStream * src, bool closeio)"
  {:arglists '([src closeio]) :sdl/c "SDL_LoadBMP_IO" :sdl/args [:pointer :bool] :sdl/ret :pointer}
  "SDL_LoadBMP_IO" [:pointer :bool] :pointer)

(ffi/defcfn load-bmp
  "SDL_Surface * SDL_LoadBMP(const char * file)"
  {:arglists '([file]) :sdl/c "SDL_LoadBMP" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_LoadBMP" [:string] :pointer)

(ffi/defcfn save-bmp-io
  "bool SDL_SaveBMP_IO(SDL_Surface * surface, SDL_IOStream * dst, bool closeio)"
  {:arglists '([surface dst closeio]) :sdl/c "SDL_SaveBMP_IO" :sdl/args [:pointer :pointer :bool] :sdl/ret :bool}
  "SDL_SaveBMP_IO" [:pointer :pointer :bool] :bool)

(ffi/defcfn save-bmp
  "bool SDL_SaveBMP(SDL_Surface * surface, const char * file)"
  {:arglists '([surface file]) :sdl/c "SDL_SaveBMP" :sdl/args [:pointer :string] :sdl/ret :bool}
  "SDL_SaveBMP" [:pointer :string] :bool)

(ffi/defcfn load-png-io
  "SDL_Surface * SDL_LoadPNG_IO(SDL_IOStream * src, bool closeio)"
  {:arglists '([src closeio]) :sdl/c "SDL_LoadPNG_IO" :sdl/args [:pointer :bool] :sdl/ret :pointer}
  "SDL_LoadPNG_IO" [:pointer :bool] :pointer)

(ffi/defcfn load-png
  "SDL_Surface * SDL_LoadPNG(const char * file)"
  {:arglists '([file]) :sdl/c "SDL_LoadPNG" :sdl/args [:string] :sdl/ret :pointer}
  "SDL_LoadPNG" [:string] :pointer)

(ffi/defcfn save-png-io
  "bool SDL_SavePNG_IO(SDL_Surface * surface, SDL_IOStream * dst, bool closeio)"
  {:arglists '([surface dst closeio]) :sdl/c "SDL_SavePNG_IO" :sdl/args [:pointer :pointer :bool] :sdl/ret :bool}
  "SDL_SavePNG_IO" [:pointer :pointer :bool] :bool)

(ffi/defcfn save-png
  "bool SDL_SavePNG(SDL_Surface * surface, const char * file)"
  {:arglists '([surface file]) :sdl/c "SDL_SavePNG" :sdl/args [:pointer :string] :sdl/ret :bool}
  "SDL_SavePNG" [:pointer :string] :bool)

(ffi/defcfn set-surface-rle
  "bool SDL_SetSurfaceRLE(SDL_Surface * surface, bool enabled)"
  {:arglists '([surface enabled]) :sdl/c "SDL_SetSurfaceRLE" :sdl/args [:pointer :bool] :sdl/ret :bool}
  "SDL_SetSurfaceRLE" [:pointer :bool] :bool)

(ffi/defcfn surface-has-rle
  "bool SDL_SurfaceHasRLE(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_SurfaceHasRLE" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_SurfaceHasRLE" [:pointer] :bool)

(ffi/defcfn set-surface-color-key
  "bool SDL_SetSurfaceColorKey(SDL_Surface * surface, bool enabled, Uint32 key)"
  {:arglists '([surface enabled key]) :sdl/c "SDL_SetSurfaceColorKey" :sdl/args [:pointer :bool :uint32] :sdl/ret :bool}
  "SDL_SetSurfaceColorKey" [:pointer :bool :uint32] :bool)

(ffi/defcfn surface-has-color-key
  "bool SDL_SurfaceHasColorKey(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_SurfaceHasColorKey" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_SurfaceHasColorKey" [:pointer] :bool)

(ffi/defcfn get-surface-color-key
  "bool SDL_GetSurfaceColorKey(SDL_Surface * surface, Uint32 * key)"
  {:arglists '([surface key]) :sdl/c "SDL_GetSurfaceColorKey" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetSurfaceColorKey" [:pointer :pointer] :bool)

(ffi/defcfn set-surface-color-mod
  "bool SDL_SetSurfaceColorMod(SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b)"
  {:arglists '([surface r g b]) :sdl/c "SDL_SetSurfaceColorMod" :sdl/args [:pointer :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_SetSurfaceColorMod" [:pointer :uint8 :uint8 :uint8] :bool)

(ffi/defcfn get-surface-color-mod
  "bool SDL_GetSurfaceColorMod(SDL_Surface * surface, Uint8 * r, Uint8 * g, Uint8 * b)"
  {:arglists '([surface r g b]) :sdl/c "SDL_GetSurfaceColorMod" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_GetSurfaceColorMod" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn set-surface-alpha-mod
  "bool SDL_SetSurfaceAlphaMod(SDL_Surface * surface, Uint8 alpha)"
  {:arglists '([surface alpha]) :sdl/c "SDL_SetSurfaceAlphaMod" :sdl/args [:pointer :uint8] :sdl/ret :bool}
  "SDL_SetSurfaceAlphaMod" [:pointer :uint8] :bool)

(ffi/defcfn get-surface-alpha-mod
  "bool SDL_GetSurfaceAlphaMod(SDL_Surface * surface, Uint8 * alpha)"
  {:arglists '([surface alpha]) :sdl/c "SDL_GetSurfaceAlphaMod" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetSurfaceAlphaMod" [:pointer :pointer] :bool)

(ffi/defcfn set-surface-blend-mode
  "bool SDL_SetSurfaceBlendMode(SDL_Surface * surface, SDL_BlendMode blendMode)"
  {:arglists '([surface blend-mode]) :sdl/c "SDL_SetSurfaceBlendMode" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "SDL_SetSurfaceBlendMode" [:pointer :uint32] :bool)

(ffi/defcfn get-surface-blend-mode
  "bool SDL_GetSurfaceBlendMode(SDL_Surface * surface, SDL_BlendMode * blendMode)"
  {:arglists '([surface blend-mode]) :sdl/c "SDL_GetSurfaceBlendMode" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetSurfaceBlendMode" [:pointer :pointer] :bool)

(ffi/defcfn set-surface-clip-rect
  "bool SDL_SetSurfaceClipRect(SDL_Surface * surface, const SDL_Rect * rect)"
  {:arglists '([surface rect]) :sdl/c "SDL_SetSurfaceClipRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_SetSurfaceClipRect" [:pointer :pointer] :bool)

(ffi/defcfn get-surface-clip-rect
  "bool SDL_GetSurfaceClipRect(SDL_Surface * surface, SDL_Rect * rect)"
  {:arglists '([surface rect]) :sdl/c "SDL_GetSurfaceClipRect" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetSurfaceClipRect" [:pointer :pointer] :bool)

(ffi/defcfn flip-surface
  "bool SDL_FlipSurface(SDL_Surface * surface, SDL_FlipMode flip)"
  {:arglists '([surface flip]) :sdl/c "SDL_FlipSurface" :sdl/args [:pointer :int] :sdl/ret :bool}
  "SDL_FlipSurface" [:pointer :int] :bool)

(ffi/defcfn rotate-surface
  "SDL_Surface * SDL_RotateSurface(SDL_Surface * surface, float angle)"
  {:arglists '([surface angle]) :sdl/c "SDL_RotateSurface" :sdl/args [:pointer :float] :sdl/ret :pointer}
  "SDL_RotateSurface" [:pointer :float] :pointer)

(ffi/defcfn duplicate-surface
  "SDL_Surface * SDL_DuplicateSurface(SDL_Surface * surface)"
  {:arglists '([surface]) :sdl/c "SDL_DuplicateSurface" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_DuplicateSurface" [:pointer] :pointer)

(ffi/defcfn scale-surface
  "SDL_Surface * SDL_ScaleSurface(SDL_Surface * surface, int width, int height, SDL_ScaleMode scaleMode)"
  {:arglists '([surface width height scale-mode]) :sdl/c "SDL_ScaleSurface" :sdl/args [:pointer :int :int :int] :sdl/ret :pointer}
  "SDL_ScaleSurface" [:pointer :int :int :int] :pointer)

(ffi/defcfn convert-surface
  "SDL_Surface * SDL_ConvertSurface(SDL_Surface * surface, SDL_PixelFormat format)"
  {:arglists '([surface format]) :sdl/c "SDL_ConvertSurface" :sdl/args [:pointer :int] :sdl/ret :pointer}
  "SDL_ConvertSurface" [:pointer :int] :pointer)

(ffi/defcfn convert-surface-and-colorspace
  "SDL_Surface * SDL_ConvertSurfaceAndColorspace(SDL_Surface * surface, SDL_PixelFormat format, SDL_Palette * palette, SDL_Colorspace colorspace, SDL_PropertiesID props)"
  {:arglists '([surface format palette colorspace props]) :sdl/c "SDL_ConvertSurfaceAndColorspace" :sdl/args [:pointer :int :pointer :int :uint32] :sdl/ret :pointer}
  "SDL_ConvertSurfaceAndColorspace" [:pointer :int :pointer :int :uint32] :pointer)

(ffi/defcfn convert-pixels
  "bool SDL_ConvertPixels(int width, int height, SDL_PixelFormat src_format, const void * src, int src_pitch, SDL_PixelFormat dst_format, void * dst, int dst_pitch)"
  {:arglists '([width height src-format src src-pitch dst-format dst dst-pitch]) :sdl/c "SDL_ConvertPixels" :sdl/args [:int :int :int :pointer :int :int :pointer :int] :sdl/ret :bool}
  "SDL_ConvertPixels" [:int :int :int :pointer :int :int :pointer :int] :bool)

(ffi/defcfn convert-pixels-and-colorspace
  "bool SDL_ConvertPixelsAndColorspace(int width, int height, SDL_PixelFormat src_format, SDL_Colorspace src_colorspace, SDL_PropertiesID src_properties, const void * src, int src_pitch, SDL_PixelFormat dst_format, SDL_Colorspace dst_colorspace, SDL_PropertiesID dst_properties, void * dst, int dst_pitch)"
  {:arglists '([width height src-format src-colorspace src-properties src src-pitch dst-format dst-colorspace dst-properties dst dst-pitch]) :sdl/c "SDL_ConvertPixelsAndColorspace" :sdl/args [:int :int :int :int :uint32 :pointer :int :int :int :uint32 :pointer :int] :sdl/ret :bool}
  "SDL_ConvertPixelsAndColorspace" [:int :int :int :int :uint32 :pointer :int :int :int :uint32 :pointer :int] :bool)

(ffi/defcfn premultiply-alpha
  "bool SDL_PremultiplyAlpha(int width, int height, SDL_PixelFormat src_format, const void * src, int src_pitch, SDL_PixelFormat dst_format, void * dst, int dst_pitch, bool linear)"
  {:arglists '([width height src-format src src-pitch dst-format dst dst-pitch linear]) :sdl/c "SDL_PremultiplyAlpha" :sdl/args [:int :int :int :pointer :int :int :pointer :int :bool] :sdl/ret :bool}
  "SDL_PremultiplyAlpha" [:int :int :int :pointer :int :int :pointer :int :bool] :bool)

(ffi/defcfn premultiply-surface-alpha
  "bool SDL_PremultiplySurfaceAlpha(SDL_Surface * surface, bool linear)"
  {:arglists '([surface linear]) :sdl/c "SDL_PremultiplySurfaceAlpha" :sdl/args [:pointer :bool] :sdl/ret :bool}
  "SDL_PremultiplySurfaceAlpha" [:pointer :bool] :bool)

(ffi/defcfn clear-surface
  "bool SDL_ClearSurface(SDL_Surface * surface, float r, float g, float b, float a)"
  {:arglists '([surface r g b a]) :sdl/c "SDL_ClearSurface" :sdl/args [:pointer :float :float :float :float] :sdl/ret :bool}
  "SDL_ClearSurface" [:pointer :float :float :float :float] :bool)

(ffi/defcfn fill-surface-rect
  "bool SDL_FillSurfaceRect(SDL_Surface * dst, const SDL_Rect * rect, Uint32 color)"
  {:arglists '([dst rect color]) :sdl/c "SDL_FillSurfaceRect" :sdl/args [:pointer :pointer :uint32] :sdl/ret :bool}
  "SDL_FillSurfaceRect" [:pointer :pointer :uint32] :bool)

(ffi/defcfn fill-surface-rects
  "bool SDL_FillSurfaceRects(SDL_Surface * dst, const SDL_Rect * rects, int count, Uint32 color)"
  {:arglists '([dst rects count color]) :sdl/c "SDL_FillSurfaceRects" :sdl/args [:pointer :pointer :int :uint32] :sdl/ret :bool}
  "SDL_FillSurfaceRects" [:pointer :pointer :int :uint32] :bool)

(ffi/defcfn blit-surface
  "bool SDL_BlitSurface(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect)"
  {:arglists '([src srcrect dst dstrect]) :sdl/c "SDL_BlitSurface" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_BlitSurface" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn blit-surface-unchecked
  "bool SDL_BlitSurfaceUnchecked(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect)"
  {:arglists '([src srcrect dst dstrect]) :sdl/c "SDL_BlitSurfaceUnchecked" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_BlitSurfaceUnchecked" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn blit-surface-scaled
  "bool SDL_BlitSurfaceScaled(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode)"
  {:arglists '([src srcrect dst dstrect scale-mode]) :sdl/c "SDL_BlitSurfaceScaled" :sdl/args [:pointer :pointer :pointer :pointer :int] :sdl/ret :bool}
  "SDL_BlitSurfaceScaled" [:pointer :pointer :pointer :pointer :int] :bool)

(ffi/defcfn blit-surface-unchecked-scaled
  "bool SDL_BlitSurfaceUncheckedScaled(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode)"
  {:arglists '([src srcrect dst dstrect scale-mode]) :sdl/c "SDL_BlitSurfaceUncheckedScaled" :sdl/args [:pointer :pointer :pointer :pointer :int] :sdl/ret :bool}
  "SDL_BlitSurfaceUncheckedScaled" [:pointer :pointer :pointer :pointer :int] :bool)

(ffi/defcfn stretch-surface
  "bool SDL_StretchSurface(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode)"
  {:arglists '([src srcrect dst dstrect scale-mode]) :sdl/c "SDL_StretchSurface" :sdl/args [:pointer :pointer :pointer :pointer :int] :sdl/ret :bool}
  "SDL_StretchSurface" [:pointer :pointer :pointer :pointer :int] :bool)

(ffi/defcfn blit-surface-tiled
  "bool SDL_BlitSurfaceTiled(SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect)"
  {:arglists '([src srcrect dst dstrect]) :sdl/c "SDL_BlitSurfaceTiled" :sdl/args [:pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_BlitSurfaceTiled" [:pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn blit-surface-tiled-with-scale
  "bool SDL_BlitSurfaceTiledWithScale(SDL_Surface * src, const SDL_Rect * srcrect, float scale, SDL_ScaleMode scaleMode, SDL_Surface * dst, const SDL_Rect * dstrect)"
  {:arglists '([src srcrect scale scale-mode dst dstrect]) :sdl/c "SDL_BlitSurfaceTiledWithScale" :sdl/args [:pointer :pointer :float :int :pointer :pointer] :sdl/ret :bool}
  "SDL_BlitSurfaceTiledWithScale" [:pointer :pointer :float :int :pointer :pointer] :bool)

(ffi/defcfn blit-surface9-grid
  "bool SDL_BlitSurface9Grid(SDL_Surface * src, const SDL_Rect * srcrect, int left_width, int right_width, int top_height, int bottom_height, float scale, SDL_ScaleMode scaleMode, SDL_Surface * dst, const SDL_Rect * dstrect)"
  {:arglists '([src srcrect left-width right-width top-height bottom-height scale scale-mode dst dstrect]) :sdl/c "SDL_BlitSurface9Grid" :sdl/args [:pointer :pointer :int :int :int :int :float :int :pointer :pointer] :sdl/ret :bool}
  "SDL_BlitSurface9Grid" [:pointer :pointer :int :int :int :int :float :int :pointer :pointer] :bool)

(ffi/defcfn map-surface-rgb
  "Uint32 SDL_MapSurfaceRGB(SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b)"
  {:arglists '([surface r g b]) :sdl/c "SDL_MapSurfaceRGB" :sdl/args [:pointer :uint8 :uint8 :uint8] :sdl/ret :uint32}
  "SDL_MapSurfaceRGB" [:pointer :uint8 :uint8 :uint8] :uint32)

(ffi/defcfn map-surface-rgba
  "Uint32 SDL_MapSurfaceRGBA(SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b, Uint8 a)"
  {:arglists '([surface r g b a]) :sdl/c "SDL_MapSurfaceRGBA" :sdl/args [:pointer :uint8 :uint8 :uint8 :uint8] :sdl/ret :uint32}
  "SDL_MapSurfaceRGBA" [:pointer :uint8 :uint8 :uint8 :uint8] :uint32)

(ffi/defcfn read-surface-pixel
  "bool SDL_ReadSurfacePixel(SDL_Surface * surface, int x, int y, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a)"
  {:arglists '([surface x y r g b a]) :sdl/c "SDL_ReadSurfacePixel" :sdl/args [:pointer :int :int :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_ReadSurfacePixel" [:pointer :int :int :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn read-surface-pixel-float
  "bool SDL_ReadSurfacePixelFloat(SDL_Surface * surface, int x, int y, float * r, float * g, float * b, float * a)"
  {:arglists '([surface x y r g b a]) :sdl/c "SDL_ReadSurfacePixelFloat" :sdl/args [:pointer :int :int :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_ReadSurfacePixelFloat" [:pointer :int :int :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn write-surface-pixel
  "bool SDL_WriteSurfacePixel(SDL_Surface * surface, int x, int y, Uint8 r, Uint8 g, Uint8 b, Uint8 a)"
  {:arglists '([surface x y r g b a]) :sdl/c "SDL_WriteSurfacePixel" :sdl/args [:pointer :int :int :uint8 :uint8 :uint8 :uint8] :sdl/ret :bool}
  "SDL_WriteSurfacePixel" [:pointer :int :int :uint8 :uint8 :uint8 :uint8] :bool)

(ffi/defcfn write-surface-pixel-float
  "bool SDL_WriteSurfacePixelFloat(SDL_Surface * surface, int x, int y, float r, float g, float b, float a)"
  {:arglists '([surface x y r g b a]) :sdl/c "SDL_WriteSurfacePixelFloat" :sdl/args [:pointer :int :int :float :float :float :float] :sdl/ret :bool}
  "SDL_WriteSurfacePixelFloat" [:pointer :int :int :float :float :float :float] :bool)
