;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.system
  "Raw bindings for SDL_system.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn set-windows-message-hook
  "void SDL_SetWindowsMessageHook(SDL_WindowsMessageHook callback, void * userdata)"
  {:arglists '([callback userdata]) :sdl/c "SDL_SetWindowsMessageHook" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_SetWindowsMessageHook" [:pointer :pointer] :void)

(ffi/defcfn get-direct3-d9-adapter-index
  "int SDL_GetDirect3D9AdapterIndex(SDL_DisplayID displayID)"
  {:arglists '([display-id]) :sdl/c "SDL_GetDirect3D9AdapterIndex" :sdl/args [:uint32] :sdl/ret :int}
  "SDL_GetDirect3D9AdapterIndex" [:uint32] :int)

(ffi/defcfn get-dxgi-output-info
  "bool SDL_GetDXGIOutputInfo(SDL_DisplayID displayID, int * adapterIndex, int * outputIndex)"
  {:arglists '([display-id adapter-index output-index]) :sdl/c "SDL_GetDXGIOutputInfo" :sdl/args [:uint32 :pointer :pointer] :sdl/ret :bool}
  "SDL_GetDXGIOutputInfo" [:uint32 :pointer :pointer] :bool)

(ffi/defcfn set-x11-event-hook
  "void SDL_SetX11EventHook(SDL_X11EventHook callback, void * userdata)"
  {:arglists '([callback userdata]) :sdl/c "SDL_SetX11EventHook" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_SetX11EventHook" [:pointer :pointer] :void)

(ffi/defcfn set-linux-thread-priority
  "bool SDL_SetLinuxThreadPriority(Sint64 threadID, int priority)"
  {:arglists '([thread-id priority]) :sdl/c "SDL_SetLinuxThreadPriority" :sdl/args [:int64 :int] :sdl/ret :bool}
  "SDL_SetLinuxThreadPriority" [:int64 :int] :bool)

(ffi/defcfn set-linux-thread-priority-and-policy
  "bool SDL_SetLinuxThreadPriorityAndPolicy(Sint64 threadID, int sdlPriority, int schedPolicy)"
  {:arglists '([thread-id sdl-priority sched-policy]) :sdl/c "SDL_SetLinuxThreadPriorityAndPolicy" :sdl/args [:int64 :int :int] :sdl/ret :bool}
  "SDL_SetLinuxThreadPriorityAndPolicy" [:int64 :int :int] :bool)

(ffi/defcfn set-ios-animation-callback
  "bool SDL_SetiOSAnimationCallback(SDL_Window * window, int interval, SDL_iOSAnimationCallback callback, void * callbackParam)"
  {:arglists '([window interval callback callback-param]) :sdl/c "SDL_SetiOSAnimationCallback" :sdl/args [:pointer :int :pointer :pointer] :sdl/ret :bool}
  "SDL_SetiOSAnimationCallback" [:pointer :int :pointer :pointer] :bool)

(ffi/defcfn set-ios-event-pump
  "void SDL_SetiOSEventPump(bool enabled)"
  {:arglists '([enabled]) :sdl/c "SDL_SetiOSEventPump" :sdl/args [:bool] :sdl/ret :void}
  "SDL_SetiOSEventPump" [:bool] :void)

(ffi/defcfn get-android-jni-env
  "void * SDL_GetAndroidJNIEnv(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidJNIEnv" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetAndroidJNIEnv" [] :pointer)

(ffi/defcfn get-android-activity
  "void * SDL_GetAndroidActivity(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidActivity" :sdl/args [] :sdl/ret :pointer}
  "SDL_GetAndroidActivity" [] :pointer)

(ffi/defcfn get-android-sdk-version
  "int SDL_GetAndroidSDKVersion(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidSDKVersion" :sdl/args [] :sdl/ret :int}
  "SDL_GetAndroidSDKVersion" [] :int)

(ffi/defcfn is-chromebook
  "bool SDL_IsChromebook(void)"
  {:arglists '([]) :sdl/c "SDL_IsChromebook" :sdl/args [] :sdl/ret :bool}
  "SDL_IsChromebook" [] :bool)

(ffi/defcfn is-dex-mode
  "bool SDL_IsDeXMode(void)"
  {:arglists '([]) :sdl/c "SDL_IsDeXMode" :sdl/args [] :sdl/ret :bool}
  "SDL_IsDeXMode" [] :bool)

(ffi/defcfn send-android-back-button
  "void SDL_SendAndroidBackButton(void)"
  {:arglists '([]) :sdl/c "SDL_SendAndroidBackButton" :sdl/args [] :sdl/ret :void}
  "SDL_SendAndroidBackButton" [] :void)

(ffi/defcfn get-android-internal-storage-path
  "const char * SDL_GetAndroidInternalStoragePath(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidInternalStoragePath" :sdl/args [] :sdl/ret :string}
  "SDL_GetAndroidInternalStoragePath" [] :string)

(ffi/defcfn get-android-external-storage-state
  "Uint32 SDL_GetAndroidExternalStorageState(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidExternalStorageState" :sdl/args [] :sdl/ret :uint32}
  "SDL_GetAndroidExternalStorageState" [] :uint32)

(ffi/defcfn get-android-external-storage-path
  "const char * SDL_GetAndroidExternalStoragePath(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidExternalStoragePath" :sdl/args [] :sdl/ret :string}
  "SDL_GetAndroidExternalStoragePath" [] :string)

(ffi/defcfn get-android-cache-path
  "const char * SDL_GetAndroidCachePath(void)"
  {:arglists '([]) :sdl/c "SDL_GetAndroidCachePath" :sdl/args [] :sdl/ret :string}
  "SDL_GetAndroidCachePath" [] :string)

(ffi/defcfn request-android-permission
  "bool SDL_RequestAndroidPermission(const char * permission, SDL_RequestAndroidPermissionCallback cb, void * userdata)"
  {:arglists '([permission cb userdata]) :sdl/c "SDL_RequestAndroidPermission" :sdl/args [:string :pointer :pointer] :sdl/ret :bool}
  "SDL_RequestAndroidPermission" [:string :pointer :pointer] :bool)

(ffi/defcfn show-android-toast
  "bool SDL_ShowAndroidToast(const char * message, int duration, int gravity, int xoffset, int yoffset)"
  {:arglists '([message duration gravity xoffset yoffset]) :sdl/c "SDL_ShowAndroidToast" :sdl/args [:string :int :int :int :int] :sdl/ret :bool}
  "SDL_ShowAndroidToast" [:string :int :int :int :int] :bool)

(ffi/defcfn send-android-message
  "bool SDL_SendAndroidMessage(Uint32 command, int param)"
  {:arglists '([command param]) :sdl/c "SDL_SendAndroidMessage" :sdl/args [:uint32 :int] :sdl/ret :bool}
  "SDL_SendAndroidMessage" [:uint32 :int] :bool)

(ffi/defcfn is-tablet
  "bool SDL_IsTablet(void)"
  {:arglists '([]) :sdl/c "SDL_IsTablet" :sdl/args [] :sdl/ret :bool}
  "SDL_IsTablet" [] :bool)

(ffi/defcfn is-tv
  "bool SDL_IsTV(void)"
  {:arglists '([]) :sdl/c "SDL_IsTV" :sdl/args [] :sdl/ret :bool}
  "SDL_IsTV" [] :bool)

(ffi/defcfn get-sandbox
  "SDL_Sandbox SDL_GetSandbox(void)"
  {:arglists '([]) :sdl/c "SDL_GetSandbox" :sdl/args [] :sdl/ret :int}
  "SDL_GetSandbox" [] :int)

(ffi/defcfn on-application-will-terminate
  "void SDL_OnApplicationWillTerminate(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationWillTerminate" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationWillTerminate" [] :void)

(ffi/defcfn on-application-did-receive-memory-warning
  "void SDL_OnApplicationDidReceiveMemoryWarning(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationDidReceiveMemoryWarning" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationDidReceiveMemoryWarning" [] :void)

(ffi/defcfn on-application-will-enter-background
  "void SDL_OnApplicationWillEnterBackground(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationWillEnterBackground" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationWillEnterBackground" [] :void)

(ffi/defcfn on-application-did-enter-background
  "void SDL_OnApplicationDidEnterBackground(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationDidEnterBackground" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationDidEnterBackground" [] :void)

(ffi/defcfn on-application-will-enter-foreground
  "void SDL_OnApplicationWillEnterForeground(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationWillEnterForeground" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationWillEnterForeground" [] :void)

(ffi/defcfn on-application-did-enter-foreground
  "void SDL_OnApplicationDidEnterForeground(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationDidEnterForeground" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationDidEnterForeground" [] :void)

(ffi/defcfn on-application-did-change-status-bar-orientation
  "void SDL_OnApplicationDidChangeStatusBarOrientation(void)"
  {:arglists '([]) :sdl/c "SDL_OnApplicationDidChangeStatusBarOrientation" :sdl/args [] :sdl/ret :void}
  "SDL_OnApplicationDidChangeStatusBarOrientation" [] :void)

(ffi/defcfn get-gdk-task-queue
  "bool SDL_GetGDKTaskQueue(XTaskQueueHandle * outTaskQueue)"
  {:arglists '([out-task-queue]) :sdl/c "SDL_GetGDKTaskQueue" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GetGDKTaskQueue" [:pointer] :bool)

(ffi/defcfn get-gdk-default-user
  "bool SDL_GetGDKDefaultUser(XUserHandle * outUserHandle)"
  {:arglists '([out-user-handle]) :sdl/c "SDL_GetGDKDefaultUser" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GetGDKDefaultUser" [:pointer] :bool)
