;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.thread
  "Raw bindings for SDL_thread.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn create-thread
  "SDL_Thread * SDL_CreateThread(SDL_ThreadFunction fn, const char * name, void * data)"
  {:arglists '([fn name data]) :sdl/c "SDL_CreateThread" :sdl/args [:pointer :string :pointer] :sdl/ret :pointer}
  "SDL_CreateThread" [:pointer :string :pointer] :pointer)

(ffi/defcfn create-thread-with-properties
  "SDL_Thread * SDL_CreateThreadWithProperties(SDL_PropertiesID props)"
  {:arglists '([props]) :sdl/c "SDL_CreateThreadWithProperties" :sdl/args [:uint32] :sdl/ret :pointer}
  "SDL_CreateThreadWithProperties" [:uint32] :pointer)

(ffi/defcfn create-thread-runtime
  "SDL_Thread * SDL_CreateThreadRuntime(SDL_ThreadFunction fn, const char * name, void * data, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)"
  {:arglists '([fn name data pfn-begin-thread pfn-end-thread]) :sdl/c "SDL_CreateThreadRuntime" :sdl/args [:pointer :string :pointer :pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateThreadRuntime" [:pointer :string :pointer :pointer :pointer] :pointer)

(ffi/defcfn create-thread-with-properties-runtime
  "SDL_Thread * SDL_CreateThreadWithPropertiesRuntime(SDL_PropertiesID props, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)"
  {:arglists '([props pfn-begin-thread pfn-end-thread]) :sdl/c "SDL_CreateThreadWithPropertiesRuntime" :sdl/args [:uint32 :pointer :pointer] :sdl/ret :pointer}
  "SDL_CreateThreadWithPropertiesRuntime" [:uint32 :pointer :pointer] :pointer)

(ffi/defcfn get-thread-name
  "const char * SDL_GetThreadName(SDL_Thread * thread)"
  {:arglists '([thread]) :sdl/c "SDL_GetThreadName" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetThreadName" [:pointer] :string)

(ffi/defcfn get-current-thread-id
  "SDL_ThreadID SDL_GetCurrentThreadID(void)"
  {:arglists '([]) :sdl/c "SDL_GetCurrentThreadID" :sdl/args [] :sdl/ret :uint64}
  "SDL_GetCurrentThreadID" [] :uint64)

(ffi/defcfn get-thread-id
  "SDL_ThreadID SDL_GetThreadID(SDL_Thread * thread)"
  {:arglists '([thread]) :sdl/c "SDL_GetThreadID" :sdl/args [:pointer] :sdl/ret :uint64}
  "SDL_GetThreadID" [:pointer] :uint64)

(ffi/defcfn set-current-thread-priority
  "bool SDL_SetCurrentThreadPriority(SDL_ThreadPriority priority)"
  {:arglists '([priority]) :sdl/c "SDL_SetCurrentThreadPriority" :sdl/args [:int] :sdl/ret :bool}
  "SDL_SetCurrentThreadPriority" [:int] :bool)

(ffi/defcfn wait-thread
  "void SDL_WaitThread(SDL_Thread * thread, int * status)"
  {:arglists '([thread status]) :sdl/c "SDL_WaitThread" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_WaitThread" [:pointer :pointer] :void :blocking)

(ffi/defcfn get-thread-state
  "SDL_ThreadState SDL_GetThreadState(SDL_Thread * thread)"
  {:arglists '([thread]) :sdl/c "SDL_GetThreadState" :sdl/args [:pointer] :sdl/ret :int}
  "SDL_GetThreadState" [:pointer] :int)

(ffi/defcfn detach-thread
  "void SDL_DetachThread(SDL_Thread * thread)"
  {:arglists '([thread]) :sdl/c "SDL_DetachThread" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DetachThread" [:pointer] :void)

(ffi/defcfn get-tls
  "void * SDL_GetTLS(SDL_TLSID * id)"
  {:arglists '([id]) :sdl/c "SDL_GetTLS" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTLS" [:pointer] :pointer)

(ffi/defcfn set-tls
  "bool SDL_SetTLS(SDL_TLSID * id, const void * value, SDL_TLSDestructorCallback destructor)"
  {:arglists '([id value destructor]) :sdl/c "SDL_SetTLS" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "SDL_SetTLS" [:pointer :pointer :pointer] :bool)

(ffi/defcfn cleanup-tls
  "void SDL_CleanupTLS(void)"
  {:arglists '([]) :sdl/c "SDL_CleanupTLS" :sdl/args [] :sdl/ret :void}
  "SDL_CleanupTLS" [] :void)
