;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.timer
  "Raw bindings for SDL_timer.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:refer-clojure :exclude [delay])
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-ticks
  "Uint64 SDL_GetTicks(void)"
  {:arglists '([]) :sdl/c "SDL_GetTicks" :sdl/args [] :sdl/ret :uint64}
  "SDL_GetTicks" [] :uint64)

(ffi/defcfn get-ticks-ns
  "Uint64 SDL_GetTicksNS(void)"
  {:arglists '([]) :sdl/c "SDL_GetTicksNS" :sdl/args [] :sdl/ret :uint64}
  "SDL_GetTicksNS" [] :uint64)

(ffi/defcfn get-performance-counter
  "Uint64 SDL_GetPerformanceCounter(void)"
  {:arglists '([]) :sdl/c "SDL_GetPerformanceCounter" :sdl/args [] :sdl/ret :uint64}
  "SDL_GetPerformanceCounter" [] :uint64)

(ffi/defcfn get-performance-frequency
  "Uint64 SDL_GetPerformanceFrequency(void)"
  {:arglists '([]) :sdl/c "SDL_GetPerformanceFrequency" :sdl/args [] :sdl/ret :uint64}
  "SDL_GetPerformanceFrequency" [] :uint64)

(ffi/defcfn delay
  "void SDL_Delay(Uint32 ms)"
  {:arglists '([ms]) :sdl/c "SDL_Delay" :sdl/args [:uint32] :sdl/ret :void}
  "SDL_Delay" [:uint32] :void :blocking)

(ffi/defcfn delay-ns
  "void SDL_DelayNS(Uint64 ns)"
  {:arglists '([ns]) :sdl/c "SDL_DelayNS" :sdl/args [:uint64] :sdl/ret :void}
  "SDL_DelayNS" [:uint64] :void :blocking)

(ffi/defcfn delay-precise
  "void SDL_DelayPrecise(Uint64 ns)"
  {:arglists '([ns]) :sdl/c "SDL_DelayPrecise" :sdl/args [:uint64] :sdl/ret :void}
  "SDL_DelayPrecise" [:uint64] :void :blocking)

(ffi/defcfn add-timer
  "SDL_TimerID SDL_AddTimer(Uint32 interval, SDL_TimerCallback callback, void * userdata)"
  {:arglists '([interval callback userdata]) :sdl/c "SDL_AddTimer" :sdl/args [:uint32 :pointer :pointer] :sdl/ret :uint32}
  "SDL_AddTimer" [:uint32 :pointer :pointer] :uint32)

(ffi/defcfn add-timer-ns
  "SDL_TimerID SDL_AddTimerNS(Uint64 interval, SDL_NSTimerCallback callback, void * userdata)"
  {:arglists '([interval callback userdata]) :sdl/c "SDL_AddTimerNS" :sdl/args [:uint64 :pointer :pointer] :sdl/ret :uint32}
  "SDL_AddTimerNS" [:uint64 :pointer :pointer] :uint32)

(ffi/defcfn remove-timer
  "bool SDL_RemoveTimer(SDL_TimerID id)"
  {:arglists '([id]) :sdl/c "SDL_RemoveTimer" :sdl/args [:uint32] :sdl/ret :bool}
  "SDL_RemoveTimer" [:uint32] :bool)
