;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.time
  "Raw bindings for SDL_time.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def date-time
  "ffi/layout of SDL_DateTime."
  (ffi/layout [:struct [[:year :int] [:month :int] [:day :int] [:hour :int] [:minute :int] [:second :int] [:nanosecond :int] [:day-of-week :int] [:utc-offset :int]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-date-time-locale-preferences
  "bool SDL_GetDateTimeLocalePreferences(SDL_DateFormat * dateFormat, SDL_TimeFormat * timeFormat)"
  {:arglists '([date-format time-format]) :sdl/c "SDL_GetDateTimeLocalePreferences" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_GetDateTimeLocalePreferences" [:pointer :pointer] :bool)

(ffi/defcfn get-current-time
  "bool SDL_GetCurrentTime(SDL_Time * ticks)"
  {:arglists '([ticks]) :sdl/c "SDL_GetCurrentTime" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GetCurrentTime" [:pointer] :bool)

(ffi/defcfn time-to-date-time
  "bool SDL_TimeToDateTime(SDL_Time ticks, SDL_DateTime * dt, bool localTime)"
  {:arglists '([ticks dt local-time]) :sdl/c "SDL_TimeToDateTime" :sdl/args [:int64 :pointer :bool] :sdl/ret :bool}
  "SDL_TimeToDateTime" [:int64 :pointer :bool] :bool)

(ffi/defcfn date-time-to-time
  "bool SDL_DateTimeToTime(const SDL_DateTime * dt, SDL_Time * ticks)"
  {:arglists '([dt ticks]) :sdl/c "SDL_DateTimeToTime" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "SDL_DateTimeToTime" [:pointer :pointer] :bool)

(ffi/defcfn time-to-windows
  "void SDL_TimeToWindows(SDL_Time ticks, Uint32 * dwLowDateTime, Uint32 * dwHighDateTime)"
  {:arglists '([ticks dw-low-date-time dw-high-date-time]) :sdl/c "SDL_TimeToWindows" :sdl/args [:int64 :pointer :pointer] :sdl/ret :void}
  "SDL_TimeToWindows" [:int64 :pointer :pointer] :void)

(ffi/defcfn time-from-windows
  "SDL_Time SDL_TimeFromWindows(Uint32 dwLowDateTime, Uint32 dwHighDateTime)"
  {:arglists '([dw-low-date-time dw-high-date-time]) :sdl/c "SDL_TimeFromWindows" :sdl/args [:uint32 :uint32] :sdl/ret :int64}
  "SDL_TimeFromWindows" [:uint32 :uint32] :int64)

(ffi/defcfn get-days-in-month
  "int SDL_GetDaysInMonth(int year, int month)"
  {:arglists '([year month]) :sdl/c "SDL_GetDaysInMonth" :sdl/args [:int :int] :sdl/ret :int}
  "SDL_GetDaysInMonth" [:int :int] :int)

(ffi/defcfn get-day-of-year
  "int SDL_GetDayOfYear(int year, int month, int day)"
  {:arglists '([year month day]) :sdl/c "SDL_GetDayOfYear" :sdl/args [:int :int :int] :sdl/ret :int}
  "SDL_GetDayOfYear" [:int :int :int] :int)

(ffi/defcfn get-day-of-week
  "int SDL_GetDayOfWeek(int year, int month, int day)"
  {:arglists '([year month day]) :sdl/c "SDL_GetDayOfWeek" :sdl/args [:int :int :int] :sdl/ret :int}
  "SDL_GetDayOfWeek" [:int :int :int] :int)
