;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.touch
  "Raw bindings for SDL_touch.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def finger
  "ffi/layout of SDL_Finger."
  (ffi/layout [:struct [[:id :uint64] [:x :float] [:y :float] [:pressure :float]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn get-touch-devices
  "SDL_TouchID * SDL_GetTouchDevices(int * count)"
  {:arglists '([count]) :sdl/c "SDL_GetTouchDevices" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTouchDevices" [:pointer] :pointer)

(ffi/defcfn get-touch-device-name
  "const char * SDL_GetTouchDeviceName(SDL_TouchID touchID)"
  {:arglists '([touch-id]) :sdl/c "SDL_GetTouchDeviceName" :sdl/args [:uint64] :sdl/ret :string}
  "SDL_GetTouchDeviceName" [:uint64] :string)

(ffi/defcfn get-touch-device-type
  "SDL_TouchDeviceType SDL_GetTouchDeviceType(SDL_TouchID touchID)"
  {:arglists '([touch-id]) :sdl/c "SDL_GetTouchDeviceType" :sdl/args [:uint64] :sdl/ret :int}
  "SDL_GetTouchDeviceType" [:uint64] :int)

(ffi/defcfn get-touch-fingers
  "SDL_Finger ** SDL_GetTouchFingers(SDL_TouchID touchID, int * count)"
  {:arglists '([touch-id count]) :sdl/c "SDL_GetTouchFingers" :sdl/args [:uint64 :pointer] :sdl/ret :pointer}
  "SDL_GetTouchFingers" [:uint64 :pointer] :pointer)
