;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.tray
  "Raw bindings for SDL_tray.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn create-tray
  "SDL_Tray * SDL_CreateTray(SDL_Surface * icon, const char * tooltip)"
  {:arglists '([icon tooltip]) :sdl/c "SDL_CreateTray" :sdl/args [:pointer :string] :sdl/ret :pointer}
  "SDL_CreateTray" [:pointer :string] :pointer)

(ffi/defcfn set-tray-icon
  "void SDL_SetTrayIcon(SDL_Tray * tray, SDL_Surface * icon)"
  {:arglists '([tray icon]) :sdl/c "SDL_SetTrayIcon" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "SDL_SetTrayIcon" [:pointer :pointer] :void)

(ffi/defcfn set-tray-tooltip
  "void SDL_SetTrayTooltip(SDL_Tray * tray, const char * tooltip)"
  {:arglists '([tray tooltip]) :sdl/c "SDL_SetTrayTooltip" :sdl/args [:pointer :string] :sdl/ret :void}
  "SDL_SetTrayTooltip" [:pointer :string] :void)

(ffi/defcfn create-tray-menu
  "SDL_TrayMenu * SDL_CreateTrayMenu(SDL_Tray * tray)"
  {:arglists '([tray]) :sdl/c "SDL_CreateTrayMenu" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_CreateTrayMenu" [:pointer] :pointer)

(ffi/defcfn create-tray-submenu
  "SDL_TrayMenu * SDL_CreateTraySubmenu(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_CreateTraySubmenu" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_CreateTraySubmenu" [:pointer] :pointer)

(ffi/defcfn get-tray-menu
  "SDL_TrayMenu * SDL_GetTrayMenu(SDL_Tray * tray)"
  {:arglists '([tray]) :sdl/c "SDL_GetTrayMenu" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTrayMenu" [:pointer] :pointer)

(ffi/defcfn get-tray-submenu
  "SDL_TrayMenu * SDL_GetTraySubmenu(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_GetTraySubmenu" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTraySubmenu" [:pointer] :pointer)

(ffi/defcfn get-tray-entries
  "const SDL_TrayEntry ** SDL_GetTrayEntries(SDL_TrayMenu * menu, int * count)"
  {:arglists '([menu count]) :sdl/c "SDL_GetTrayEntries" :sdl/args [:pointer :pointer] :sdl/ret :pointer}
  "SDL_GetTrayEntries" [:pointer :pointer] :pointer)

(ffi/defcfn remove-tray-entry
  "void SDL_RemoveTrayEntry(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_RemoveTrayEntry" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_RemoveTrayEntry" [:pointer] :void)

(ffi/defcfn insert-tray-entry-at
  "SDL_TrayEntry * SDL_InsertTrayEntryAt(SDL_TrayMenu * menu, int pos, const char * label, SDL_TrayEntryFlags flags)"
  {:arglists '([menu pos label flags]) :sdl/c "SDL_InsertTrayEntryAt" :sdl/args [:pointer :int :string :uint32] :sdl/ret :pointer}
  "SDL_InsertTrayEntryAt" [:pointer :int :string :uint32] :pointer)

(ffi/defcfn set-tray-entry-label
  "void SDL_SetTrayEntryLabel(SDL_TrayEntry * entry, const char * label)"
  {:arglists '([entry label]) :sdl/c "SDL_SetTrayEntryLabel" :sdl/args [:pointer :string] :sdl/ret :void}
  "SDL_SetTrayEntryLabel" [:pointer :string] :void)

(ffi/defcfn get-tray-entry-label
  "const char * SDL_GetTrayEntryLabel(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_GetTrayEntryLabel" :sdl/args [:pointer] :sdl/ret :string}
  "SDL_GetTrayEntryLabel" [:pointer] :string)

(ffi/defcfn set-tray-entry-checked
  "void SDL_SetTrayEntryChecked(SDL_TrayEntry * entry, bool checked)"
  {:arglists '([entry checked]) :sdl/c "SDL_SetTrayEntryChecked" :sdl/args [:pointer :bool] :sdl/ret :void}
  "SDL_SetTrayEntryChecked" [:pointer :bool] :void)

(ffi/defcfn get-tray-entry-checked
  "bool SDL_GetTrayEntryChecked(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_GetTrayEntryChecked" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GetTrayEntryChecked" [:pointer] :bool)

(ffi/defcfn set-tray-entry-enabled
  "void SDL_SetTrayEntryEnabled(SDL_TrayEntry * entry, bool enabled)"
  {:arglists '([entry enabled]) :sdl/c "SDL_SetTrayEntryEnabled" :sdl/args [:pointer :bool] :sdl/ret :void}
  "SDL_SetTrayEntryEnabled" [:pointer :bool] :void)

(ffi/defcfn get-tray-entry-enabled
  "bool SDL_GetTrayEntryEnabled(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_GetTrayEntryEnabled" :sdl/args [:pointer] :sdl/ret :bool}
  "SDL_GetTrayEntryEnabled" [:pointer] :bool)

(ffi/defcfn set-tray-entry-callback
  "void SDL_SetTrayEntryCallback(SDL_TrayEntry * entry, SDL_TrayCallback callback, void * userdata)"
  {:arglists '([entry callback userdata]) :sdl/c "SDL_SetTrayEntryCallback" :sdl/args [:pointer :pointer :pointer] :sdl/ret :void}
  "SDL_SetTrayEntryCallback" [:pointer :pointer :pointer] :void)

(ffi/defcfn click-tray-entry
  "void SDL_ClickTrayEntry(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_ClickTrayEntry" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_ClickTrayEntry" [:pointer] :void)

(ffi/defcfn destroy-tray
  "void SDL_DestroyTray(SDL_Tray * tray)"
  {:arglists '([tray]) :sdl/c "SDL_DestroyTray" :sdl/args [:pointer] :sdl/ret :void}
  "SDL_DestroyTray" [:pointer] :void)

(ffi/defcfn get-tray-entry-parent
  "SDL_TrayMenu * SDL_GetTrayEntryParent(SDL_TrayEntry * entry)"
  {:arglists '([entry]) :sdl/c "SDL_GetTrayEntryParent" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTrayEntryParent" [:pointer] :pointer)

(ffi/defcfn get-tray-menu-parent-entry
  "SDL_TrayEntry * SDL_GetTrayMenuParentEntry(SDL_TrayMenu * menu)"
  {:arglists '([menu]) :sdl/c "SDL_GetTrayMenuParentEntry" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTrayMenuParentEntry" [:pointer] :pointer)

(ffi/defcfn get-tray-menu-parent-tray
  "SDL_Tray * SDL_GetTrayMenuParentTray(SDL_TrayMenu * menu)"
  {:arglists '([menu]) :sdl/c "SDL_GetTrayMenuParentTray" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_GetTrayMenuParentTray" [:pointer] :pointer)

(ffi/defcfn update-trays
  "void SDL_UpdateTrays(void)"
  {:arglists '([]) :sdl/c "SDL_UpdateTrays" :sdl/args [] :sdl/ret :void}
  "SDL_UpdateTrays" [] :void)
