;; GENERATED by tools/gen.clj from the SDL_ttf headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from SDL_ttf, Copyright (C) 2001-2025
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.ttf
  "Raw bindings for SDL_ttf.h, SDL_textengine.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its TTF_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- structs -------------------------------------------------------------

(def text
  "ffi/layout of TTF_Text."
  (ffi/layout [:struct [[:text :pointer] [:num-lines :int] [:refcount :int] [:internal :pointer]]]))

(def gpu-atlas-draw-sequence
  "ffi/layout of TTF_GPUAtlasDrawSequence."
  (ffi/layout [:struct [[:atlas-texture :pointer] [:xy :pointer] [:uv :pointer] [:num-vertices :int] [:indices :pointer] [:num-indices :int] [:image-type :int] [:next :pointer]]]))

(def sub-string
  "ffi/layout of TTF_SubString."
  (ffi/layout [:struct [[:flags :uint32] [:offset :int] [:length :int] [:line-index :int] [:cluster-index :int] [:rect [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]]]]))

(def fill-operation
  "ffi/layout of TTF_FillOperation."
  (ffi/layout [:struct [[:cmd :int] [:rect [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]]]]))

(def copy-operation
  "ffi/layout of TTF_CopyOperation."
  (ffi/layout [:struct [[:cmd :int] [:text-offset :int] [:glyph-font :pointer] [:glyph-index :uint32] [:src [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]] [:dst [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]] [:reserved :pointer]]]))

(def draw-operation
  "ffi/layout of TTF_DrawOperation."
  (ffi/layout [:union [[:cmd :int] [:fill [:struct [[:cmd :int] [:rect [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]]]]] [:copy [:struct [[:cmd :int] [:text-offset :int] [:glyph-font :pointer] [:glyph-index :uint32] [:src [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]] [:dst [:struct [[:x :int] [:y :int] [:w :int] [:h :int]]]] [:reserved :pointer]]]]]]))

(def text-data
  "ffi/layout of TTF_TextData."
  (ffi/layout [:struct [[:font :pointer] [:color [:struct [[:r :float] [:g :float] [:b :float] [:a :float]]]] [:needs-layout-update :bool] [:layout :pointer] [:x :int] [:y :int] [:w :int] [:h :int] [:num-ops :int] [:ops :pointer] [:num-clusters :int] [:clusters :pointer] [:props :uint32] [:needs-engine-update :bool] [:engine :pointer] [:engine-text :pointer]]]))

(def text-engine
  "ffi/layout of TTF_TextEngine."
  (ffi/layout [:struct [[:version :uint32] [:userdata :pointer] [:create-text :pointer] [:destroy-text :pointer]]]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn version
  "int TTF_Version(void)"
  {:arglists '([]) :sdl/c "TTF_Version" :sdl/args [] :sdl/ret :int}
  "TTF_Version" [] :int)

(ffi/defcfn get-freetype-version
  "void TTF_GetFreeTypeVersion(int * major, int * minor, int * patch)"
  {:arglists '([major minor patch]) :sdl/c "TTF_GetFreeTypeVersion" :sdl/args [:pointer :pointer :pointer] :sdl/ret :void}
  "TTF_GetFreeTypeVersion" [:pointer :pointer :pointer] :void)

(ffi/defcfn get-harfbuzz-version
  "void TTF_GetHarfBuzzVersion(int * major, int * minor, int * patch)"
  {:arglists '([major minor patch]) :sdl/c "TTF_GetHarfBuzzVersion" :sdl/args [:pointer :pointer :pointer] :sdl/ret :void}
  "TTF_GetHarfBuzzVersion" [:pointer :pointer :pointer] :void)

(ffi/defcfn init
  "bool TTF_Init(void)"
  {:arglists '([]) :sdl/c "TTF_Init" :sdl/args [] :sdl/ret :bool}
  "TTF_Init" [] :bool)

(ffi/defcfn open-font
  "TTF_Font * TTF_OpenFont(const char * file, float ptsize)"
  {:arglists '([file ptsize]) :sdl/c "TTF_OpenFont" :sdl/args [:string :float] :sdl/ret :pointer}
  "TTF_OpenFont" [:string :float] :pointer)

(ffi/defcfn open-font-io
  "TTF_Font * TTF_OpenFontIO(SDL_IOStream * src, bool closeio, float ptsize)"
  {:arglists '([src closeio ptsize]) :sdl/c "TTF_OpenFontIO" :sdl/args [:pointer :bool :float] :sdl/ret :pointer}
  "TTF_OpenFontIO" [:pointer :bool :float] :pointer)

(ffi/defcfn open-font-with-properties
  "TTF_Font * TTF_OpenFontWithProperties(SDL_PropertiesID props)"
  {:arglists '([props]) :sdl/c "TTF_OpenFontWithProperties" :sdl/args [:uint32] :sdl/ret :pointer}
  "TTF_OpenFontWithProperties" [:uint32] :pointer)

(ffi/defcfn copy-font
  "TTF_Font * TTF_CopyFont(TTF_Font * existing_font)"
  {:arglists '([existing-font]) :sdl/c "TTF_CopyFont" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_CopyFont" [:pointer] :pointer)

(ffi/defcfn get-font-properties
  "SDL_PropertiesID TTF_GetFontProperties(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetFontProperties" [:pointer] :uint32)

(ffi/defcfn get-font-generation
  "Uint32 TTF_GetFontGeneration(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontGeneration" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetFontGeneration" [:pointer] :uint32)

(ffi/defcfn add-fallback-font
  "bool TTF_AddFallbackFont(TTF_Font * font, TTF_Font * fallback)"
  {:arglists '([font fallback]) :sdl/c "TTF_AddFallbackFont" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "TTF_AddFallbackFont" [:pointer :pointer] :bool)

(ffi/defcfn remove-fallback-font
  "void TTF_RemoveFallbackFont(TTF_Font * font, TTF_Font * fallback)"
  {:arglists '([font fallback]) :sdl/c "TTF_RemoveFallbackFont" :sdl/args [:pointer :pointer] :sdl/ret :void}
  "TTF_RemoveFallbackFont" [:pointer :pointer] :void)

(ffi/defcfn clear-fallback-fonts
  "void TTF_ClearFallbackFonts(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_ClearFallbackFonts" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_ClearFallbackFonts" [:pointer] :void)

(ffi/defcfn set-font-size
  "bool TTF_SetFontSize(TTF_Font * font, float ptsize)"
  {:arglists '([font ptsize]) :sdl/c "TTF_SetFontSize" :sdl/args [:pointer :float] :sdl/ret :bool}
  "TTF_SetFontSize" [:pointer :float] :bool)

(ffi/defcfn set-font-size-dpi
  "bool TTF_SetFontSizeDPI(TTF_Font * font, float ptsize, int hdpi, int vdpi)"
  {:arglists '([font ptsize hdpi vdpi]) :sdl/c "TTF_SetFontSizeDPI" :sdl/args [:pointer :float :int :int] :sdl/ret :bool}
  "TTF_SetFontSizeDPI" [:pointer :float :int :int] :bool)

(ffi/defcfn get-font-size
  "float TTF_GetFontSize(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontSize" :sdl/args [:pointer] :sdl/ret :float}
  "TTF_GetFontSize" [:pointer] :float)

(ffi/defcfn get-font-dpi
  "bool TTF_GetFontDPI(TTF_Font * font, int * hdpi, int * vdpi)"
  {:arglists '([font hdpi vdpi]) :sdl/c "TTF_GetFontDPI" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetFontDPI" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-font-style
  "void TTF_SetFontStyle(TTF_Font * font, TTF_FontStyleFlags style)"
  {:arglists '([font style]) :sdl/c "TTF_SetFontStyle" :sdl/args [:pointer :uint32] :sdl/ret :void}
  "TTF_SetFontStyle" [:pointer :uint32] :void)

(ffi/defcfn get-font-style
  "TTF_FontStyleFlags TTF_GetFontStyle(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontStyle" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetFontStyle" [:pointer] :uint32)

(ffi/defcfn set-font-outline
  "bool TTF_SetFontOutline(TTF_Font * font, int outline)"
  {:arglists '([font outline]) :sdl/c "TTF_SetFontOutline" :sdl/args [:pointer :int] :sdl/ret :bool}
  "TTF_SetFontOutline" [:pointer :int] :bool)

(ffi/defcfn get-font-outline
  "int TTF_GetFontOutline(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontOutline" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontOutline" [:pointer] :int)

(ffi/defcfn set-font-hinting
  "void TTF_SetFontHinting(TTF_Font * font, TTF_HintingFlags hinting)"
  {:arglists '([font hinting]) :sdl/c "TTF_SetFontHinting" :sdl/args [:pointer :int] :sdl/ret :void}
  "TTF_SetFontHinting" [:pointer :int] :void)

(ffi/defcfn get-num-font-faces
  "int TTF_GetNumFontFaces(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetNumFontFaces" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetNumFontFaces" [:pointer] :int)

(ffi/defcfn get-font-hinting
  "TTF_HintingFlags TTF_GetFontHinting(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontHinting" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontHinting" [:pointer] :int)

(ffi/defcfn set-font-sdf
  "bool TTF_SetFontSDF(TTF_Font * font, bool enabled)"
  {:arglists '([font enabled]) :sdl/c "TTF_SetFontSDF" :sdl/args [:pointer :bool] :sdl/ret :bool}
  "TTF_SetFontSDF" [:pointer :bool] :bool)

(ffi/defcfn get-font-sdf
  "bool TTF_GetFontSDF(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontSDF" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_GetFontSDF" [:pointer] :bool)

(ffi/defcfn get-font-weight
  "int TTF_GetFontWeight(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontWeight" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontWeight" [:pointer] :int)

(ffi/defcfn set-font-wrap-alignment
  "void TTF_SetFontWrapAlignment(TTF_Font * font, TTF_HorizontalAlignment align)"
  {:arglists '([font align]) :sdl/c "TTF_SetFontWrapAlignment" :sdl/args [:pointer :int] :sdl/ret :void}
  "TTF_SetFontWrapAlignment" [:pointer :int] :void)

(ffi/defcfn get-font-wrap-alignment
  "TTF_HorizontalAlignment TTF_GetFontWrapAlignment(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontWrapAlignment" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontWrapAlignment" [:pointer] :int)

(ffi/defcfn get-font-height
  "int TTF_GetFontHeight(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontHeight" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontHeight" [:pointer] :int)

(ffi/defcfn get-font-ascent
  "int TTF_GetFontAscent(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontAscent" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontAscent" [:pointer] :int)

(ffi/defcfn get-font-descent
  "int TTF_GetFontDescent(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontDescent" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontDescent" [:pointer] :int)

(ffi/defcfn set-font-line-skip
  "void TTF_SetFontLineSkip(TTF_Font * font, int lineskip)"
  {:arglists '([font lineskip]) :sdl/c "TTF_SetFontLineSkip" :sdl/args [:pointer :int] :sdl/ret :void}
  "TTF_SetFontLineSkip" [:pointer :int] :void)

(ffi/defcfn get-font-line-skip
  "int TTF_GetFontLineSkip(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontLineSkip" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontLineSkip" [:pointer] :int)

(ffi/defcfn set-font-kerning
  "void TTF_SetFontKerning(TTF_Font * font, bool enabled)"
  {:arglists '([font enabled]) :sdl/c "TTF_SetFontKerning" :sdl/args [:pointer :bool] :sdl/ret :void}
  "TTF_SetFontKerning" [:pointer :bool] :void)

(ffi/defcfn get-font-kerning
  "bool TTF_GetFontKerning(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontKerning" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_GetFontKerning" [:pointer] :bool)

(ffi/defcfn font-is-fixed-width
  "bool TTF_FontIsFixedWidth(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_FontIsFixedWidth" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_FontIsFixedWidth" [:pointer] :bool)

(ffi/defcfn font-is-scalable
  "bool TTF_FontIsScalable(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_FontIsScalable" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_FontIsScalable" [:pointer] :bool)

(ffi/defcfn get-font-family-name
  "const char * TTF_GetFontFamilyName(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontFamilyName" :sdl/args [:pointer] :sdl/ret :string}
  "TTF_GetFontFamilyName" [:pointer] :string)

(ffi/defcfn get-font-style-name
  "const char * TTF_GetFontStyleName(const TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontStyleName" :sdl/args [:pointer] :sdl/ret :string}
  "TTF_GetFontStyleName" [:pointer] :string)

(ffi/defcfn set-font-direction
  "bool TTF_SetFontDirection(TTF_Font * font, TTF_Direction direction)"
  {:arglists '([font direction]) :sdl/c "TTF_SetFontDirection" :sdl/args [:pointer :int] :sdl/ret :bool}
  "TTF_SetFontDirection" [:pointer :int] :bool)

(ffi/defcfn get-font-direction
  "TTF_Direction TTF_GetFontDirection(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontDirection" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetFontDirection" [:pointer] :int)

(ffi/defcfn string-to-tag
  "Uint32 TTF_StringToTag(const char * string)"
  {:arglists '([string]) :sdl/c "TTF_StringToTag" :sdl/args [:string] :sdl/ret :uint32}
  "TTF_StringToTag" [:string] :uint32)

(ffi/defcfn tag-to-string
  "void TTF_TagToString(Uint32 tag, char * string, size_t size)"
  {:arglists '([tag string size]) :sdl/c "TTF_TagToString" :sdl/args [:uint32 :pointer :size_t] :sdl/ret :void}
  "TTF_TagToString" [:uint32 :pointer :size_t] :void)

(ffi/defcfn set-font-script
  "bool TTF_SetFontScript(TTF_Font * font, Uint32 script)"
  {:arglists '([font script]) :sdl/c "TTF_SetFontScript" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "TTF_SetFontScript" [:pointer :uint32] :bool)

(ffi/defcfn get-font-script
  "Uint32 TTF_GetFontScript(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_GetFontScript" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetFontScript" [:pointer] :uint32)

(ffi/defcfn get-glyph-script
  "Uint32 TTF_GetGlyphScript(Uint32 ch)"
  {:arglists '([ch]) :sdl/c "TTF_GetGlyphScript" :sdl/args [:uint32] :sdl/ret :uint32}
  "TTF_GetGlyphScript" [:uint32] :uint32)

(ffi/defcfn set-font-language
  "bool TTF_SetFontLanguage(TTF_Font * font, const char * language_bcp47)"
  {:arglists '([font language-bcp47]) :sdl/c "TTF_SetFontLanguage" :sdl/args [:pointer :string] :sdl/ret :bool}
  "TTF_SetFontLanguage" [:pointer :string] :bool)

(ffi/defcfn font-has-glyph
  "bool TTF_FontHasGlyph(TTF_Font * font, Uint32 ch)"
  {:arglists '([font ch]) :sdl/c "TTF_FontHasGlyph" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "TTF_FontHasGlyph" [:pointer :uint32] :bool)

(ffi/defcfn get-glyph-image
  "SDL_Surface * TTF_GetGlyphImage(TTF_Font * font, Uint32 ch, TTF_ImageType * image_type)"
  {:arglists '([font ch image-type]) :sdl/c "TTF_GetGlyphImage" :sdl/args [:pointer :uint32 :pointer] :sdl/ret :pointer}
  "TTF_GetGlyphImage" [:pointer :uint32 :pointer] :pointer)

(ffi/defcfn get-glyph-image-for-index
  "SDL_Surface * TTF_GetGlyphImageForIndex(TTF_Font * font, Uint32 glyph_index, TTF_ImageType * image_type)"
  {:arglists '([font glyph-index image-type]) :sdl/c "TTF_GetGlyphImageForIndex" :sdl/args [:pointer :uint32 :pointer] :sdl/ret :pointer}
  "TTF_GetGlyphImageForIndex" [:pointer :uint32 :pointer] :pointer)

(ffi/defcfn get-glyph-metrics
  "bool TTF_GetGlyphMetrics(TTF_Font * font, Uint32 ch, int * minx, int * maxx, int * miny, int * maxy, int * advance)"
  {:arglists '([font ch minx maxx miny maxy advance]) :sdl/c "TTF_GetGlyphMetrics" :sdl/args [:pointer :uint32 :pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetGlyphMetrics" [:pointer :uint32 :pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn get-glyph-kerning
  "bool TTF_GetGlyphKerning(TTF_Font * font, Uint32 previous_ch, Uint32 ch, int * kerning)"
  {:arglists '([font previous-ch ch kerning]) :sdl/c "TTF_GetGlyphKerning" :sdl/args [:pointer :uint32 :uint32 :pointer] :sdl/ret :bool}
  "TTF_GetGlyphKerning" [:pointer :uint32 :uint32 :pointer] :bool)

(ffi/defcfn get-string-size
  "bool TTF_GetStringSize(TTF_Font * font, const char * text, size_t length, int * w, int * h)"
  {:arglists '([font text length w h]) :sdl/c "TTF_GetStringSize" :sdl/args [:pointer :string :size_t :pointer :pointer] :sdl/ret :bool}
  "TTF_GetStringSize" [:pointer :string :size_t :pointer :pointer] :bool)

(ffi/defcfn get-string-size-wrapped
  "bool TTF_GetStringSizeWrapped(TTF_Font * font, const char * text, size_t length, int wrap_width, int * w, int * h)"
  {:arglists '([font text length wrap-width w h]) :sdl/c "TTF_GetStringSizeWrapped" :sdl/args [:pointer :string :size_t :int :pointer :pointer] :sdl/ret :bool}
  "TTF_GetStringSizeWrapped" [:pointer :string :size_t :int :pointer :pointer] :bool)

(ffi/defcfn measure-string
  "bool TTF_MeasureString(TTF_Font * font, const char * text, size_t length, int max_width, int * measured_width, size_t * measured_length)"
  {:arglists '([font text length max-width measured-width measured-length]) :sdl/c "TTF_MeasureString" :sdl/args [:pointer :string :size_t :int :pointer :pointer] :sdl/ret :bool}
  "TTF_MeasureString" [:pointer :string :size_t :int :pointer :pointer] :bool)

(ffi/defcfn render-text-solid
  "SDL_Surface * TTF_RenderText_Solid(TTF_Font * font, const char * text, size_t length, SDL_Color fg)"
  {:arglists '([font text length fg]) :sdl/c "TTF_RenderText_Solid" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderText_Solid" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-solid-wrapped
  "SDL_Surface * TTF_RenderText_Solid_Wrapped(TTF_Font * font, const char * text, size_t length, SDL_Color fg, int wrapLength)"
  {:arglists '([font text length fg wrap-length]) :sdl/c "TTF_RenderText_Solid_Wrapped" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :sdl/ret :pointer}
  "TTF_RenderText_Solid_Wrapped" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :pointer)

(ffi/defcfn render-glyph-solid
  "SDL_Surface * TTF_RenderGlyph_Solid(TTF_Font * font, Uint32 ch, SDL_Color fg)"
  {:arglists '([font ch fg]) :sdl/c "TTF_RenderGlyph_Solid" :sdl/args [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderGlyph_Solid" [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-shaded
  "SDL_Surface * TTF_RenderText_Shaded(TTF_Font * font, const char * text, size_t length, SDL_Color fg, SDL_Color bg)"
  {:arglists '([font text length fg bg]) :sdl/c "TTF_RenderText_Shaded" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderText_Shaded" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-shaded-wrapped
  "SDL_Surface * TTF_RenderText_Shaded_Wrapped(TTF_Font * font, const char * text, size_t length, SDL_Color fg, SDL_Color bg, int wrap_width)"
  {:arglists '([font text length fg bg wrap-width]) :sdl/c "TTF_RenderText_Shaded_Wrapped" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :sdl/ret :pointer}
  "TTF_RenderText_Shaded_Wrapped" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :pointer)

(ffi/defcfn render-glyph-shaded
  "SDL_Surface * TTF_RenderGlyph_Shaded(TTF_Font * font, Uint32 ch, SDL_Color fg, SDL_Color bg)"
  {:arglists '([font ch fg bg]) :sdl/c "TTF_RenderGlyph_Shaded" :sdl/args [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderGlyph_Shaded" [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-blended
  "SDL_Surface * TTF_RenderText_Blended(TTF_Font * font, const char * text, size_t length, SDL_Color fg)"
  {:arglists '([font text length fg]) :sdl/c "TTF_RenderText_Blended" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderText_Blended" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-blended-wrapped
  "SDL_Surface * TTF_RenderText_Blended_Wrapped(TTF_Font * font, const char * text, size_t length, SDL_Color fg, int wrap_width)"
  {:arglists '([font text length fg wrap-width]) :sdl/c "TTF_RenderText_Blended_Wrapped" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :sdl/ret :pointer}
  "TTF_RenderText_Blended_Wrapped" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :pointer)

(ffi/defcfn render-glyph-blended
  "SDL_Surface * TTF_RenderGlyph_Blended(TTF_Font * font, Uint32 ch, SDL_Color fg)"
  {:arglists '([font ch fg]) :sdl/c "TTF_RenderGlyph_Blended" :sdl/args [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderGlyph_Blended" [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-lcd
  "SDL_Surface * TTF_RenderText_LCD(TTF_Font * font, const char * text, size_t length, SDL_Color fg, SDL_Color bg)"
  {:arglists '([font text length fg bg]) :sdl/c "TTF_RenderText_LCD" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderText_LCD" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn render-text-lcd-wrapped
  "SDL_Surface * TTF_RenderText_LCD_Wrapped(TTF_Font * font, const char * text, size_t length, SDL_Color fg, SDL_Color bg, int wrap_width)"
  {:arglists '([font text length fg bg wrap-width]) :sdl/c "TTF_RenderText_LCD_Wrapped" :sdl/args [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :sdl/ret :pointer}
  "TTF_RenderText_LCD_Wrapped" [:pointer :string :size_t [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] :int] :pointer)

(ffi/defcfn render-glyph-lcd
  "SDL_Surface * TTF_RenderGlyph_LCD(TTF_Font * font, Uint32 ch, SDL_Color fg, SDL_Color bg)"
  {:arglists '([font ch fg bg]) :sdl/c "TTF_RenderGlyph_LCD" :sdl/args [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :sdl/ret :pointer}
  "TTF_RenderGlyph_LCD" [:pointer :uint32 [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]] [:by-value [:struct [[:r :uint8] [:g :uint8] [:b :uint8] [:a :uint8]]]]] :pointer)

(ffi/defcfn create-surface-text-engine
  "TTF_TextEngine * TTF_CreateSurfaceTextEngine(void)"
  {:arglists '([]) :sdl/c "TTF_CreateSurfaceTextEngine" :sdl/args [] :sdl/ret :pointer}
  "TTF_CreateSurfaceTextEngine" [] :pointer)

(ffi/defcfn draw-surface-text
  "bool TTF_DrawSurfaceText(TTF_Text * text, int x, int y, SDL_Surface * surface)"
  {:arglists '([text x y surface]) :sdl/c "TTF_DrawSurfaceText" :sdl/args [:pointer :int :int :pointer] :sdl/ret :bool}
  "TTF_DrawSurfaceText" [:pointer :int :int :pointer] :bool)

(ffi/defcfn destroy-surface-text-engine
  "void TTF_DestroySurfaceTextEngine(TTF_TextEngine * engine)"
  {:arglists '([engine]) :sdl/c "TTF_DestroySurfaceTextEngine" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_DestroySurfaceTextEngine" [:pointer] :void)

(ffi/defcfn create-renderer-text-engine
  "TTF_TextEngine * TTF_CreateRendererTextEngine(SDL_Renderer * renderer)"
  {:arglists '([renderer]) :sdl/c "TTF_CreateRendererTextEngine" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_CreateRendererTextEngine" [:pointer] :pointer)

(ffi/defcfn create-renderer-text-engine-with-properties
  "TTF_TextEngine * TTF_CreateRendererTextEngineWithProperties(SDL_PropertiesID props)"
  {:arglists '([props]) :sdl/c "TTF_CreateRendererTextEngineWithProperties" :sdl/args [:uint32] :sdl/ret :pointer}
  "TTF_CreateRendererTextEngineWithProperties" [:uint32] :pointer)

(ffi/defcfn draw-renderer-text
  "bool TTF_DrawRendererText(TTF_Text * text, float x, float y)"
  {:arglists '([text x y]) :sdl/c "TTF_DrawRendererText" :sdl/args [:pointer :float :float] :sdl/ret :bool}
  "TTF_DrawRendererText" [:pointer :float :float] :bool)

(ffi/defcfn destroy-renderer-text-engine
  "void TTF_DestroyRendererTextEngine(TTF_TextEngine * engine)"
  {:arglists '([engine]) :sdl/c "TTF_DestroyRendererTextEngine" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_DestroyRendererTextEngine" [:pointer] :void)

(ffi/defcfn create-gpu-text-engine
  "TTF_TextEngine * TTF_CreateGPUTextEngine(SDL_GPUDevice * device)"
  {:arglists '([device]) :sdl/c "TTF_CreateGPUTextEngine" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_CreateGPUTextEngine" [:pointer] :pointer)

(ffi/defcfn create-gpu-text-engine-with-properties
  "TTF_TextEngine * TTF_CreateGPUTextEngineWithProperties(SDL_PropertiesID props)"
  {:arglists '([props]) :sdl/c "TTF_CreateGPUTextEngineWithProperties" :sdl/args [:uint32] :sdl/ret :pointer}
  "TTF_CreateGPUTextEngineWithProperties" [:uint32] :pointer)

(ffi/defcfn get-gpu-text-draw-data
  "TTF_GPUAtlasDrawSequence * TTF_GetGPUTextDrawData(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetGPUTextDrawData" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_GetGPUTextDrawData" [:pointer] :pointer)

(ffi/defcfn destroy-gpu-text-engine
  "void TTF_DestroyGPUTextEngine(TTF_TextEngine * engine)"
  {:arglists '([engine]) :sdl/c "TTF_DestroyGPUTextEngine" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_DestroyGPUTextEngine" [:pointer] :void)

(ffi/defcfn set-gpu-text-engine-winding
  "void TTF_SetGPUTextEngineWinding(TTF_TextEngine * engine, TTF_GPUTextEngineWinding winding)"
  {:arglists '([engine winding]) :sdl/c "TTF_SetGPUTextEngineWinding" :sdl/args [:pointer :int] :sdl/ret :void}
  "TTF_SetGPUTextEngineWinding" [:pointer :int] :void)

(ffi/defcfn get-gpu-text-engine-winding
  "TTF_GPUTextEngineWinding TTF_GetGPUTextEngineWinding(const TTF_TextEngine * engine)"
  {:arglists '([engine]) :sdl/c "TTF_GetGPUTextEngineWinding" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetGPUTextEngineWinding" [:pointer] :int)

(ffi/defcfn create-text
  "TTF_Text * TTF_CreateText(TTF_TextEngine * engine, TTF_Font * font, const char * text, size_t length)"
  {:arglists '([engine font text length]) :sdl/c "TTF_CreateText" :sdl/args [:pointer :pointer :string :size_t] :sdl/ret :pointer}
  "TTF_CreateText" [:pointer :pointer :string :size_t] :pointer)

(ffi/defcfn get-text-properties
  "SDL_PropertiesID TTF_GetTextProperties(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetTextProperties" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetTextProperties" [:pointer] :uint32)

(ffi/defcfn set-text-engine
  "bool TTF_SetTextEngine(TTF_Text * text, TTF_TextEngine * engine)"
  {:arglists '([text engine]) :sdl/c "TTF_SetTextEngine" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "TTF_SetTextEngine" [:pointer :pointer] :bool)

(ffi/defcfn get-text-engine
  "TTF_TextEngine * TTF_GetTextEngine(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetTextEngine" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_GetTextEngine" [:pointer] :pointer)

(ffi/defcfn set-text-font
  "bool TTF_SetTextFont(TTF_Text * text, TTF_Font * font)"
  {:arglists '([text font]) :sdl/c "TTF_SetTextFont" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "TTF_SetTextFont" [:pointer :pointer] :bool)

(ffi/defcfn get-text-font
  "TTF_Font * TTF_GetTextFont(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetTextFont" :sdl/args [:pointer] :sdl/ret :pointer}
  "TTF_GetTextFont" [:pointer] :pointer)

(ffi/defcfn set-text-direction
  "bool TTF_SetTextDirection(TTF_Text * text, TTF_Direction direction)"
  {:arglists '([text direction]) :sdl/c "TTF_SetTextDirection" :sdl/args [:pointer :int] :sdl/ret :bool}
  "TTF_SetTextDirection" [:pointer :int] :bool)

(ffi/defcfn get-text-direction
  "TTF_Direction TTF_GetTextDirection(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetTextDirection" :sdl/args [:pointer] :sdl/ret :int}
  "TTF_GetTextDirection" [:pointer] :int)

(ffi/defcfn set-text-script
  "bool TTF_SetTextScript(TTF_Text * text, Uint32 script)"
  {:arglists '([text script]) :sdl/c "TTF_SetTextScript" :sdl/args [:pointer :uint32] :sdl/ret :bool}
  "TTF_SetTextScript" [:pointer :uint32] :bool)

(ffi/defcfn get-text-script
  "Uint32 TTF_GetTextScript(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_GetTextScript" :sdl/args [:pointer] :sdl/ret :uint32}
  "TTF_GetTextScript" [:pointer] :uint32)

(ffi/defcfn set-text-color
  "bool TTF_SetTextColor(TTF_Text * text, Uint8 r, Uint8 g, Uint8 b, Uint8 a)"
  {:arglists '([text r g b a]) :sdl/c "TTF_SetTextColor" :sdl/args [:pointer :uint8 :uint8 :uint8 :uint8] :sdl/ret :bool}
  "TTF_SetTextColor" [:pointer :uint8 :uint8 :uint8 :uint8] :bool)

(ffi/defcfn set-text-color-float
  "bool TTF_SetTextColorFloat(TTF_Text * text, float r, float g, float b, float a)"
  {:arglists '([text r g b a]) :sdl/c "TTF_SetTextColorFloat" :sdl/args [:pointer :float :float :float :float] :sdl/ret :bool}
  "TTF_SetTextColorFloat" [:pointer :float :float :float :float] :bool)

(ffi/defcfn get-text-color
  "bool TTF_GetTextColor(TTF_Text * text, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a)"
  {:arglists '([text r g b a]) :sdl/c "TTF_GetTextColor" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetTextColor" [:pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn get-text-color-float
  "bool TTF_GetTextColorFloat(TTF_Text * text, float * r, float * g, float * b, float * a)"
  {:arglists '([text r g b a]) :sdl/c "TTF_GetTextColorFloat" :sdl/args [:pointer :pointer :pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetTextColorFloat" [:pointer :pointer :pointer :pointer :pointer] :bool)

(ffi/defcfn set-text-position
  "bool TTF_SetTextPosition(TTF_Text * text, int x, int y)"
  {:arglists '([text x y]) :sdl/c "TTF_SetTextPosition" :sdl/args [:pointer :int :int] :sdl/ret :bool}
  "TTF_SetTextPosition" [:pointer :int :int] :bool)

(ffi/defcfn get-text-position
  "bool TTF_GetTextPosition(TTF_Text * text, int * x, int * y)"
  {:arglists '([text x y]) :sdl/c "TTF_GetTextPosition" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetTextPosition" [:pointer :pointer :pointer] :bool)

(ffi/defcfn set-text-wrap-width
  "bool TTF_SetTextWrapWidth(TTF_Text * text, int wrap_width)"
  {:arglists '([text wrap-width]) :sdl/c "TTF_SetTextWrapWidth" :sdl/args [:pointer :int] :sdl/ret :bool}
  "TTF_SetTextWrapWidth" [:pointer :int] :bool)

(ffi/defcfn get-text-wrap-width
  "bool TTF_GetTextWrapWidth(TTF_Text * text, int * wrap_width)"
  {:arglists '([text wrap-width]) :sdl/c "TTF_GetTextWrapWidth" :sdl/args [:pointer :pointer] :sdl/ret :bool}
  "TTF_GetTextWrapWidth" [:pointer :pointer] :bool)

(ffi/defcfn set-text-wrap-whitespace-visible
  "bool TTF_SetTextWrapWhitespaceVisible(TTF_Text * text, bool visible)"
  {:arglists '([text visible]) :sdl/c "TTF_SetTextWrapWhitespaceVisible" :sdl/args [:pointer :bool] :sdl/ret :bool}
  "TTF_SetTextWrapWhitespaceVisible" [:pointer :bool] :bool)

(ffi/defcfn text-wrap-whitespace-visible
  "bool TTF_TextWrapWhitespaceVisible(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_TextWrapWhitespaceVisible" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_TextWrapWhitespaceVisible" [:pointer] :bool)

(ffi/defcfn set-text-string
  "bool TTF_SetTextString(TTF_Text * text, const char * string, size_t length)"
  {:arglists '([text string length]) :sdl/c "TTF_SetTextString" :sdl/args [:pointer :string :size_t] :sdl/ret :bool}
  "TTF_SetTextString" [:pointer :string :size_t] :bool)

(ffi/defcfn insert-text-string
  "bool TTF_InsertTextString(TTF_Text * text, int offset, const char * string, size_t length)"
  {:arglists '([text offset string length]) :sdl/c "TTF_InsertTextString" :sdl/args [:pointer :int :string :size_t] :sdl/ret :bool}
  "TTF_InsertTextString" [:pointer :int :string :size_t] :bool)

(ffi/defcfn append-text-string
  "bool TTF_AppendTextString(TTF_Text * text, const char * string, size_t length)"
  {:arglists '([text string length]) :sdl/c "TTF_AppendTextString" :sdl/args [:pointer :string :size_t] :sdl/ret :bool}
  "TTF_AppendTextString" [:pointer :string :size_t] :bool)

(ffi/defcfn delete-text-string
  "bool TTF_DeleteTextString(TTF_Text * text, int offset, int length)"
  {:arglists '([text offset length]) :sdl/c "TTF_DeleteTextString" :sdl/args [:pointer :int :int] :sdl/ret :bool}
  "TTF_DeleteTextString" [:pointer :int :int] :bool)

(ffi/defcfn get-text-size
  "bool TTF_GetTextSize(TTF_Text * text, int * w, int * h)"
  {:arglists '([text w h]) :sdl/c "TTF_GetTextSize" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetTextSize" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-text-sub-string
  "bool TTF_GetTextSubString(TTF_Text * text, int offset, TTF_SubString * substring)"
  {:arglists '([text offset substring]) :sdl/c "TTF_GetTextSubString" :sdl/args [:pointer :int :pointer] :sdl/ret :bool}
  "TTF_GetTextSubString" [:pointer :int :pointer] :bool)

(ffi/defcfn get-text-sub-string-for-line
  "bool TTF_GetTextSubStringForLine(TTF_Text * text, int line, TTF_SubString * substring)"
  {:arglists '([text line substring]) :sdl/c "TTF_GetTextSubStringForLine" :sdl/args [:pointer :int :pointer] :sdl/ret :bool}
  "TTF_GetTextSubStringForLine" [:pointer :int :pointer] :bool)

(ffi/defcfn get-text-sub-strings-for-range
  "TTF_SubString ** TTF_GetTextSubStringsForRange(TTF_Text * text, int offset, int length, int * count)"
  {:arglists '([text offset length count]) :sdl/c "TTF_GetTextSubStringsForRange" :sdl/args [:pointer :int :int :pointer] :sdl/ret :pointer}
  "TTF_GetTextSubStringsForRange" [:pointer :int :int :pointer] :pointer)

(ffi/defcfn get-text-sub-string-for-point
  "bool TTF_GetTextSubStringForPoint(TTF_Text * text, int x, int y, TTF_SubString * substring)"
  {:arglists '([text x y substring]) :sdl/c "TTF_GetTextSubStringForPoint" :sdl/args [:pointer :int :int :pointer] :sdl/ret :bool}
  "TTF_GetTextSubStringForPoint" [:pointer :int :int :pointer] :bool)

(ffi/defcfn get-previous-text-sub-string
  "bool TTF_GetPreviousTextSubString(TTF_Text * text, const TTF_SubString * substring, TTF_SubString * previous)"
  {:arglists '([text substring previous]) :sdl/c "TTF_GetPreviousTextSubString" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetPreviousTextSubString" [:pointer :pointer :pointer] :bool)

(ffi/defcfn get-next-text-sub-string
  "bool TTF_GetNextTextSubString(TTF_Text * text, const TTF_SubString * substring, TTF_SubString * next)"
  {:arglists '([text substring next]) :sdl/c "TTF_GetNextTextSubString" :sdl/args [:pointer :pointer :pointer] :sdl/ret :bool}
  "TTF_GetNextTextSubString" [:pointer :pointer :pointer] :bool)

(ffi/defcfn update-text
  "bool TTF_UpdateText(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_UpdateText" :sdl/args [:pointer] :sdl/ret :bool}
  "TTF_UpdateText" [:pointer] :bool)

(ffi/defcfn destroy-text
  "void TTF_DestroyText(TTF_Text * text)"
  {:arglists '([text]) :sdl/c "TTF_DestroyText" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_DestroyText" [:pointer] :void)

(ffi/defcfn close-font
  "void TTF_CloseFont(TTF_Font * font)"
  {:arglists '([font]) :sdl/c "TTF_CloseFont" :sdl/args [:pointer] :sdl/ret :void}
  "TTF_CloseFont" [:pointer] :void)

(ffi/defcfn quit
  "void TTF_Quit(void)"
  {:arglists '([]) :sdl/c "TTF_Quit" :sdl/args [] :sdl/ret :void}
  "TTF_Quit" [] :void)

(ffi/defcfn was-init
  "int TTF_WasInit(void)"
  {:arglists '([]) :sdl/c "TTF_WasInit" :sdl/args [] :sdl/ret :int}
  "TTF_WasInit" [] :int)
