;; GENERATED by tools/gen.clj from the SDL3 headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from Simple DirectMedia Layer, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.raw.vulkan
  "Raw bindings for SDL_vulkan.h: one jolt.ffi/defcfn per exported C function,
  named by kebab-casing the C name without its SDL_ prefix, and one ffi/layout per
  struct. Nothing here checks errors or converts values — see the sdl3.* namespaces."
  (:require [jolt.ffi :as ffi]))

;; ---- functions -----------------------------------------------------------

(ffi/defcfn vulkan-load-library
  "bool SDL_Vulkan_LoadLibrary(const char * path)"
  {:arglists '([path]) :sdl/c "SDL_Vulkan_LoadLibrary" :sdl/args [:string] :sdl/ret :bool}
  "SDL_Vulkan_LoadLibrary" [:string] :bool)

(ffi/defcfn vulkan-get-vk-get-instance-proc-addr
  "SDL_FunctionPointer SDL_Vulkan_GetVkGetInstanceProcAddr(void)"
  {:arglists '([]) :sdl/c "SDL_Vulkan_GetVkGetInstanceProcAddr" :sdl/args [] :sdl/ret :pointer}
  "SDL_Vulkan_GetVkGetInstanceProcAddr" [] :pointer)

(ffi/defcfn vulkan-unload-library
  "void SDL_Vulkan_UnloadLibrary(void)"
  {:arglists '([]) :sdl/c "SDL_Vulkan_UnloadLibrary" :sdl/args [] :sdl/ret :void}
  "SDL_Vulkan_UnloadLibrary" [] :void)

(ffi/defcfn vulkan-get-instance-extensions
  "char const * const * SDL_Vulkan_GetInstanceExtensions(Uint32 * count)"
  {:arglists '([count]) :sdl/c "SDL_Vulkan_GetInstanceExtensions" :sdl/args [:pointer] :sdl/ret :pointer}
  "SDL_Vulkan_GetInstanceExtensions" [:pointer] :pointer)
