;; GENERATED by tools/gen.clj from the SDL_net headers — do not edit by hand.
;; Regenerate with `jolt gen` (see deps.edn :tasks).
;; Reproduces declarations from SDL_net, Copyright (C) 1997-2026
;; Sam Lantinga <slouken@libsdl.org>, zlib license; see LICENSE.
(ns sdl3.consts.net
  "Every SDL_net enum and flag set as a map from keyword to value, plus
  property name strings. `-names` maps invert an enum (first-declared name wins
  for aliased values). Values were computed by compiling the C headers."
  (:refer-clojure :exclude [keys]))

(def status
  "NET_Status (NET_*)."
  {:failure -1, :success 1, :waiting 0})

(def status-names
  "NET_Status value -> keyword (the first-declared name of an aliased value)."
  {-1 :failure, 0 :waiting, 1 :success})

(def prop
  "#define NET_PROP_*."
  {:datagram-socket-allow-broadcast-boolean "NET.datagram_socket.allow_broadcast", :datagram-socket-reuseaddr-boolean "NET.datagram_socket.reuseaddr", :server-reuseaddr-boolean "NET.server.reuseaddr"})

(def misc
  "#define NET_*."
  {:net-major-version 3, :net-micro-version 0, :net-minor-version 2})

